### ISSUE TITLE
Manager configuration edition - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1238]
Tasks - cluster disabled:

- [x] Edit manager configuration 
- [x] Restart manager 

Tasks - cluster enabled:

- [x] Edit master configuration 
- [x] Restart master
- [x] Edit worker configuration 
- [x] Restart worker
- [x] Restart cluster

Misc tasks:

- [ ] Try all the error scenarios

**Comment by pablotr9** [comment]
**Tasks - cluster enabled:**

* _Edit master configuration_
**OK**. If configuration is correct, master configuration is successfully updated.
* _Restart master_
**OK**. If configuration is correct, master configuration is succesfully updated.
**FAIL**. If configuration is wrong, wazuh-manager fails: 
 **FAIL** Empty tags \<disabled>\</disabled> (is saved as \<disabled/>)
 **FAIL** Using text instead of number: \<timeout>AAA\</timeout>
 **FAIL** Using text instead of yes/no: \<disabled>AAA\</disabled>

* _Edit worker configuration_
**OK**. If the configuration is correct, worker configuration is successfully updated.
*  _Restart worker_
**OK**. If the configuration is correct, master configuration is successfully updated.
**FAIL**. Same errors as restarting master when the configuration is wrong.

* _Restart cluster_ (Management->Status->RestartCluster).
 **Ok**. Cluster is restarted correctly if configuration is correct.
**FAIL**. If  `/cluster/configuration/validation` fails, RestartCluster button is disabled permanently.

**Comment by pablotr9** [comment]
Tasks - cluster disabled:

* [x]  Edit manager configuration
**OK**. Manager configuration updated succesfully if configuration is correct.
* [x]  Restart manager
**OK**. Manager is succesfully restarted if configuration is correct otherwise the list of errors is shown.


Tasks - cluster enabled:
* [x]  Edit master configuration
* [x]  Restart master
* [x]  Edit worker configuration
* [x]  Restart worker
* [x]  Restart cluster
**OK**. (Management->Status->Restart) Cluster is succesfully restarted if configuration is correct otherwise the list of errors is shown.

Misc tasks:
* [ ]  Try all the error scenarios


**FAIL**. When saving a worker's configuration, the validation was done against the master configuration instead of that node's configuration.
**FAIL**. Wrong api call when cluster->disabled option was modified.
