### ISSUE TITLE
[elastic-7] Tasks summary

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1386]
This ticket is intended to track all tasks related to Elastic 7:

- [ ] Configuration files and alerts template #1382 
- [ ] How to reindex from 6.x to 7.x #1383
- [ ] Adapt Wazuh app code #1385  
- [ ] Security features (X-Pack, Search Guard) #1387
- [ ] Docker deployments #1388  
- [ ] Testing #1384 

Regards
