### ISSUE TITLE
Logtest from the app

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1434]
With the amazing enhancements and capabilities done to the app with version 3.9.0 the experience of creating custom decoders and rules has been greatly improved. 

Almost everything can now be done through the web interface while also having the added benefit of syntax and general verification as the files are being edited.

It feels only natural to provide the users with the ability to test log messages as their rules and decoders are being written in that interface, with the possibility of providing even better feedback.

So this issue is to request a tool to test how the ruleset would react to specific log messages. As an enhancement upon the ossec-logtest, it could visually provide an interactive tree of all the rules showing the "path" taken by analysisd and highlighting why each rule and decoder matched (so like `ossec-logtest -v` but interactive).

---------------------------------------------

(@jesusgn90 added)

The main target of this ticket is to give the user the ability to do not need to log in using SSH into the Wazuh manager instance for testing a sample log.

- [x] Components
  - [x] Input box for reading the sample log.
  - [x] Button/action element for sending the sample log.
  - [x] Output box for showing the results.
- [x] Design
  - [x] This feature should be easily accessible from almost every Ruleset section, the user may want to test a log when modifying decoders or after saving a new rule for example.
  - [x] By default it should be hidden.
  - [x] It should not be very intrusive, should work at the same time you are editing or creating a ruleset file. Think about a user with the strategy _trial and error_, the user would expect to quickly try the sample log multiple times until the ruleset modification is done.

**Update 24/09/2019**
**Pending-api** and **Pending-core** https://github.com/wazuh/wazuh-api/issues/449
- [x] Logic
  - [x] Connect with an API endpoint.
  - [x] Handle unexpected results properly.
  - [x] Limit the input so we don't crash the API or the logtest tool.

**Comment by juankaromo** [comment]
Hi team,

For the first iteration of this issue, I've designed de solution below:

A new button for open de `logtest` section would be added on rules and decoders sections:
![image](https://user-images.githubusercontent.com/21195730/64184818-5935d200-ce6c-11e9-81ed-f758ce8ccf3f.png)

This button would open a new section with an empty text area where introduce the log, and a text viewer on seeing the `logtest` result:

![image](https://user-images.githubusercontent.com/21195730/64185461-77500200-ce6d-11e9-840c-c14dae79c67a.png)

It will be possible thanks to a new API endpoint that sending a log in string fromat e.g.:

```js
{"timestamp":"2019-09-03T13:22:27.950+0000","rule":{"level":7,"description":"python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms","id":"23504","firedtimes":33,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"]},"agent":{"id":"000","name":"a205e5b2a1aa"},"manager":{"name":"a205e5b2a1aa"},"id":"1567516947.252273","cluster":{"name":"wazuh","node":"master"},"decoder":{"name":"json"},"data":{"vulnerability":{"cve":"CVE-2019-9948","title":"python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms","severity":"Medium","published":"2019-03-23T00:00:00+00:00","state":"Fixed","cvss":{"cvss3_score":"7.400000"},"package":{"name":"python","version":"2.7.5-80.el7_6","condition":"less than 2.7.5-86.el7"},"advisories":"RHSA-2019:2030,RHSA-2019:1700","cwe_reference":"CWE-749","bugzilla_reference":"https://bugzilla.redhat.com/show_bug.cgi?id=1695570","reference":"https://access.redhat.com/security/cve/CVE-2019-9948"}},"location":"vulnerability-detector"}
```

Returns us a `logtest` result in plain text as well e.g.: 

```js
**Phase 1: Completed pre-decoding.
       full event: 'timestamp:2019-09-03T13:22:27.950+0000 rule:level:7 rule:description:python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms rule:id:23504 rule:firedtimes:33 rule:mail:false rule:groups:[vulnerability-detector] rule:gdpr:[IV_35.7.d] agent:id:000 agent:name:a205e5b2a1aa manager:{name:a205e5b2a1aa} id:1567516947.252273 cluster:name:wazuh cluster:node:master decoder:{name:json} data:{vulnerability:cve:CVE-2019-9948} data:{vulnerability:title:python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms} data:{vulnerability:severity:Medium} data:{vulnerability:published:2019-03-23T00:00:00+00:00} data:{vulnerability:state:Fixed} data:{vulnerability:cvss:{cvss3_score:7.400000}} data:{vulnerability:package:name:python} data:{vulnerability:package:version:2.7.5-80.el7_6} data:{vulnerability:package:condition:less than 2.7.5-86.el7} data:{vulnerability:advisories:RHSA-2019:2030,RHSA-2019:1700} data:{vulnerability:cwe_reference:CWE-749} data:{vulnerability:bugzilla_reference:https://bugzilla.redhat.com/show_bug.cgi?id=1695570} data:{vulnerability:reference:https://access.redhat.com/security/cve/CVE-2019-9948} location:vulnerability-detector'
       timestamp: '(null)'
       hostname: 'a205e5b2a1aa'
       program_name: '(null)'
       log: 'timestamp:2019-09-03T13:22:27.950+0000 rule:level:7 rule:description:python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms rule:id:23504 rule:firedtimes:33 rule:mail:false rule:groups:[vulnerability-detector] rule:gdpr:[IV_35.7.d] agent:id:000 agent:name:a205e5b2a1aa manager:{name:a205e5b2a1aa} id:1567516947.252273 cluster:name:wazuh cluster:node:master decoder:{name:json} data:{vulnerability:cve:CVE-2019-9948} data:{vulnerability:title:python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms} data:{vulnerability:severity:Medium} data:{vulnerability:published:2019-03-23T00:00:00+00:00} data:{vulnerability:state:Fixed} data:{vulnerability:cvss:{cvss3_score:7.400000}} data:{vulnerability:package:name:python} data:{vulnerability:package:version:2.7.5-80.el7_6} data:{vulnerability:package:condition:less than 2.7.5-86.el7} data:{vulnerability:advisories:RHSA-2019:2030,RHSA-2019:1700} data:{vulnerability:cwe_reference:CWE-749} data:{vulnerability:bugzilla_reference:https://bugzilla.redhat.com/show_bug.cgi?id=1695570} data:{vulnerability:reference:https://access.redhat.com/security/cve/CVE-2019-9948} location:vulnerability-detector'
**Phase 2: Completed decoding.
       No decoder matched.
**Phase 3: Completed filtering (rules).
       Rule id: '1002'
       Level: '2'
       Description: 'Unknown problem somewhere in the system.'
```

The API issue is this https://github.com/wazuh/wazuh-api/issues/449

Regards.

**Comment by juankaromo** [comment]
**Update 04/09/2019**

Today I implemented a new ruleset shortcuts component. From these shortcuts, you can create a new file (either rule, decoder or lists), upload files, and open the `Logtest`.

For this, I have used the `eui` Key Pad Menu component and the Item buttons.

![shortcuts](https://user-images.githubusercontent.com/21195730/64270462-db40fc00-cf3b-11e9-9ce8-0509423a7561.gif)


On the other hand, for the Logtest, the requests have been mocked, and a component has been created consisting of a text area where the log would be introduced, and on the other hand, a `config-viewer` where the result would be seen.

![logtest](https://user-images.githubusercontent.com/21195730/64270467-e005b000-cf3b-11e9-9c34-68a8b50314a6.gif)

**Comment by juankaromo** [comment]
**Update 05/09/2019**

Today the navigation in ruleset tabs was changed. The right sidebar was deprecated by an improved action bar inside the tables. On the other hand, the way to show the result of the test has been changed from `wz-xml-file-viewer` to eui `CodeBlock`.

![logtest2](https://user-images.githubusercontent.com/21195730/64355393-6cc67180-d001-11e9-8d24-c49617bd91b1.gif)

Additionally, the design of the ruleset tables has been improved to adapt them to the look and feel of eui tables (they are not going to be migrated still).

![image](https://user-images.githubusercontent.com/21195730/64355515-a7300e80-d001-11e9-850e-426c051bcaf1.png)

**Comment by juankaromo** [comment]
**Update 06/09/2019**

Today the design and logic of the testlog have been improved.  In addition, the ruleset tables have been redesigned to resemble `eui`, and the navigability of the section has been improved.

Finally, the `upload-files` component has been integrated into the branch.

![refactor_ruleset](https://user-images.githubusercontent.com/21195730/64438946-466c0900-d0c9-11e9-8b6d-0204f4a31ea8.gif)

Branch: https://github.com/wazuh/wazuh-kibana-app/tree/logtest

**Comment by juankaromo** [comment]
**Update 09/09/2019**

Today I've done an alternative mode to show de logtest. I renamed de Dev tools section by Tools. In this section, I would show selectable cards with some options. The first would be the old dev tools console, named now API Dev console, and a second option that would be the logtest.

It looks like this:

![wazuh-tools](https://user-images.githubusercontent.com/21195730/64542600-1f5d4380-d324-11e9-9886-4014ff8e9d73.gif)

**Comment by juankaromo** [comment]
**Update** 

Update of the tools section

![toolssection](https://user-images.githubusercontent.com/21195730/65218752-6e8b3d00-dab7-11e9-82bf-7432cca4dba6.gif)

**Comment by jctello** [comment]
I'm really looking forward to this feature as it completes the Kibana workflow for creating rules and decoders. 

If possible (maybe for a future release as not to delay this one) it would be great if it would have the option of the `verbose` functionality from the `ossec-logtest -v` utility, in order to determine the reason why a log may have not matched the expected rule.

Maybe the `debug` modifier could be also useful.

**Comment by Joanes04** [comment]
**Update 13/07/2020**

The implementation of Logtest from the app has been resumed. We have added a new login menu and a new view for Logtest:

![new_view_logtest](https://user-images.githubusercontent.com/9945959/87296387-fa6acb80-c506-11ea-89cd-b15583ea1c4a.gif)

We've also added some accesses from the Rules, Decoders and CDB Lists view, which keeps the session open while you browse these sections, so you can try out the different options:

![flyout](https://user-images.githubusercontent.com/9945959/87296707-79f89a80-c507-11ea-97a3-47181fc52828.gif)

**Comment by jsanchez91** [comment]
Related Issues:
- https://github.com/wazuh/wazuh/issues/5337
- https://github.com/wazuh/wazuh/issues/5590
- https://github.com/wazuh/wazuh/issues/5577

**Comment by gabiwassan** [comment]
Working on this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/3055) (draft). 
- Requests have already been added

**Comment by gabiwassan** [comment]
[PR](https://github.com/wazuh/wazuh-kibana-app/pull/3039/) on revision.
