### ISSUE TITLE
Testing for #1484

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1526]
Minimum tests:

- [x] Overview welcome screen with no agents, same with agents, review console from the browser and make some reloads (F5)
- [x] Agent welcome screen with never connected, disconnected, and active agent, review console from the browser and make some reloads (F5)
- [x] Agent > Syscollector for Linux, Windows and MacOS agent, it should be different depending on the OS, and it should not fail regardless of the information the Wazuh API could give us. [see comment](https://github.com/wazuh/wazuh-kibana-app/issues/1526#issuecomment-500587618)
- [x] Force the API to throw "socket error" like errors shutting down a node, an agent, killing some of the main daemons, combining all of that with some edition features such a rule edition. Found a tiny _bug_, already fixed and pushed [see comment](https://github.com/wazuh/wazuh-kibana-app/issues/1526#issuecomment-500587618), even with our latest changes, the app behavior for these situations is the same as before (it doesn't imply it is the best, but we didn't introduce bugs with these changes)
- [x] Play with the extensions in both Overview welcome and Agent welcome sections, check if all is working as before.
- [x] Review some UI elements like the menu directive in the most common browsers (Chrome, Safari, Firefox) __not tested in Safari, but tested in Firefox which uses to fail the same as Safari__
- [x] Check if the same info toaster is not being displayed twice or more. 
- [x] Use the API form from settings: add, delete, edit API entries. [see comment](https://github.com/wazuh/wazuh-kibana-app/issues/1526#issuecomment-500587618)
- [x] Review if all the "AlertsStats" instances are working as expected. [see comment](https://github.com/wazuh/wazuh-kibana-app/issues/1526#issuecomment-500587618)

**Comment by jesusgn90** [comment]
Forgot to add the _state_ translation as we did before, right now it showing just the letter (it's correct but not human-readable):

![image](https://user-images.githubusercontent.com/8860227/59223349-fc5bb000-8bcb-11e9-81dd-34caff174ccc.png)

Here we are showing `-` instead of `0` as we do in other places:

![image](https://user-images.githubusercontent.com/8860227/59223414-2614d700-8bcc-11e9-801d-f040beb4eb65.png)

When editing an existing one API entry, if you fill it with wrong values it shows the error and the API entry updating is rejected (that's right) but it closes the form, it should be opened until the edition is right or the user closes the form by itself:

![image](https://user-images.githubusercontent.com/8860227/59223582-958ac680-8bcc-11e9-81c6-ddd425d8ed04.png)

The `mtu` key for syscollector is not being translated (`mtu` should be `MTU`)

![image](https://user-images.githubusercontent.com/8860227/59223973-86584880-8bcd-11e9-89b8-efb6de2ccb4c.png)

For the daemons checking, I've discovered a tiny _bug_, for the `wazuh-db` and the `clusterd` daemons we were checking always them as `true`. The next change has been made and properly validated https://github.com/wazuh/wazuh-kibana-app/commit/cddcef630c5234dd6f6a495715743dfcfd4e4001
