### ISSUE TITLE
[backports-6.8.x] from 3.10-7.3

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1712]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10   | 6.8     | n/a |

**Tasks we need to migrate from 3.10-7.3**

- [x] Filter by namespace the index pattern list #1450
- [x] Support new compliance groups HIPAA and NIST 800 53 #1448
- [x] [visualize] Fix top line of "Agents status" visualization #1379
- [x] Interactive guide for registering agents #1468
- [x] Export agent configuration #1340
- [x] Export group related information #1341
- [x] Syscollector network interfaces table doesn't paginate #1474
- [x] Disable agent configuration export if it's not active #1519
- [x] Update NIST 800-53 requirements descriptions #1532
- [x] Move ".wazuh-version" information to a registry file #1467
- [x] Wazuh app doesn't open under custom spaces #1234
- [x] Granular options for agent configuration reports #1518
- [x] Alert from empty configuration when exporting agent configuration #1538
- [x] Timezone is not always applied correctly #1612
- [x] AWS-S3 configuration is not being shown correctly #1675
- [x] Alerts search bar works randomly #1686
- [x] Installation date for the Wazuh app is not being updated properly #1692
- [x] Hide/Block the Wazuh app depending on the selected Kibana space #1601
- [x] add search/discover logs to "Overview / Integrity monitoring" dasboard #1527
- [x] Review PUT and DELETE calls from management sections #1555
- [x] Menu directive is hidden when the route changes #1502
- [x] Timeouts in cluster monitoring #1663
- [x] Fully remove "known-fields.js" file and its related logic #1682
- [x] Monitoring section tabs not working properly #1707
- [x] Hide atrributes field from non Windows agents FIM files #1710
- [x] Rebuild HIPAA and NIST-800-53 dashboards #1638

**Tasks we aren't going to migrate**

- The dark theme (Adapt Wazuh app for Kibana dark mode #1562) will only be applied in 3.10-7.3 because in 6.8 the dark theme of Kibana is applied only to the dashboards and not to the whole application.
