### ISSUE TITLE
Redesign tables using react EuiTables

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1829]
In order to improve the user feel it is necessary to change the current `wz-table` directive to the `EuiTables` component.

- [x] Groups  https://github.com/wazuh/wazuh-kibana-app/tree/euitables-groups-1829
  - [x] The groups table
  - [x] Table with the agents in the group
  - [x] Table with the files in the group
- [x] Agents
  - [x] The agents-preview table
  - [x] Agent > Integrity monitoring table
- [x] Management [ #1899]  https://github.com/wazuh/wazuh-kibana-app/tree/euitables-ruleset-1829
  - [x] Rules
  - [x] Decoders
  - [x] CDB lists
- [x]  Agents > File integrity monitoring

**Comment by adri9valle** [comment]
**Update 10.02.19**

Branch: [https://github.com/wazuh/wazuh-kibana-app/tree/ui-changes](ui-changes)

The groups table has been modified, also the way to add a new group:
![image](https://user-images.githubusercontent.com/7983984/66046955-204e5300-e527-11e9-823e-16ccfccfa10f.png)

![image](https://user-images.githubusercontent.com/7983984/66046933-1298cd80-e527-11e9-80fd-aab3f2ffb787.png)

![image](https://user-images.githubusercontent.com/7983984/66046945-188eae80-e527-11e9-9855-65b0d012dd74.png)

**Comment by adri9valle** [comment]
**Update 03.10.19**

The Groups controller is now a class, but since the `wz-table` was replaced by the `EuiTable` when accessing into a group the App redirects again to the main group table.

**Comment by adri9valle** [comment]
**Update 04.10.19**

The table of the agents in a group works properly, lists, removes and navigates to an agent.

**TODO**
- Implement the PDF report module in the table

**Comment by jsanchez91** [comment]
Create a new react component to replace the agent preview table.

![image (5)](https://user-images.githubusercontent.com/3064506/66217318-5aeef180-e6c7-11e9-9364-0bfe040526c4.png)

**Comment by adri9valle** [comment]
**Update 07.10.19**

The table for listing the agents in a group is finished:

**Added/Solved**:

- Implement the PDF report module in the table
- Apply the filters when exporting the CSV

![image](https://user-images.githubusercontent.com/7983984/66301220-fdd98280-e8f6-11e9-8489-d71fe79b25fa.png)

**NOTE:** Most probably the tabs will be replaced by a selector near the query bar in order to change between agents and files:

This:
![image](https://user-images.githubusercontent.com/7983984/66301400-590b7500-e8f7-11e9-83f6-1c5238f9460e.png)

By something similar to this:
![image](https://user-images.githubusercontent.com/7983984/66301665-d800ad80-e8f7-11e9-860a-47bdb19839f0.png)

**Comment by jsanchez91** [comment]
Remove the blue header from the table and add the actions section in the upper right corner.

![image](https://user-images.githubusercontent.com/3064506/66320413-1362a280-e91f-11e9-8390-1051878edad0.png)

**Comment by adri9valle** [comment]
**Update 10.11.19**

Implemented redux to refresh the state between components, in the future the APP will use redux in order to improve the data managing.

**Comment by jsanchez91** [comment]
I pass the `apiReq` service to the component.

Now the agents is paginated in the request, this improvement the behevior in environments with many agents.

![agents-table](https://user-images.githubusercontent.com/3064506/66664098-34433480-ec4c-11e9-9494-e3793ac751ab.gif)

**Comment by jsanchez91** [comment]
I integrate the component `WzFilterBar` created by @juankaromo 

![agents_q](https://user-images.githubusercontent.com/3064506/66846015-6c5eb600-ef71-11e9-904a-ba361a5958c4.gif)

**Comment by adri9valle** [comment]
**Update**

- The file content is shown as raw.
- The rule and decoder information is shown as raw.

Working in a new component to show the information and the raw content.

**Comment by jsanchez91** [comment]
**Update**

I push some commits with improvements in the performance of the component 

---
Progress:
- [x]  Load items dynamically
- [x] Api request with pagination
- [x] Api request with sort
- [x] Api request with q filter
- [x] Api request with search filter
- [ ] FilterBar with dynamic fields
- [ ] Link rows with agents
- [ ] Link actions buttons with agents

**Comment by adri9valle** [comment]
**Update**

Currently works:

- Show rules, decoder and lists in a table (TODO improve the pagination)
- Change between rules/decoders and rules/decoders files
- Export as CSV
- Import files
- Show rule information
- Filter bar implemented
- Set filter from rule information view



![image](https://user-images.githubusercontent.com/7983984/67404862-3f835200-f5b4-11e9-80be-7caf423d066f.png)

![image](https://user-images.githubusercontent.com/7983984/67405104-9721bd80-f5b4-11e9-9f6d-63797d9171e1.png)

![image](https://user-images.githubusercontent.com/7983984/67405142-a3a61600-f5b4-11e9-8555-2a4e36d09358.png)

![image](https://user-images.githubusercontent.com/7983984/67405182-b3255f00-f5b4-11e9-991b-3c705a19ae2e.png)

![rules](https://user-images.githubusercontent.com/7983984/67405391-fc75ae80-f5b4-11e9-8fe3-942dd9e48b4f.gif)

**Comment by jsanchez91** [comment]
Currently work:

Filter list:
---
![filters](https://user-images.githubusercontent.com/3064506/67786689-98992d00-fa6f-11e9-96be-693b54013c6d.

Select filters:
---
![select_filters](https://user-images.githubusercontent.com/3064506/67786811-ca11f880-fa6f-11e9-8cd0-72de77e26020.gif)

Search
---
![search](https://user-images.githubusercontent.com/3064506/67786911-f88fd380-fa6f-11e9-860c-447431eec2e7.gif)

Add new agent button:
---
![add_new_agent](https://user-images.githubusercontent.com/3064506/67786936-02b1d200-fa70-11e9-81fb-3527f03f7e53.gif)

Formated button (download csv):
---
![formated](https://user-images.githubusercontent.com/3064506/67787012-1eb57380-fa70-11e9-9c2f-af17b27ea3b2.gif)

**Comment by jsanchez91** [comment]
1. Should show `add new agent` component if no have agents register.
2. Should show the agents if the manager has registered agents.
3. The empty fields should be shown as '-'.
4. The number of items shown must be equal to the value `Rows per page`.
5. If the "row per page" value is changed, the number of displayed items must be changed.
6. The pagination must be consistence.
7. All columns except 'action' can be sorted.
8. If a filter is applied, the table should show only matching items.
9. If a second filter is applied this should have an `AND` label.
10. If you type something in the filter bar, a search filter must be applied.
11. If reload the browser the filter should be persistent.
12. If delete the filters the table should show all agents.
13. The `Formated` button should download all displayed agents in a CSV file.
14. The `Add new agent` button should show the form to add agents.
15. The agent with id `000` should never be shown.

Code Test | Chrome | Firefox | Edge | Safari
------------ | ------------- | ------------- | ------------- | -------------
1 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
2 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
3 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
4 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
5 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
6 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
7 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
8 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
9 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
10 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
11 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
12 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
13 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
14 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:
15 | :heavy_check_mark: | :black_square_button: | :black_square_button: | :black_square_button:

**Comment by pablotr9** [comment]
**Update** 
Agents -> File Integrity Monitoring. This table has been redesigned using react EuiTables. #1941
