### ISSUE TITLE
Review all API requests (included dev-tools autocomplete)

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2001]
Hi team!

After studying the new **API 4.0**, and checking the current API documentation, we have come to the conclusion that we need to review every single call running from FrontEnd to the Wazuh API, and make the necessary changes in all API calls to ensure the proper functioning of the APP.

To organize the workflow, we have created a development branch, [new-api](https://github.com/wazuh/wazuh-kibana-app/tree/new-api), thanks to the **Git-Flow** tool, which will be our main development branch. <del>This branch will be continuously updated from branch [3.12-7.5](https://github.com/wazuh/wazuh-kibana-app/tree/3.12-7.5).</del> This branch will be continuously updated from branch [3.13-7.6](https://github.com/wazuh/wazuh-kibana-app/tree/3.123-7.6).
From this branch, we'll create each **feature** that comes up, using the `NewApi/` prefix. 

Once all of the above has been described, the following questions should be completed in order to finish this issue:

- [x] [NewApi Review: api-tester.js](https://github.com/wazuh/wazuh-kibana-app/issues/2034) @Joanes04 and @Desvelao 
- [x] [NewApi Review: api/request](https://github.com/wazuh/wazuh-kibana-app/issues/2043) @pablotr9 
- [x] [NewApi Review: Overview section](https://github.com/wazuh/wazuh-kibana-app/issues/2054) @pablotr9 
- [x] [NewApi Review: health-check](https://github.com/wazuh/wazuh-kibana-app/issues/2036) @Joanes04 
- [x] [NewApi Review: Management section](https://github.com/wazuh/wazuh-kibana-app/issues/2049) @pablotr9 @Joanes04 
- [x] [NewApi Review: agents section](https://github.com/wazuh/wazuh-kibana-app/issues/2044) @Desvelao 
- [x] [NewApi Review: Settings section ](https://github.com/wazuh/wazuh-kibana-app/issues/2050) @pablotr9 
- [x]  [NewApi Review: DevTools section](https://github.com/wazuh/wazuh-kibana-app/issues/2053) @Joanes04 
- [x] [NewApi Review: Monitoring](https://github.com/wazuh/wazuh-kibana-app/issues/2055) @pablotr9  @Joanes04 
- [x] [NewApi Review: Export PDF report](https://github.com/wazuh/wazuh-kibana-app/issues/2073) @Joanes04 

**At this point, some of the API 4.0 endpoints have been changed, and some things already reviewed need to be revisited, so we created new issues that are already solved:**

- [x] [NewApi Review: Adapt new Rules](https://github.com/wazuh/wazuh-kibana-app/issues/2167) @Joanes04 
- [x] [NewApi Review: Adapt new Decoders](https://github.com/wazuh/wazuh-kibana-app/issues/2168) @Joanes04 
- [x] [NewApi Review: Adapt new CDB Lists](https://github.com/wazuh/wazuh-kibana-app/issues/2177) @Joanes04 
- [x] [NewApi Review: Adapt new Groups](https://github.com/wazuh/wazuh-kibana-app/issues/2179) @Joanes04 
- [x] [NewApi Review: Adapt new Configuration](https://github.com/wazuh/wazuh-kibana-app/issues/2185) @Joanes04 
- [x] [NewApi Review: Adapt new status and reports](https://github.com/wazuh/wazuh-kibana-app/issues/2186) @Joanes04 
- [x] [NewApi Review: Adapt new agents](https://github.com/wazuh/wazuh-kibana-app/issues/2189) @Joanes04 
- [x] [NewApi Review: Adapt new logs](https://github.com/wazuh/wazuh-kibana-app/issues/2217) @Joanes04

**Comment by Desvelao** [comment]
**Agents section TODO**:
- [ ] `rules/mitre` need to be adapted to new API when is merged.

**Comment by jsanchez91** [comment]
All tasks have been completed, the Issue is closed
