### ISSUE TITLE
Adapt Kibana app to support the Wazuh API 4.0

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2021]
Hi team!

In this issue we'll describe the process of adaptation to the new API 4.0. For this we'll describe the **current status** of our API calls, both from the FrontEnd and the BackEnd. 
On the other hand, we'll describe where **we want to go** with the adaptation to the new API 4.0 and the **changes we need** to make in our system.

Once we have described all of the above, the following issues must be completed to finish with the adaptation to the new API 4.0

- [x] [API authentication with JWT token](https://github.com/wazuh/wazuh-kibana-app/issues/1998) @Joanes04 
- [x] [Adapt/manage API errors format](https://github.com/wazuh/wazuh-kibana-app/issues/2000) @Desvelao 
- [x] [Adapt/manage API response format](https://github.com/wazuh/wazuh-kibana-app/issues/1999) @Joanes04 
- [x] [Review all API requests (inluded dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001) @wazuh/frontend 
- [x] [Adapt Wazuh API configuration for new api](https://github.com/wazuh/wazuh-kibana-app/issues/2221) @Joanes04
