### ISSUE TITLE
NewApi Review: Management section

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2049]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

In this issue, we are going to adapt all the API endpoints in Management section to be fully compatible with the new format of Wazuh API 4.0.

- [x] Management
    - [x] Ruleset @pablotr9 
    - [x] Decoders @pablotr9 
    - [x] CDB Lists @pablotr9 
    - [x] Configuration @Joanes04 
    - [x] Groups @pablotr9 @Joanes04 
    - [x] Status @pablotr9 
    - [x] Reporting @pablotr9 @Joanes04 
    - [x] Cluster @pablotr9 
    - [x] Logs @pablotr9 

**Branches**

- [x] We need to solve TODO in order to complete the issue.

**Parent issue**

[Review all API requests (inluded dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001)

**Comment by Joanes04** [comment]
**Configuration**

We will be reviewing and updating the API calls in sections

**configuration-switch.js** 

- We have updated the response format of the endpoint: `/cluster/nodes`.

> Old format

```
this.props.updateClusterNodes(nodes.data.data.items);
```

> New format

```
this.props.updateClusterNodes(nodes.data.data.affected_items);
```

**Comment by Joanes04** [comment]
**TODO**

**Configuration**

- [ ] In **Global configuration**, we try to make the following request, and in the new API 4.0 there is no such endpoint:

```
/cluster/{node_id}/configuration/com/logging
```

**Comment by Joanes04** [comment]
**UPDATE**

- We have fixed the pagination for the new API 4.0 in the Rules table

> Old format

```
const rawItems = await this.wzReq(
      'GET',
      `${this.paths[this.props.request]}${showingFiles ? '/files' : ''}`,
      params: this.buildFilter(),
    ).catch((error) => {
      console.warn(`Error when get the items of ${section}: `, error);
      return {}
});
```

> New format

```
const rawItems = await this.wzReq(
      'GET',
      `${this.paths[this.props.request]}${showingFiles ? '/files' : ''}`,
      { params: this.buildFilter() },
    ).catch((error) => {
      console.warn(`Error when get the items of ${section}: `, error);
      return {}
});
```

**Comment by Joanes04** [comment]
**UPDATE**

We have adapted the request for `Management > groups`:

* We have changed the format for the **errorResponse**, because now in the new API 4.0, we have `affected_items` and `failed_items`. When we **add/remove** agents in a group, we have changed the toast format:

![whitfail](https://user-images.githubusercontent.com/9945959/74445161-efbae600-4e43-11ea-9153-9719dcaee044.gif)

* We have adapted the format for the api requests with parameters in the controller groups:

> Old format

```
const req = await this.apiReq.request('GET', '/agents', params);
```

> New format

```
const req = await this.apiReq.request('GET', '/agents', { params: params });
```
