### ISSUE TITLE
Adapt wazuh-monitoring cron for new jobs

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2064]
The Wazuh UI has two cron jobs:
- Check_know_fields
- Monitoring

The first job checks all fields in the Elasticsearch index-pattern and update it if discovered a new field.

The second Job, It is monitoring a request to the Wazuh API configured in the environment and save the response in the `wazuh-monitoring-3.x-*` index.

We need to replicate this behavior for other API requests and save in an index, for example: 
```
GET /manager/stats/remoted
GET /manager/stats/analysisd
```

**Comment by jsanchez91** [comment]
Related Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2020

**Comment by jsanchez91** [comment]
The code of the monitoring task is very specific to the request it makes. We'll create logic to simplify the creation of new tasks scheduled to index an API response periodically.

After analyzing the problem, we thought of two solutions:

1. Duplicate the code of the monitoring task and adapt it to other requests. The difficulty of this solution is the same for all the new scheduled tasks we want to monitor, but the problem is that it generates a lot of duplicated code and is too difficult to maintain.

2. Create a task scheduler, this solution has more cost in time and difficulty, but the result is better than the first solution.

### The task scheduler solution

To create a new task we have thought about the basic data to make the request to the API, the storage of the response in an index and the interval in which the task will be executed. The result is this interface:

```typescript
export interface job {
  status: boolean
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  request: string
  params: {}
  interval: string
  index: string
  creation: 'h' | 'd' | 'w' | 'm'
  apis?: string[]
}
```
##### Description of the fields
**status**: Status of the task
**method**: HTTP method of the request
**request**: Path of the request
**params**: Object with the parameters of the request
**interval**: The interval in which the task will be executed expressed in Cron time string format
**index**: The name of the index in which the answer is to be stored 
**creation**: The frequency of creation of a new index
**apis**: (optional) By default the task run in all APIs configured unless any is specified, in which case only will be executed in these. This is a white list.

**Comment by jsanchez91** [comment]
**Update:**

I pushed a new branch to work in this issue: [3.12-7.5#2064-cron-jobs](https://github.com/wazuh/wazuh-kibana-app/tree/3.12-7.5%232064-cron-jobs)

The first commits include a new class for making API requests and some unit tests.

The new class has 3 parameters in its constructor:
- `request`: String with the path of the request
- `api`: Object with the implementation of the `IApi` interface
- `params` (optional): An object with the request parameter, by default, is an empty object.

 ```ts
interface IApi {
  id: string
  user: string
  password: string
  url: string
  port: number
  cluster_info: {
    manager: string
    cluster: 'Disabled' | 'Enabled'
    status: 'disabled' | 'enabled'
  }
}
```

**Comment by jsanchez91** [comment]
**Update:**

We build the logic to get the IApi interfaces from the Wazuh configuration and filter these if the key `apis` is defined in the Job configuration.


We create some unit tests for these methods:
```
    ✓ should job is assigned  (5ms)
    ✓ should get API object when no specified the `apis` parameter on the job object (1ms)
    ✓ should get all API objects when no specified the `apis` parameter on the job object (1ms)
    ✓ should get one of two API object when specified the id in `apis` parameter on the job object (1ms)
    ✓ should get two of three API object when specified the id in `apis` parameter on the job object (1ms)
    ✓ should throw an exception when no get APIs (4ms)
    ✓ should throw an exception when no match API
```

**Comment by jsanchez91** [comment]
**Update**:
Finished the first iteration. 

The code has the minimum requirements to make a request to the selected APIs, create an index if it does not exist and insert the result as a document in it.

At this point, these are the requirements for building a final version:

- [ ] All indexes must be created with a configurable prefix.
- [ ] Should be created index-pattern when creating an index.
- [ ] Should be created a new index by the interval creation selected.
- [ ] All documents must have a timestamp field.
- [ ] Implement logic to throw errors when expected behaviors are detected.
- [ ] Implement logic to catch and register all exceptions.
- [ ] Improvements all interface, some class or methods get unnecessary params.
- [ ] Create methods for loading the default jobs, these could be disabled by the settings or only activated in the cluster mode.
- [ ] Jobs may be disabled or their settings changed at run time.

**Comment by jsanchez91** [comment]
**Update**:
- All documents are created with a timestamp field:
- Added a new field to the configuration to define the prefix of all the indexes created by the jobs
![image](https://user-images.githubusercontent.com/3064506/74719735-e3b09900-5234-11ea-9b97-11753fe383dc.png)

**Comment by jsanchez91** [comment]
Some API request has parameters in their path. To solve this problem we modified the IJob interface to accept two types: a string or an IRequest interface.
```ts
interface IJob {
  status: boolean
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  request: string | IRequest
  params: {}
  interval: string
  index: string
  creation: 'h' | 'd' | 'w' | 'm'
  apis?: string[]
}
```

This is the IRequest interface:
```ts
interface IRequest {
  request: string
  params: {
    [key:string]: {
      request?: string
      list?: string[]
    }
  }
}
```

This interface accepts a parameter in its path using curly braces, for example:
`/cluster/{clusterId}/stats`

The name between the curly keys is used as a key in the params property. The param property has two properties:
- Request: It's possible to get the list of the values of the parameter directly from another API request. This second request must have the items object, the item object be an Array of strings or an object with only one key.
- List: An Array of strings.

##### Example
```ts
{
  status: true,
  method: "GET",
  request: {
    request: '/cluster/{nodeName}/stats/remoted?pretty',
    params: {
      nodeName: {
        request: '/cluster/nodes?select=name'
      }
    }
  },
  params: {},
  interval: '0 0 * * * *',
  index: 'cluster-stats-remoted',
  creation: 'w',
}
```

**Comment by jsanchez91** [comment]
**Update**: 
#### Task finishes:
- [x] Should be created index-pattern when creating an index.
- [x] Should be created a new index by the interval creation selected.

**Comment by jsanchez91** [comment]
Rebase the branch `3.12-7.5#2064-cron-jobs` with branch `3.13-7.8` and complete these points:

- [x] Implement logic to throw errors when expected behaviors are detected.
- [x] Implement logic to catch and register all exceptions.
- [x] Improvements all interface, some class or methods get unnecessary params.

**Comment by jsanchez91** [comment]
**Update:**

- We have created a method to execute the tasks depending on whether Wazuh is running in cluster mode
- In the ODFE the index pattern is not created in the private tenants, we add the logic to create it if it does not exist when the user enters the WazuhUI

**Comment by jsanchez91** [comment]
The development of the cron tasks configuration view is described in this Issue:  https://github.com/wazuh/wazuh-kibana-app/issues/2386

**Comment by pablotr9** [comment]
- [ ] Move `apiName` and `nodeName` one level above from its current level in the JSON tree.

The `nodeName` and `apiName` fields are part of the `analysisd` and `remoted` fields, these two fields are not part of them so they should be at the same level (that way it is easier to filter by them)
![image](https://user-images.githubusercontent.com/35685689/88156986-78fff100-cc0a-11ea-9101-52331f5d9a9b.png)
Instead, it should be like this:
```
         "remoted" : {
          .....
          },
     >   "apiName" : "default",
     >   "nodeName" : "manager_centos"
          "cluster" : "true",
          "timestamp" : "2020-07-20T11:27:45.853Z"
        }
```

**Comment by jsanchez91** [comment]
Updated:
