### ISSUE TITLE
RBAC: New Api authentication

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2103]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6     | X |

**Description**

In this issue we are going to define the changes we have to make in the `api-interceptor.js` file of the [new-api](https://github.com/wazuh/wazuh-kibana-app/tree/new-api) branch that we made in the [API authentication with JWT token](https://github.com/wazuh/wazuh-kibana-app/issues/1998)

Now let's take into account the data of the logged-in user, to obtain a token with the permissions of that user, and to be able to show and hide functions in the Wazuh UI.

Now we have a new diagram that we will explain below

![NEW api-interceptor js (2)](https://user-images.githubusercontent.com/9945959/75479906-4fe67780-596e-11ea-97a5-83670a3fd36e.jpg)

As we can see from the diagram, the request is coming through to our interceptor. The first thing we do is check if we have a token in the **payload** of the **request**. At this point we would have two alternatives:

**We have token**

If we have the token in the **payload**, we would make the request to the Wazuh API 4.0 through the AXIOS http client. If the API response is an error 401, it means that the token we have is no longer valid, so we have to update our authentication, and we will go to the other "alternative". If the response we get from the Wazuh API is correct (status: 200) or an error with status other than 401, we will return it to the BackEnd as a Wazuh API 4.0 response.

**We haven't token**

In case we don't have a token stored, we would make a request to Wazuh API 4.0 of : /security/user/authenticate. To make this request, we need first to obtain the data of the logged user, to be able to send it in the parameter: **Authorization context**. At this point, we have three possible alternatives, which we will solve in the following issues:

- [x] [RBAC: Adapt to X-pack](https://github.com/wazuh/wazuh-kibana-app/issues/2104)
- [ ] ~[RBAC: Adapt to SearchGuard](https://github.com/wazuh/wazuh-kibana-app/issues/2105)~
- [x] [RBAC: Adapt to OpenDistro](https://github.com/wazuh/wazuh-kibana-app/issues/2106)

Once we get the data from the logged in user, we make the request to Wazuh API 4.0, and we get the response.

Once the token request to the Wazuh API 4.0, we have again two possibilities. If you return an error, we will return the error to the BackEnd informing that we cannot get the token. If we get the token, the cycle it again from the beginning, with the new token ready to use.

**WARNING**

> Now in the API request response, the data is returned, but the new token is also returned in each request, so that the FrontEnd part always has the token updated with the available permissions

**Comment by Joanes04** [comment]
**UPDATE**

We have made some changes to the **api-interceptor** function, to adapt it to the new RBAC system. The changes we have made are as follows:

- We have moved **server** and **req** to our api-interceptor:

**api-interceptor.js**

> Old format
```
constructor(server) {
    this.server = server;
    this.manageHosts = new ManageHosts();
    this.updateRegistry = new UpdateRegistry();
}
```
> Old format
```
constructor(server) {
    this.server = server;
    this.manageHosts = new ManageHosts();
    this.updateRegistry = new UpdateRegistry();
}
```

**Comment by jsanchez91** [comment]
**Update**
- New function "getCurrentPlatform" created in "WazuhApiCtrl" controller.
This function detects the active security plug-in in Kibana

https://github.com/wazuh/wazuh-kibana-app/blob/4.0-7.8.0-rbac/server/controllers/wazuh-api.js#L59-L67
```js

getCurrentPlatform(server) {
  if (server.plugins.security) {
    return 'xpack';
  }
  if (server.plugins.opendistro_security) {
    return 'opendistro';
  }
  return undefined;
}
```

- An interface has been created to implement the classes needed to obtain the data from the different security plugins:

https://github.com/wazuh/wazuh-kibana-app/blob/4.0-7.8.0-rbac/server/lib/security-factory/security-factory.ts#L11
