### ISSUE TITLE
Deangularize Wazuh UI

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2394]
Hi team,

Following Kibana's steps, we have been migrating our code from `angular.js` to `ReactJs `for some time. Most of the work is done, but we still have to undertake the final Deangularization and the cleaning of the obsolete files on repository. This issue will serve as a summary of all the processes that need to be undertaken in this last phase:

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/2383 Migrate Manage agents of group to React
- [ ] #2364 Migrate DevTools to React
- [x] https://github.com/wazuh/wazuh-kibana-app/commit/4035850050ebe6f6d102ea812a7498973f525f9d Migrate cluster nodes and remove `wz-table` & `wz-enter` directives
- [x] https://github.com/wazuh/wazuh-kibana-app/commit/6252dc187b1edb75e0999e54b16eb445007eb168 Removed other unused directives
- [x] #2395 Migrate health check to React and remove `wz-src` directive

Regards,
