### ISSUE TITLE
Migrating from legacy plugins to the new platform

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2475]
Hi team!

As Kibana is removing the functions used by the legacy plugins, we have to start migrating WazuhUI to a new platform.

This link shows the requirements and the process to do this migration:
[Migrating legacy plugins to the new platform - link](https://github.com/elastic/kibana/blob/v7.9.0/src/core/MIGRATION.md)

### Steps of migration
- [x] Define the plugin's manifest
- [x] [Server-side migration](https://github.com/wazuh/wazuh-kibana-app/issues/2591)
- [x] [Browser-side migration](https://github.com/wazuh/wazuh-kibana-app/issues/2660)

**Comment by jsanchez91** [comment]
**Update:**

Working in the branch: `feature/2475-migrating-plugin-new-platform`

> - Created plugin's manifest
> - Update the server-side instance
