### ISSUE TITLE
[4.0] Improve the toasts and expand its information

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2487]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 4001 |

**Description**
In this issue, we go to improve as the errors are shown in toasts

**TODO**
- [x] Service to launch toasts:
  - Wrap `toastNotifications` of `ui/notify`
  - Posibility of launch:
    - Simple toasts (success, warning, danger)
    - Improved toast with a button to expand the information (open a modal)
- [x] Modal component to show the expanded information about the toast
  - Callout with a message
  - Code block with more information about the error (as `error.stack`)
  - Button to copy the information like the text to reporting/debugging purposes
- [ ] Replace all instances of `toastNotifications` by the new service
