### ISSUE TITLE
Add a link to "Check Connection" in the deploy_new_agents component

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2495]
Hi team!

A new section will be created in the documentation to indicate how the connectivity between the agent and the manager is checked.
See the doc [section](https://documentation.wazuh.com/current/user-manual/agents/agent-connection.html)
It would be necessary to include a link to this new section in the `deploy_new_agent` component.

![image](https://user-images.githubusercontent.com/3064506/94283575-7a72d000-ff51-11ea-961d-973c379fb310.png)

**Task:**
- [x] Create some mockups
- [x] Implement the mockup
- [x] Add the link

**Comment by eze9252** [comment]
Hi @jsanchez91,

I have two options to resolve this issue.

1.  In the step "Install and enroll the agent" add a text in the end with the link to documentation: 

![Captura de pantalla de 2021-04-06 15-50-39](https://user-images.githubusercontent.com/36004787/113763702-5e19d200-96f0-11eb-965e-98069479c8bd.png)

2. Add a new step "Checking connection with Manager" with the link to documentation: 

![Captura de pantalla de 2021-04-06 15-16-08](https://user-images.githubusercontent.com/36004787/113763909-9faa7d00-96f0-11eb-9e5e-ce1d53542e64.png)


Tell me what you think is the best.
