### ISSUE TITLE
Check if the Wazuh-wui was updated

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2555]
Hi team!

We need to add logic to check if the plugin has been updated, if it has been updated changes need to be made on the server-side and on the browser-side.

### Server-side
Compare the version and revision stored in the file wazuh-registry.json and compare it with the one indicated in the package.json

If they do not match, the wazuh-registry.json file must be regenerated

### Browser-side
Check if there is a cookie or a variable in Localstorage with the version and revision of the plugin.

If it does not exist or the value is different from the current one, delete the data from the browser and force the browser to reload.

### TODO:
**Server-side**
- [x] Check wazuh-registry version
- [x] Remove/update wazuh-registry

**Browser-side**
- [x] Check if there is information about the version of the plugin in the browser.
- [x] Check the difference between browser information and the current version.
- [x] Remove browser data
- [ ] ~Force reload~

**Comment by jsanchez91** [comment]
The task of force-reload is impossible to implement, this will be fixed with the migration to the new platform.

On the new platform, the bundles files are inside the package and can be versioned.
