### ISSUE TITLE
[newPlatform] Server-side migration plan 

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2591]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2475 
------------ | -------------
### Description
Move server-side logic to the new platform plugin format

### Tasks
- [x] [Migration of Routers](https://github.com/wazuh/wazuh-kibana-app/issues/2592)
- [x] [Migration of Monitoring](https://github.com/wazuh/wazuh-kibana-app/issues/2703)
- [x] [Migration of initialize](https://github.com/wazuh/wazuh-kibana-app/issues/2705)
- [x] [Migration of scheduler](https://github.com/wazuh/wazuh-kibana-app/issues/2706)
- [x] [Migration of queue](https://github.com/wazuh/wazuh-kibana-app/issues/2718)

**Comment by Desvelao** [comment]
## Backend changes
### ApiInterceptor
Refactorized the `ApiInterceptor` service:
- Replaced the class with static methods by functions
- Simplify logic
- Now the token of the internal Wazuh API host user is saved in memory instead of `wazuh-registry.json` file. Created a caché for this.
- Replaced and adapted the instances of ApiInterceptor by the new functions

**Comment by Desvelao** [comment]
### Changes
- Unified to constants (`utils/contants.js`) all the instances to `optimize` directory where Wazuh data is being saved
- The Wazuh app data is now under `<KIBANA>/data` folder

**Comment by Desvelao** [comment]
### Changes - Backend cleaning

[PR](https://github.com/wazuh/wazuh-kibana-app/pull/2781):

- Removed not used files (`.old.js`)
- Renamed `.js` files to `.ts`
- Renamed `/util` to `/common`
- Moved `/server/reporting` to `/server/lib/reporting`
- Moved `/server/jobs/queue` to `/server/start/queue`
- Moved `/server/logger` to `/server/lib/logger`
- Moved files in `/util` to `/server/lib`
- Adapted imports in backend and frontend
- Created `index` files for each backend job
- Removed endpoints:
  - `/api/pci/{requirement}`
  - `/api/gdpr/{requirement}`
  - `/api/nist/{requirement}`
  - `/api/tsc/{requirement}`
  - `/api/hipaa/{requirement}`
  - `/api/monitoring`
  - `/api/agents`
  - `/elastic/index-patterns`
  - `/reports`
- Renamed endpoint `/elastic/esAlerts` to `/elastic/alerts`. Adapted frontend
- Removed files:
  - `/server/lib/elastic-wrapper.ts`
  - `/server/lib/api-helper.js`
  - `/server/lib/get-path.ts`
  - `/server/lib/reporting/tab-description`
