### ISSUE TITLE
[newPlatform] Migration of Routers

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2592]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2591 
------------ | -------------

### Description
Migrating the router files to the new plugin format.
This involves adapting the related controllers.

### Tasks
**Routers:**
- [x] [wazuh-api](https://github.com/wazuh/wazuh-kibana-app/issues/2600)
- [x] [wazuh-elastic](https://github.com/wazuh/wazuh-kibana-app/issues/2684)
- [x] [wazuh-hosts](https://github.com/wazuh/wazuh-kibana-app/issues/2685)
- [x] [wazuh-reporting](https://github.com/wazuh/wazuh-kibana-app/issues/2686)
- [x] [wazuh-utils](https://github.com/wazuh/wazuh-kibana-app/issues/2687)

Pending integration with frontend

**Comment by Desvelao** [comment]
## Endpoint context

Created a `wazuh` key with the next methods:
- `logger`: Kibana server logger
- `security`: instance to the current security platform.
- `plugins`: access to plugins
- `api`: contains a client to do request to Wazuh API. It's a wrapper of ApiInterceptor.

These are availables in the `context` param of endpoint handlers.
```context.wazuh```

### `api`
It contains a client to do requests to Wazuh API endpoints as the internal user configurated for each host in the `wazuh.yml` or use the current user.
```ts
// Internal user
context.wazuh.api.client.asInternalUser.authenticate(apiIHostID: string)
context.wazuh.api.client.asInternalUser.request(method: string, path: string, data: any, options: {apiHostID: string})

// Current user
context.wazuh.api.client.asInternalUser.authenticate(apiIHostID: string, authContext: any)
context.wazuh.api.client.asCurrentUser.request(method: string, path: string, data: any, options: {apiHostID: string})
```

**Comment by Desvelao** [comment]
### Changes
- Replaced the calls with the legacy Elasticsearch client by the provided by the new platform contained in the `context.core.elasticsearch.client`.
- Replaced calls to `.kibana` index by calls with the current user using the saved objects client `context.core.savedObjects.client`

**Comment by Desvelao** [comment]
## Changes
- Moved some `.js` backend files to `.ts`

**Comment by Desvelao** [comment]
Removed the next ot used endpoints [PR](https://github.com/wazuh/wazuh-kibana-app/pull/2781):
  - `/api/pci/{requirement}`
  - `/api/gdpr/{requirement}`
  - `/api/nist/{requirement}`
  - `/api/tsc/{requirement}`
  - `/api/hipaa/{requirement}`
  - `/api/monitoring`
  - `/api/agents`
  - `/elastic/index-patterns`
  - `/reports`
