### ISSUE TITLE
RBAC second iteration 

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2594]
### Description
We need to improve the integration of the RBAC system into the interface. In this second iteration we are going to implement:
- The complete management of the Wazuh API users.
- Error correction and improvement of the restriction of the different views and components according to the policies and roles of the user.
- Document the auth_context information of the ODFE and X-Pack 

### Tasks
- [x] [Improved the CRUD ](https://github.com/wazuh/wazuh-kibana-app/issues/2595)
- [x] [Improved view authorization](https://github.com/wazuh/wazuh-kibana-app/issues/2656)
- [ ] Research the auth_context
