### ISSUE TITLE
[RBAC] Improve the users' CRUD and user mapping

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2595]
Parent Issue | https://github.com/wazuh/wazuh-kibana-app/issues/2594
------------ | -------------

### Description
We need to replace Elastic users with Wazuh users in the section Security/Users.
The section of Security/Users will show de Wazuh API users, and from here will be able to create, edit, and delete such users.

Also, we need to change the section Security/Role Mapping to add the option to map an internal user. This section will be replaced by a new mapping where will be able to map internal users ( ODFE or X-PACK) with Wazuh API roles. 

### Task
- [x] Implement CRUD of the Wazuh-API users
- [x] Implement internal user mapping
- [x] Refactor services and classes to clean code.

**Comment by frankeros** [comment]
The Wazuh users' CRUD was implemented with the PR [#2598](https://github.com/wazuh/wazuh-kibana-app/pull/2598)

Now the section users is showing the Wazuh users instad of the internal users
![image](https://user-images.githubusercontent.com/26828184/99309122-b894bd80-2837-11eb-89d6-8aaf89c64042.png)

Now we can create a new Wazuh user from here
![image](https://user-images.githubusercontent.com/26828184/99309182-d104d800-2837-11eb-81fe-330c178c0619.png)

As we can see, the fields are validating the same as  the Wazuh API
![image](https://user-images.githubusercontent.com/26828184/99308972-808d7a80-2837-11eb-8bf8-25bc27d7ae08.png)

Also, we can edit and delete the users 
![image](https://user-images.githubusercontent.com/26828184/99309378-14f7dd00-2838-11eb-8349-f50ad2a2a200.png)
![image](https://user-images.githubusercontent.com/26828184/99309682-95b6d900-2838-11eb-9b90-5ea29344aa6a.png)

Regarding the role mapping now we can select internal users directly or/and set custome rules
![image](https://user-images.githubusercontent.com/26828184/99310421-c51a1580-2839-11eb-853f-874d5603c39c.png)
![image](https://user-images.githubusercontent.com/26828184/99310456-d105d780-2839-11eb-8f97-40e695efe4b8.png)

If we have some rule that is not compatible whit the visual editor now it's open directly with the JSON editor instead
![image](https://user-images.githubusercontent.com/26828184/99311187-f515e880-283a-11eb-9a19-8760462aeffb.png)
