### ISSUE TITLE
Integrating NIDS

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2603]
### Description
Wazuh NIDS (OwlH) components will be integrated into the plugin. In this first iteration, the integration will be done in the following sections.

### Tasks
- [ ] [Modules](https://github.com/wazuh/wazuh-kibana-app/issues/2604)
- [ ] [Management](https://github.com/wazuh/wazuh-kibana-app/issues/2605)
- [ ] [Agents](https://github.com/wazuh/wazuh-kibana-app/issues/2606)

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
