### ISSUE TITLE
[NIDS] Agents

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2606]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2603
------------------|----------------------------------------------------------------------------

### Description
Integrate Wazuh NIDS into the agents' view.

### Task
> Agents Table 
- [ ] Include NIDS column
- [ ] if client does have NIDS node installed show **NIDS** pill
- [ ] if node is online NIDS pill will be green, if node is offline red, if node is unregistered or any other issue yellow
- [ ] NIDS pill will link with Node Details panel [[NODE - DETAILS](https://github.com/owlh-net/owlh-wazuh-app/issues/16)]

> Agent detail
- [ ] Include top menu **NIDS** - will link to [[NODE - DETAILS](https://github.com/owlh-net/owlh-wazuh-app/issues/16)]
- [ ] include panel/s with monitor/status info - cpu/mem/storage - suricata - zeek - files

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
