### ISSUE TITLE
Change kibana `Time filter defaults` to last 24h 

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2611]
Hi team!

By default, the "Time filter defaults" is set to the last 15 minutes. We will add logic to change its value to the last 24 hours.

![image](https://user-images.githubusercontent.com/3064506/98804806-f13b2e00-2416-11eb-8050-6bf1a3267ecf.png)

### Tasks
- [x] Check the current value
- [x] Update the value
- [x] Create new setting to disable this check.
