### ISSUE TITLE
Inconsistent data in sample data alerts

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2614]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 4008 |

**Description**
The data entered from the alerts entered with the sample data are not consistent, the data entered must be checked to ensure that the information in the rule is real.

**Steps to reproduce**

1. Add sample data
2. See in event view

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/3064506/98833425-476f9780-243e-11eb-9714-a89452d203d8.png)

![image (3)](https://user-images.githubusercontent.com/3064506/98833396-3c1c6c00-243e-11eb-9ed6-9a41e070d1c6.png)

### Tasks

- [ ] Sample security information
- [ ] Sample auditing and policy monitoring
- [ ] Sample threat detection and response
