### ISSUE TITLE
[newPlatform] Browser-side migration plan

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2660]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2475 
------------ | -------------
Branch | [feature/2475-migrating-plugin-browser-side](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2475-migrating-plugin-browser-side)

### Description
Move browser-side logic to the new platform plugin format

### Tasks
- [ ] Migration of health check
- [ ] Migration of modules
- [ ] Migration of management
- [ ] Migration of agents
- [ ] Migration of dev_tools
- [ ] Migration of security
- [ ] Migration of settings
