### ISSUE TITLE
[newPlatform] [browserSide] Migrate Health-Check 

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2682]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2660
------------ | -------------
Branch | [feature/2475-migrating-plugin-browser-side](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2475-migrating-plugin-browser-side)

### Description
Migrate the health check component to the new platform.
Refactorizing all involved classes and modules.

### Tasks
- [x] Resolve the new plugin start and setup for public
- [x] Create a new Router 
- [x] Migrate of the component Health Check (refactor)
- [x] Migrate services
- [x] Integrate with server-side
- [x] Testing
- [x] Adapt for 4.2.0
  - [x] Integrate in branch the component
  - [x] Add check for the monitoring index pattern
  - [x] Add check for the statistics index pattern
  - [x] Add logic to retry the API connection check
  - [x] Refactor `Checking...` message in check with dependencies when these fail.
  - [x] Testing. Define the use cases.
  - [x] [Optional] Adapt the ReactJS tests

**Comment by frankeros** [comment]
**Summary**

- The plugin start and setup were refactorized to integrate and expose some kibana services

- A new router was added and a Kibana context was provided in the root app.  

- The health-check component was refactorized to clean code. 

- All involved services were migrated from statics classes and `js` files to const modules and `ts`

- The branch was merged with the server-side migration to testing

- Solving some issues with services. (in Progress)

**Comment by frankeros** [comment]
**Summary**

- Fixed render errors (Callouts)

- Fixing index pattern services

**Comment by frankeros** [comment]
**Summary**

- Migrated endpoint  `/elastic/template/{pattern}` to new Elastic client
- Fixed refreshIndexPattern
- Refactored health check to functional await for dependents checks

**Comment by frankeros** [comment]
**Summary**
- Added unit test

**Comment by Desvelao** [comment]
### Changes
- Adapted the refactored health check to  `4.2-7.10` branch
- Added check for monitoring index pattern
- Added check for statistics index pattern
- Added retry button for the API connection check

**Comment by Desvelao** [comment]
Work branch: refactor/healthcheck-4.2-7.10

### Changes
- Replaced the initial status check message from `Checking...` to `Waiting...` to no confuse to the user with checks that aren't started.
- Fixed problem with toasts in the menu which broke the toast system.

### Bugs
- [ ] Change the `pattern` setting in `Settings > Configuration` and `Execute the health check` doesn't create the new index pattern if it doesn't exist

**Comment by Desvelao** [comment]
Work branch: `refactor/healthcheck-4.2-7.10`

### Changes
- Fixed problem when change the index pattern from `Settings > Configuration`.
- Fixed 2 infinite loops: one with URL redirection and another with set state of the component.
- Updated the previous components tests.
