### ISSUE TITLE
[newPlatform] [browserSide] Migrate Overview component and styles

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2683]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2660
------------ | -------------
Branch | [feature/2475-migrating-plugin-browser-side](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2475-migrating-plugin-browser-side)

### Description
Create the `main overview component` this involves the migration of `stats overview` and `extensions overview`
Migrate all `less` and `css` files to `scss`.

### Tasks
- [x] Migrate all `less` and `css` files to `scss`.
- [x] Create new main overview as container
- [x] Migrate stats overview and extensions overview
- [ ] Migrate services
- [ ] Integrate with server-side
- [ ] Testing

**Comment by frankeros** [comment]
**Summary**

- The styles were migrated to scss.

- The main overview component was added.

- The stats overview and extensions overview were migrated

- Migrating services. (in progress)

**Comment by frankeros** [comment]
**Summary**

- Fixed render errors (Callouts)

- Refactored Cookies usage in AppState

- Migrated countApi resolver to fix no default API in cookies

**Comment by frankeros** [comment]
**Summary**
- Added unit test
