### ISSUE TITLE
[newPlatform] [browserSide] Migrate Management

### ISSUE THREAD

**Issue by gabiwassan** [wazuh/wazuh-kibana-app#2690]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2660
------------ | -------------
Branch | [feature/2475-migrating-plugin-browser-side](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2475-migrating-plugin-browser-side)

### Description
Migrate the health check component to the new platform.
Refactorizing all involved classes and modules.

### Tasks
- [x] Resolve the new plugin start and setup for public
- [x] Create a new Router 
- [x] Migrate of the component Health Check (refactor)
- [x] Migrate services
- [x] Integrate with server-side
- [ ] Testing

**Comment by gabiwassan** [comment]
The main view was migrated and now we use react components and functional components.
Added navigation to `Management/Rules`
Problems with the controller of management (this controller is made for angularjs and it is only one for all subviews)

**Comment by gabiwassan** [comment]
Added navigation to Management/Decoders, testing on the process.

**Comment by gabiwassan** [comment]
** Summary **
This issue is paused in order to improve a prev migration to the new platform keeping angular as the main app tech
