### ISSUE TITLE
[newPlatform] Migration of Monitoring

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2703]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2591 
------------ | -------------

### Description
Migrate the monitoring job to the new platform.

### Tasks
- [x] Create a function to attach to `start` plugin method
- [x] Replace the Elasticsearch client
- [x] Replace the Wazuh API calls with the new ApiInterceptor methods

**Comment by Desvelao** [comment]
## Changes
- Refactorized from class to functions. Now export the main function to do the job.
- Replaced Elasticsearch request using the `ElasticWrapper` for the new Elasticsearch client provided by the new Kibana platform
- Replaced `ApiInterceptor` requests with the new methods.
- Created a context that is passed to the monitoring job. Includes the Elasticsearch client, API client and the Kibana logger customized for `monitoring`.
- Renamed some methods.
- Convert some files to `.ts` to support Typescript.
- Removed the logic to update the monitoring known fields.
