### ISSUE TITLE
[newPlatform] Migration of initialize

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2705]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2591 
------------ | -------------

### Description
Migrate the app initialize process to the new platform.

### Tasks
- [x] Create a function to attach to `start` plugin method
- [x] Adapt to typescript
- [x] Refactor the logic

**Comment by Desvelao** [comment]
### Changes
- Replaced the Elasticsearch requests to use the new client
- Replaced server logger
- Refactor some logic
