### ISSUE TITLE
[newPlatform] Migration of scheduler

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2706]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2591 
------------ | -------------

### Description
Migrate the scheduler process to the new platform.

### Tasks
- [x] Create a function to attach to `start` plugin method
- [x] Adapt the Elasticsearch requests
- [x] Adapt the Wazuh API resquests

**Comment by Desvelao** [comment]
### Changes
- Removed the ApiRequest service.
- Replaced the ApiInterceptor requests by a wrapper using the context and adapted responses.
- Replaced the Elasticsearch requests with the new client.
- Adapted the Cron-scheduler ErrorHandler method.
- Replaced the class Scheduler with a function to do the job.
- Created a context for the job with methods with the new Elasticsearch and Wazuh API client, and server logger customized.
