### ISSUE TITLE
Migrate plugin to new platform keeping Angular

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2707]
Derived from issue | https://github.com/wazuh/wazuh-kibana-app/issues/2660
------------ | -------------
Branch | [POC/migrating-with-angular](https://github.com/wazuh/wazuh-kibana-app/tree/POC/migrating-with-angular)

### Description
Migrate plugin front side to new platform keeping Angular as the main app tech.

### Tasks
- [x] Perform the Angular app on new platform 
- [x] Migrate legacy dependencies
- [x] Migrate external dependencies
- [x] Integrate with server-side
- [x] Perform root template
- [x] Perform Health Check
- [x] Perform components 
- [x] Perform Discover
- [x] Perform Visualizations

**Comment by frankeros** [comment]
** Summary ** 
- In order to keep Angular, we perform the plugin as Kibana did with their plugin Discover
- Migrated all legacy and external dependencies, except discover
- Integrated with the last changes of 4.0-7.9 and last changes of the server-side migration
- Fixed Health check

**Comment by gabiwassan** [comment]
- Fixed the main menu of Wazuh.
- Fixed body validation in `/api/request` backend

**Comment by frankeros** [comment]
**Summary**

- Fixed missing injector from Angular 
- Fixed codemirror dependency for dev tools
- Started to migrate discover as local module/component

**Comment by gabiwassan** [comment]
- Fixed styles on menu wazuh.
- Started to merge with the migration of backend, fixed some conflicts, and started tests.

**Comment by frankeros** [comment]
**Summary**
- Copied local files for discover component
- Resolved dependencies into new files
- Fixing Angular problems with discover

**Comment by gabiwassan** [comment]
- Integrated migration of backend with POC angular frontend. [PR](https://github.com/wazuh/wazuh-kibana-app/pull/2716)
- Fixing problems with render of components.

**Comment by frankeros** [comment]
- Solved problems with angular scope for discover
- Trying to solve problems with Cookies
- Solving problems with visualizations

![image](https://user-images.githubusercontent.com/26828184/103315337-08a09b80-4a04-11eb-925b-30b9c8eeb374.png)
![image](https://user-images.githubusercontent.com/26828184/103315352-13f3c700-4a04-11eb-8a6d-606e9c0e683a.png)

**Comment by gabiwassan** [comment]
- Fixed some problems to load Agents view.
- d3 library changed some methods on the last [release](https://github.com/d3/d3/blob/master/CHANGES.md#shapes-d3-shape) and now we have updated our implementation for `pie` and `arch`.

**Comment by frankeros** [comment]
- Fixed visualizations (dashboards)
- Using the new template for discover
- Solving controller scope issues
- Solving sidebar issues

**Comment by frankeros** [comment]
- Solved controller issues of discover
- Solved sidebar issues
- Fixed  refresh fields index patterns from pattern handler
