### ISSUE TITLE
[newPlatform] Migration of queue

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2718]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2591 
------------ | -------------

### Description
Migrate the queue process to the new platform.

### Tasks
- [x] Create a function to attach to `start` plugin method
- [x] Refactor class with static methods to functions
- [x] Adapt instances of Queue in backend to the new exports
- [x] Move cron frequency to `contants` file
- [x] Testing

**Comment by Desvelao** [comment]
## Changes
- Refactorized class with static methods to functions.
- Renamed exported functions.
- Refactorized as the queue jobs are run.
- Moved the cron frequency constant to `util/constants` file.
- Refactorized in `wazuh-api.ts` the use to add a job to the queue.

## Test suite
Created a test suite with the next tests:
  - Check the job is added to the queue.
  - Check the job is removed from the queue after execution.
