### ISSUE TITLE
Bugfixing for 7.10.0

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2727]
### Bugfixing for 7.10.0
Branch
|--|
[4.0-7.10](https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.10)

We need to work in the app recently adapted to the new platform keeping Angular, in order to fix behaviors and styles issues.

#### Tasks
- [x] Merge last changes of 4.0-7.9
- [x] [Solve issues with cookies](https://github.com/wazuh/wazuh-kibana-app/issues/2733)
- [x] [Solve issues with reporting](https://github.com/wazuh/wazuh-kibana-app/issues/2728)
- [x] [Prune Kibana discover integration (remove unnecessary files)](https://github.com/wazuh/wazuh-kibana-app/issues/2744)
- [x] [Bughunt in Health Check ](https://github.com/wazuh/wazuh-kibana-app/issues/2738)
- [x] [Bughunt in Modules](https://github.com/wazuh/wazuh-kibana-app/issues/2739)
- [x] [Bughunt in Management](https://github.com/wazuh/wazuh-kibana-app/issues/2750)
- [x] [Bughunt in Agents](https://github.com/wazuh/wazuh-kibana-app/issues/2729)
- [x] [Bughunt in Dev Tools](https://github.com/wazuh/wazuh-kibana-app/issues/2742)
- [x] [Bughunt in Security](https://github.com/wazuh/wazuh-kibana-app/issues/2731)
- [x] [Bughunt in Settings](https://github.com/wazuh/wazuh-kibana-app/issues/2735)
- [x] [Bughunt in Menu](https://github.com/wazuh/wazuh-kibana-app/issues/2755)
- [x] [Bughunt with Open Distro 1.12](https://github.com/wazuh/wazuh-kibana-app/issues/2753)
- [x] Bughunt with X-Pack
- [x] [Check styles in dark mode](https://github.com/wazuh/wazuh-kibana-app/issues/2757)
- [x] Create `wazuh-monitoring-*` and `wazuh-statistics-*` index patterns in the frontend
- [ ] Fix errors found
- [x] Prepare build with 7.10.0 to prod
- [x] Prepare build without security 7.10.0 to prod

**Comment by Desvelao** [comment]
## Errors found
- [] No visualizations in Management/Statistics
![image](https://user-images.githubusercontent.com/34042064/104036505-c598b200-51d3-11eb-8c2e-248b3eec559d.png)

**Comment by Desvelao** [comment]
## Create `wazuh-monitoring-*` and `wazuh-statistics-*` index patterns
It is necessary to create these index patterns. Before the migration, these were created in the backend. Now, it should do in the frontend using the client of saved objects, the same as `wazuh-alerts-*` index pattern. This could do in the health check.

**Comment by frankeros** [comment]
Founded this error on build 
![image](https://user-images.githubusercontent.com/26828184/104655010-cf228e00-569b-11eb-986d-0de177b3d45d.png)
Fixed in https://github.com/wazuh/wazuh-kibana-app/commit/5a7e9c0232d6d28b5b60d48cbee7255cf29b5f4b

**Comment by frankeros** [comment]
>  Prepare build with 7.10.0 to prod

- Created `.kibana-plugin-helpers.json`
- Removed old `index.js`
- Added dependencies for prod `"axios": "^0.21.1"` and `"pdfmake": "0.1.65"`
- Removed `preinstall` and `prebuild` scripts from package.json

**Comment by frankeros** [comment]
>  Prepare build with 7.10.0 to prod
- Apparently, the directory `/usr/share/kibana/data` is not creating by default in a clean installation of Kibana. So we can't create the `wazuh` directory.

```bash
Detected an unhandled Promise rejection.
2001 - ENOENT: no such file or directory, mkdir '/usr/share/kibana/data/wazuh'
```

**Comment by frankeros** [comment]
When an agent has no alerts yet, it should show an empty state instead of a blanck space
![image](https://user-images.githubusercontent.com/26828184/104959231-870fae00-59b0-11eb-82ef-4ee5c7c8f5c2.png)

**Comment by frankeros** [comment]
- Added `postbuild` script to include assets
- Fixed reporting in Kibana Prod, moved fonts to assets

**Comment by gabiwassan** [comment]
- Preparing environment 7.10.0 without a security plugin for exploratory testing.

**Comment by frankeros** [comment]
- Trying to fix vis on prod, the problem is the class vis imported from the visualizations plugin. This class uses static services from its own plugin, in dev, these services are loaded from the beginning but in prod are empties.

**Comment by gabiwassan** [comment]
- Tested and checked the build on the prod environment of 7.10.0 without a security plugin.

**Comment by frankeros** [comment]
>     * Trying to fix vis on prod, the problem is the class vis imported from the visualizations plugin. This class uses static services from its own plugin, in dev, these services are loaded from the beginning but in prod are empties.

- Fixed with little refactor using functions provided by the plugin visualizations 
- Tested core functionalities, everything looks fine.

**Comment by frankeros** [comment]
Fixed all issues of this EPIC
