### ISSUE TITLE
[newPlatform] [browserSide] [Migration with AngularJS] Adapt reporting to the new backend endpoints

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2728]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2727
------------ | -------------
Branch | [4.0-7.10-adapt-reports-new-endpoints](https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.10-adapt-reports-new-endpoints)

### Description
The frontend needs to be adapted to the new backend endpoints to create reports.

## Endpoints
The `POST /reports` endpoints has been split into 4, one for each type of report:
- `POST /reports/modules/{moduleID}`: Create reports for the modules
- `POST /reports/groups/{groupID}`: Create reports for the groups
- `POST /reports/agents/{agentID}`: Create reports for the agents
- `POST /reports/agents/{agentID}/inventory`: Create reports for the agent inventory
Issue: #2686

### Tasks
- [x] Adapt the requests to create reports to new backend endpoints
- [x] Testing each type of reports is generated with the correct information

**Comment by Desvelao** [comment]
## Testing `POST /reports/modules/{moduleID}`
### Security information management
- [ ] Security Events
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] Integrity monitoring
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] Amazon AWS
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] Google Cloud Platform
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
 
 ## Auditing and Policy Monitoring
 - [ ] Policy monitoring
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] System Auditing
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] OpenSCAP
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] CIS-CAT
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter

## Threat detection and response
- [ ] Vulnerabilities
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] VirusTotal
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
 - [ ] Osquery
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] Docker Listener
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] MITRE ATT&CK
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter

## Regulatory Compliance
- [ ] PCI DSS
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] GDPR
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] HIPAA
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] NIST 800-53
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
- [ ] TSC
  - [ ] No agent selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter
  - [ ] Agent pinned/selected
    - [ ] Without filters
    - [ ] With filters
      - [ ] Searchbar filter
      - [ ] Filter
      - [ ] searchbar filter and filter

**Comment by Desvelao** [comment]
## Testing `POST /reports/groups/{groupID}`
(To be defined)

**Comment by Desvelao** [comment]
## Testing `POST /reports/agents/{agentID}`
(To be defined)

**Comment by Desvelao** [comment]
## Testing `POST /reports/agents/{agentID}/inventory`
(To be defined)

**Comment by Desvelao** [comment]
### Changes
- The `ReportingService` is now used in the ReactJS components instead of coming through AngularJS properties.
- Adapted the reports to the different endpoints:
  - Removed some unused  `body` properties of frontend requests.
