### ISSUE TITLE
Bughunt in Security

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-kibana-app#2731]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2727
------------ | -------------
Branch | [feature/2731_4.0-7.10](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2731_4.0-7.10)

### Description
In order to fix behaviors and style issues.

#### Tasks
- [x] Create, update and delete Users
- [x] Create, update and delete Roles
- [x] Create, update and delete Policies
- [x] Create, update and delete Role Mapping

**Comment by sortizowlh** [comment]
Error on security request: _Invalid header_.

**Comment by sortizowlh** [comment]
Solved errors with this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/2749)
