### ISSUE TITLE
[4.0-7.10] Bughunt in Dev-Tools

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#2742]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2727
------------ | -------------
Branch | [4.0-7.10](https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.10)

### Description
In order to fix errors.

#### Tasks
- [x] Bottom: "Export as Json"
- [x] Bottom: "?"
- [x] Get querys
- [x] The searches you do remain when you restart or switch windows
- [x] Run the generate-api-info script

**Comment by CPAlejandro** [comment]
Fixing right side bug in Dev-Tools
![image.png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/b60fb906-de55-4751-a723-81c5e4dc5939)
