### ISSUE TITLE
Various failures when working with unsupported agents

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2836]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.3   | 7.9.1     | 4013 |
| 4.0.4   | 7.10.0     | 4016 |

**Description**
If an agent that is not officially supported, but compiled from sources, is pinned the app will fail in various places including:

- Clicking on the Wazuh drop-down menu (makes the top bar disappear)
- Clicking on More in the agent's summary page (makes the content blank)
- Selecting Inventory data provides an almost blank page (but generating a report does provide information) 

**Steps to reproduce**

**Menu disappearance** 
1. Register and connect an OpenBSD agent
2. Select the Security Configuration Assessment dashboard (easy way to pin an agent)
3. Select the OpenBSD
4. Click on the Wazuh drop-down menu and it disappears

![openBSD-menu-disappearance](https://user-images.githubusercontent.com/36071202/105752800-091b4c00-5f48-11eb-99e8-975b3690d42c.gif)
Console output can be found here: 
[openBSD-menu-disappearance.log](https://github.com/wazuh/wazuh-kibana-app/files/5869006/openBSD-menu-disappearance.log)

**Agent summary page disappearance**
1. Select the openBSD agent from the Agents section
2. Select `More` menu (that would give quick access to the various dashboards) and see the page go blank
![openBSD-modules-directory](https://user-images.githubusercontent.com/36071202/105753133-82b33a00-5f48-11eb-8abc-b9ca94b6c8b4.gif)
Corresponding console logs are here: 
[openBSD-Modules-Load.log](https://github.com/wazuh/wazuh-kibana-app/files/5869062/openBSD-Modules-Load.log)
And they show: `Uncaught TypeError: UnsupportedComponents[platform] is undefined`

**Blank inventory data page**
1. Select the openBSD agent from the Agents section
2. Select Inventory data (view almost blank page)
![image](https://user-images.githubusercontent.com/36071202/105753392-ea698500-5f48-11eb-9946-68fa877e213c.png)

3. Select Generate report to see some data is available.
![image](https://user-images.githubusercontent.com/36071202/105753480-0e2ccb00-5f49-11eb-9eed-621c27ac11f4.png)

**Additional context**
Although this operating system is not officially supported, the user interface should be able to handle errors gracefully and indicate the limitations.

**Comment by Desvelao** [comment]
I checked with an OpenBSD VM and this problem is happening.

The problem is caused due to other OS types differents of Linux (includes `Linux` in his `os.uname`, Darwin, Windows or SunOs are not managed correctly.

**Comment by Desvelao** [comment]
# Changes
- Moved OS types to constants
- Restructuring the logic to show the available modules for the selected agent in the main menu

**Comment by Desvelao** [comment]
# Changes
- Fixed main menu
- Fixed `More` menu in the agent view
- Added a prompt to Modules to show when the module is not supported by the selected agent

**Comment by Desvelao** [comment]
# TODO
- [x] Fix main menu
- [x] Fix `More` menu in the agent view
- [x] Added a prompt to the de module view to show when the module is not supported by the selected agent

**Comment by Desvelao** [comment]
I checked the `Inventory data` view for the agent, and some information is displayed
![image](https://user-images.githubusercontent.com/34042064/107654635-2019a800-6c83-11eb-9477-6e5bce78c7c6.png)
