### ISSUE TITLE
Migrate /manager/files and /cluster/{node_id}/files API endpoints

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2844]
Wazuh
|---|
4.1.1

Hi team.
We need to migrate this API endpoints `/manager/files` and `/cluster/{node_id}/files`  corresponding to this [#wazuh/7148](https://github.com/wazuh/wazuh/issues/7148)

- [x] Migrate configuration files endpoints to `/manager/configuration` and `/cluster/{node_id}/configuration` and RBAC https://github.com/wazuh/wazuh/issues/7181)
- [x] Migrate decoder files endpoints to `/decoders/files` and RBAC https://github.com/wazuh/wazuh/issues/7179
- [x] Migrate rule files endpoints to `/rules/files` and RBAC https://github.com/wazuh/wazuh/issues/7178
- [x] Migrate list files endpoints to `/lists/files` and RBAC https://github.com/wazuh/wazuh/issues/7180

**Comment by frankeros** [comment]
- Migrated configuration endpoints, it remains to finish RBAC rules
- Refactored ruleset-handler as a factory for `decoders`, `rules`, and `lists` resources
- Migrated ruleset-editor

**Comment by frankeros** [comment]
- Migrated Rules Decoders and Lists services usages
- Migrated RBAC for all resources
- Remains to test with 4.1.1 API integrated
