### ISSUE TITLE
MITRE Framework section redesign

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3202]
Hello team,

With the new endpoints of MITRE performed in [#wazuh/wazuh/7819](https://github.com/wazuh/wazuh/issues/7819), we are able to incorporate the new MITRE documentation in the section of the App.
Also, we need to perform these changes with a new design for the section, due to a lot of the information provided. We need to improve the UX ensuring the easy and intuitive reading and searching of the whole info

At the end of this EPIC, these tasks should be done:

- [x] [Research and propose the new design of the MITRE section.](https://github.com/wazuh/wazuh-kibana-app/issues/3214)
- [x] [List and search Tactics and their related techniques.](https://github.com/wazuh/wazuh-kibana-app/issues/3291)
- [x] [List and search Techniques and their related tactics, groups, software and mitigations.](https://github.com/wazuh/wazuh-kibana-app/issues/3291)
- [x] [List and search Mitigations and their related techniques.](https://github.com/wazuh/wazuh-kibana-app/issues/3291)
- [x] [List and search Groups and their related techniques.](https://github.com/wazuh/wazuh-kibana-app/issues/3291)
- [x] [List and search Software and its related techniques.](https://github.com/wazuh/wazuh-kibana-app/issues/3291)
- [x] [Display the resource detail information.](https://github.com/wazuh/wazuh-kibana-app/issues/3293)

Also, we need to migrate the current source of techniques and tactics from the Framework section
- [x] [Migrate source of the Techniques and Tactics of Framework](https://github.com/wazuh/wazuh-kibana-app/issues/3290)

**ETA:** 21/06/11
