### ISSUE TITLE
Testing Wazuh 4.2.0 revision 4202 

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3212]
We need to perform testing of the changes introduced in the code revision `4202` in production mode.
Also, we need to perform a regression test with these changes over our general checks.

**Checks for 4202:**
- [x] Wazuh help links in the Kibana help menu [#3170](https://github.com/wazuh/wazuh-kibana-app/pull/3170)
- [x] Changed default `wazuh.monitoring.creation` app setting from `d` to `w` [#3174](https://github.com/wazuh/wazuh-kibana-app/pull/3174)
- [x] Changed default `wazuh.monitoring.shards` app setting from `2` to `1` [#3174](https://github.com/wazuh/wazuh-kibana-app/pull/3174)
- [x] Redirect to group details using the `group` query param in the URL [#3184](https://github.com/wazuh/wazuh-kibana-app/pull/3184)
- [x] Removed module titles [#3160](https://github.com/wazuh/wazuh-kibana-app/pull/3160)
- [x] Removed Sha1 field from registry key detail [#3189](https://github.com/wazuh/wazuh-kibana-app/pull/3189)
- [x] Fixed screen flickers in Cluster visualization [#3159](https://github.com/wazuh/wazuh-kibana-app/pull/3159)
- [x] Fix the broken links when using `server.basePath` Kibana setting [#3161](https://github.com/wazuh/wazuh-kibana-app/pull/3161)
- [x] Fixing filter in reports [#3173](https://github.com/wazuh/wazuh-kibana-app/pull/3173)

**General checks:** 

- [x] Firefox - ODFE 1.13.1
- [x] Chrome - ODFE 1.13.1
- [x] Safari - ODFE 1.13.1
- [x] Firefox - Basic 7.11.2
- [x] Chrome - X-Pack 7.11.2
- [x] Safari - X-Pack 7.11.2

**Comment by Desvelao** [comment]
Should we remove the double toolip?
Related to: Removed module titles #3160
![image](https://user-images.githubusercontent.com/34042064/116997881-afac8100-acdd-11eb-9eac-4e313f579a81.png)
