### ISSUE TITLE
Automation Tier 1 - Architecture with Cypress and test cases as templates

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3259]
| Version |
| --- | 
| 4.2.x |

As a wazuh kibana app developer
I want to write automated tests
In order to validate the health of the system

We need to create an automation test for all basic functionalities of our App.
We'll implement the cases prioritizing the severity of each functionality.

As a first iteration of the automation repository, we'll be creating a test suite, covering the test cases we have covered in our general checks. our sanity suite. Later on, we will be adding more in-depth tests to validate some edge cases.

At the end of this EPIC all this test should be completed:

- [x] Define architecture for Cypress repository
- [x] POC testing with Decoders and Rules 
- [x] Implement login steps functions for common test cases 
- [x] Implement selectors for the menu as template mode
- [x] Implement selector for settings as template mode
- [x] Investigate CI git Cypress and Github
- [x] Implement CI for PR

**ETA:** 21/06/11
