### ISSUE TITLE
Implement a client-side logging

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3262]
| Parent Issue |
|:---:|
| #3271 |

**Description**
In order to handle JS exceptions from components, we need to implement client-side logging using React error boundaries with a service to send the errors to the backend to store them.
 
 Tasks:
 - [x] Define log level strategy (logging and UI representation).
 - [x] Create a backend service to store (evaluate alternatives) all frontend logs from a new endpoint. [#3312 ](https://github.com/wazuh/wazuh-kibana-app/issues/3312)
 - [x] Create an [error boundary](https://reactjs.org/docs/error-boundaries.html) component as a HOC. #3313
 - [x] Create a new logging service with different log levels and send logs to the new endpoint.
 - [x] Create a new error handler to be responsible for the error orchestration (business rules for errors). #3316 
   
 **Acceptance criteria**
 - Not all errors should be sent to the backend, only logs categorized with a certain level or higher. 
 - The errors displayed in the UI must be clear to the user and not prevent the use of the app. 
 - The component must display only NO business errors, the business errors must be handled by the corresponding component.
  - The error orchestrator must be responsible for manage what to do with the errors according to the error level and interfaces.
 
 **Alternatives**
 Check the libs [loglevel](https://github.com/pimterry/loglevel) and [loglevel-plugin-remote](https://github.com/kutuluk/loglevel-plugin-remote).
 [Here](https://www.loggly.com/blog/best-practices-for-client-side-logging-and-error-handling-in-react/) an example with error boundary and `loglevel`.

**Comment by frankeros** [comment]
#### Define log level strategy (logging and UI representation).

Levels: 
--- 2 tier ---
- Verbose
- Debug
- Info
- Warning
--- 1 tier --- 
- Error
  - UI: A React components crashs but, the app continues working
  - Bussines: It's an expected and handled error but is necessary to display or log for the user. Display and log should be optional.
  - Critical: The app doesn't work
