### ISSUE TITLE
Implement try-catch strategy on all front services

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3265]
| Parent Issue | Blocked by | 
|:---:|:---:|
|#3271| #3262 |

**Description**
In order to improve better error handling in the front-end, we should implement a better try-catch strategy in all services and functions. 

**Acceptance Criteria**
- An error must be handled for every business function, and log it then throw it again until the top component or class.
- Each function could add to the original error some metadata (id, origin, etc) but not remove properties or replace values.
- An NO business error only must be displayed or not by the new component of #3262.
- All business errors should be displayed by the component by self.
- If the service or function is no used remove it.

**Tasks:**
- [x] Define try-catch strategy and interfaces (docu) #3385 
- [x] Refactor try-catch in Settings section. #3392
- [x] Refactor try-catch in Security section. #3394 
- [x] Refactor try-catch in ManagementController. #3396  
- [x] Refactor try-catch in Overview. #3407 
- [x] Refactor try-catch in Agents. #3398 
- [x] Refactor try-catch in Agent/FIM/SCA. #3416  
- [x] Refactor try-catch in Agent > Syscollector. #3431
- [x] Refactor try-catch in Agent > Controller/Settings. #3467 
- [x] Refactor try-catch in Components/wz-files. #3447   
- [x] Refactor try catch in Components/Overview #3441 
- [x] Refactor try-catch in Components/add-moludes-data #3471
- [x] Refactor try-catch in Management > Groups. #3411   
- [x] Refactor try catch in Management > Ruleset #3409 
- [x] Refactor try catch in Management > Reporting #3426 
- [x] Refactor try catch in Management > Status #3433
- [x] Refactor try catch in Management > Statistics #3428
- [x] Refactor try catch in Management > Configuration #3450 
- [x] Refactor try-catch in Public > Controller, Directives and Factories. #3473
- [x] Refactor try catch in common/modules and management/groups #3464
- [x] Refactor try catch in React services #3435 
- [x] Refactor try catch in Public/Services #3477
- [x] Refactor try-catch in react-services and theirs clients:
- [x] Refactor try-catch in  angular services and theirs clients: 
- [x] Refactor try-catch in utils and theirs clients:

**Comment by Machi3mfl** [comment]
### USES CASES OF `try-catch` in code

### 001. empty
    catch (error) { }
### 002. showToast1
    this.showToast('danger', 'Error', error.message || error);
### 003. showToast2
     } catch (error) {
        this.showToast('danger', error, 3000);
     }
### 004. return false
    } catch (error) {
        return false;
    }
### 005. setState1
    } catch (err) {
        this.setState({
        error: `Data could not be fetched for ${this.props.fileName}`,
        currentFile: { file: this.props.fileName },
        });
    }
### 006. setState2
    } catch (error) {
      this.setState({error, isLoading: false})
    }
### 007. setError
    } catch (error) {
      setError(error);
    }
### 008. getToasts().add
    catch (err) {
        // We can't ensure the suggestions contains valid characters
        getToasts().add({
          color: 'danger',
          title: 'Error',
          text: 'The filter contains invalid characters',
          toastLifeTimeMs: 10000,
        });
### 009. Empty
    }catch(error){

    }
### 010. setError SetLoading
    } catch (error) {
      setError(error);
      setLoading(false);
    }
### 011. this.errorToast(err)
    } catch (err) {
        this.setState({ isRefreshing: false });
        this.errorToast(err);
    }
### 012. 
    } catch (e) {
        this.setState({ loadingReport: false });
    }
### 013. console.log
    } catch (err) {
      console.log(err);
    }
### 014. onError(error)
    }catch(error){
      onError && onError(error);
    }
### 015. Promise.reject
    } catch (error) {
      return Promise.reject(error);
    }
### 014. this.handleError(error)
    } catch (error) {
      this.handleError(error);
    }
### 015. this.state.errors
    } catch (error) {
        this.state.errors.push(`Error trying to create ${pattern} index pattern: ${error.message}`);
    }
### 016.  return { error }
    } catch (err) {
        return {
            error: `Could not connect to API with id: ${hosts[i].id}: ${err.message || err}`,
        };
    }
### 017.  ErrorHandler.handle
    } catch (error) {
      ErrorHandler.handle(error, 'Error loading agents');
    }
### 018. getToasts().addDanger()
    } catch (error) { 
        getToasts().addDanger({title: 'An error occurred while trying to get the most active agent', text: error.message || error });
    }
### 019. this.apiOutputBox
    } catch (error) {
        return this.apiOutputBox.setValue(
          'Wazuh API is not reachable. Reason: timeout.'
        );
    }
### 020. console.warn
    } catch (error) {
      console.warn(`Error when try to get cluster status`, error);
    }
### 021. throw
    } catch (error) {
      throw new Error(error);
    }
### 022. this.props.updateError
    } catch (error) {
      this.props.updateError(error);
    }
### 023. getToasts().error
    } catch (error) {
      getToasts().error('management:status:overview.fetchData', error);
    }
