### ISSUE TITLE
Migration to React 

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3276]
#### Migration to React

**Description**
The app keeps using a lot of Angular components. We need to migrate to React, using the correct architecture to ensure the robustness of the product. 

**Propose**
We need to migrate all components keeping in mind these principles:
- Use sandbox pattern
- Unit test
- Refactor static services
- Apply SOLID for TS
- Apply Lint/Prettier
- Clean deprecated files

The principal components we should migrate are:
- **Angular router** => React-router (blocked by Kibana Discover)
- **Agents**:
    - Controller => React main container
    - Refactor to the new architecture
- **Modules**:
   - Controller => React main container 
   - Refactor to the new architecture 
- **Kibana Vis copy** => Consume Visualization plugin 
- **Kibana Discover copy** => POC Angular component => Consume Discover plugin (blocked by fork and Angular dependency)
- **Management:**
  - Controller => React main container 
  - Refactor to the new architecture 
- **Settings:**
  - Controller => React main container 
  - Refactor to new architecture
- **Security:**
  - Controller => React main container
  - Refactor to new architecture
- **Api console (dev tools):**
  - Controller => React main container
  - Refactor to the new architecture

**Tasks:**
- [ ] [POC] Investigate to get kibana-discover (Angular) as a React component.
    - [ ] Implement resolver (event handler) with kibana-discover rootScope and redux.
- [ ] Migrate all enhance values for kibana-discover into the kibana-integration/discover
- [ ] Migrate all app routes to react-router
  - [ ] Recover what has already been done for React main component 
  - [ ] Recover what has already been done for react-router and apply last routes changes
  - [ ] Migrate all Angular resolvers to redux states or services
- [ ] Migrate all static services to react context providers or get-set service patterns as a new copy (recover what has already been done).
- [ ] Migrate Angular components, for each section:
   - [ ] Recover what has already been done.
   - [ ] Move controller to a new main container.
   - [ ] Move all scope variables to Redux.
   - [ ] Implement new services.
   - [ ] Refactor children component in new architecture.
- [ ] Migrate kibana-vis to consume kibana visualization plugin.

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
