### ISSUE TITLE
Clean code backend

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3277]
#### Clean code backend

**Description**
The app backend has a lot of bad practices on architecture and code patterns. To make it scalable and robust we need to refactorize this.

**Propose**
We need to refactor all classes keeping in mind these principles:
- Use API Rest pattern (routes, middlewares, controllers, mappers, services)
- Unit test
- Apply SOLID for TS
- Apply Lint/Prettier
- Clean deprecated files

The principal components we should migrate are:
- **Routers:** 
  - Refactor to more atomic classes.
  - Normalize middlewares.
- **Controllers:**
  - Refactor into more atomic classes (one by endpoint).
  - Move logic and resolvers to business classes.
  - Normalize responses.
- **Cron jobs:**
  - Refactor into more atomic classes.
  - Performance optimization.
- **Libs:**
  - Refactor into more atomic classes.

**Tasks:**
- [ ] Separate routes classes into atomic classes by business domain.
- [ ] Implement middlewares for common resources.
- [ ] Separate controller classes into atomic classes by endpoints.
- [ ] Move controller logic into common (atomic) classes by business domain.
- [ ] Implement response mappers (separate from the controller the presentation layer).
- [ ] Separate Cron jobs into more atomic classes.
- [ ] Separate libs into more atomic classes by business domain.
