### ISSUE TITLE
Separate controller classes into atomic classes by endpoints.

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3282]
| Parent Issue | Blocked by |
|:---:| :---: | 
| #3277 | #3283 |

**Description**
In order to improve the quality of the server-side, we need to re-organize the current controllers into one-responsibility controllers. 

**Acceptance Criteria**
- One controller per endpoint.
- The folder structure should correspond to the business domain.

**Tasks**
- [ ] Separate `wazuh-api` controller by per endpoint controllers and implement the new services.
- [ ] Separate `wazuh-elastic` controller by per endpoint controllers and implement the new services.
- [ ] Separate `wazuh-hosts` controller by per endpoint controllers and implement the new services.
- [ ] Separate `wazuh-reporting` controller by per endpoint controllers and implement the new services.
- [ ] Separate `wazuh-utils` controller by per endpoint controllers and implement the new services.
