### ISSUE TITLE
Migrate all app routes to react-router

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3301]
| Parent Issue |
| #3276 |

**Description**

**Tasks**
- [ ] Migrate all app routes to react-router
  - [ ] Recover what has already been done for React main component 
  - [ ] Recover what has already been done for react-router and apply last routes changes
  - [ ] Migrate all Angular resolvers to redux states or services

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
