### ISSUE TITLE
New section for Office365 module

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3371]
| Wazuh version | 
|---|
|4.3.0|

### Epic - New section for Office365 module

Hi team, we need to do the UI support for the module Office365. The related epic is [#wazuh/wazuh/4983](https://github.com/wazuh/wazuh/issues/4983).

At the end of this epic, these user stories should be completed:

- As a user, I want to enable/disable the Office365 section from my UI
- As a user, I want to navigate to the Office365 section from the menu
- As a user, I want to see a principal dashboard based on the Office365 module events
- As a user, I want to see an interactive panel to explore all capabilities of the Office365 module
- As a user, I want to see all the events related to the Office365 module in the discover

<details>
  <summary>Related issues</summary>
  
|Issues|
|---|
[Office365 module] Implement Explore Agent disabled state in no Agent moduleswazuh-kibana-app #3530
[Module] [Office365] Add `rule.level` and `rule.id` fields to alerts table of each drill down viewwazuh-kibana-app #3560
Specify filters for Office365 search barwazuh-kibana-app #3532
Specify filters for Office365 search barwazuh-kibana-app #3533
[Module] [Office365] Add the configuration viewerwazuh-kibana-app #3507
Module Office 365 configuration viewerwazuh-kibana-app #3524
Office365 link in agent viewwazuh-kibana-app #3550
SecurtyAlerts does not update automaticallywazuh-kibana-app #3522
[Module] [Office365] [Panel] Add module configuration to the module informationwazuh-kibana-app #3539
[Module] [Office365] [Panel] Add the view for the module configurationwazuh-kibana-app #3541
Enhance OverviewActions to have custom buttonswazuh-kibana-app #3485
Change operator from "is" to "is one of" to allow multiple selectionswazuh-kibana-app #3521
Improve reusability of Security Alerts componentwazuh-kibana-app #3527
Refactor useFilterManagerwazuh-kibana-app #3512
Filter suggested values by the already active filterswazuh-kibana-app #3510
Specify tables for Office365 panel and their drilldownswazuh-kibana-app #3511
Added 2 new aggtables to office365 with their drilldownswazuh-kibana-app #3526
[Office365 module] Fix Office365 Sample Data Agent IDwazuh-kibana-app #3523
Fix/office agentwazuh-kibana-app #3528
Create an advanced search barwazuh-kibana-app #3463
Create drilldown tablewazuh-kibana-app #3493
Create a modular view for the moduleswazuh-kibana-app #3422
Create side panel component with module infowazuh-kibana-app #3421
Integrate office365 alerts into the geolocalization pipelinewazuh-kibana-app #3400
Create a base module for the office365wazuh-kibana-app #3391
Create table components for new moduleswazuh-kibana-app #3476
Dynamically generate options for filter menuwazuh-kibana-app #3500
Create a component that checks for sample datawazuh-kibana-app #3423
Add office365 events to the sample data modulewazuh-kibana-app #3401
Query config refactorwazuh-kibana-app #3489
Propose the Office365 Dashboard designwazuh-kibana-app #3379
Research info about the modulewazuh-kibana-app #3380

</details>

**Comment by asteriscos** [comment]
Pending list:

### General
- [ ] Change `custom-search-bar` combobox operator from *"is"* to *"is one of"* to allow multiple selections
- [ ] Set 4 aggregation tables in Main Panel view
- [ ] Define and setup `custom-search-bar` filter fields
- [ ] Change security alerts table columns according to each drilldown configuration
- [ ] Implement Explore Agent disabled state in no Agent modules
- [ ] Add HOC `withModuleNotForAgent` to hide office365 vies when there's a pinned agent
- [ ] Fix Office365 Sample Data Agent ID
- [ ] Add Office365 to `Management/Configuration viewer` issue #3507
- [ ] Typescript
- [ ] Unit tests

### Side Panel Module Config
- [ ] Request module configuration for each node in the cluster
- [ ] Add accordion collapsible description for each node configuration
- [ ] Fix Side Panel Module Config View when rendering properties with object values
- [ ] Add another call to action to toggle collapsible Side Panel (wishlist)
- [ ] Fix Side Panel collapsible when kibana navigation is docked

**Comment by mpRegalado** [comment]
`AggTables` definition in progress in https://github.com/wazuh/wazuh-kibana-app/issues/3511

**Comment by mpRegalado** [comment]
Created https://github.com/wazuh/wazuh-kibana-app/issues/3527 to deal with issues regarding the reusability of SecurityAlerts, where we cannot properly define its columns or set their name.

**Comment by CPAlejandro** [comment]
Found a bug when reducing the width in some of the Office Drilldown tables, like entering some of the Top Users, in this case
![image](https://user-images.githubusercontent.com/17100196/128019494-2bb5473f-a6a4-42e0-8ff6-0d7657a9280f.png)

**Comment by AlexRuiz7** [comment]
## BUG
Pinning agents breaks the visualizations.

![Peek 2021-10-19 17-25](https://user-images.githubusercontent.com/15186973/137942375-35954d41-2389-4cb3-8fa0-4c1f10aaa8d5.gif)
