### ISSUE TITLE
Regression Wazuh app 4.2.2 r4202

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3537]
| Wazuh | Revision | RC | Core RC |
| --: | --: | --: | --: |
| 4.2.1 | 4202 | 1 | 1 |

Hello team, in order to check the quality of the app 4.2.1 r4202 we need to perform these tasks
- [x] Planning regression of revision
We are creating new test cases for every scenario not contemplated in previous executions that should validate the functionality of the features included in the changelog for 4.2.1

- [x] Design test cases for changelog

  -- New Features
    - [x] Wazuh help links in the Kibana help menu #3170
    - [x] Redirect to group details using the group query param in the URL #3184
    - [x] Configuration to disable Wazuh App access from X-Pack/ODFE role #3222 #3292
    - [x] Added confirmation message when closing a form #3221
    - [x] Improvement to hide navbar Wazuh label. #3240
    - [x] Add modal creating new rule/decoder #3274
    - [x] New functionality to change app logos #3503
 
  -- Changes
    - [x] Removed module titles #3160
    - [x] Changed default wazuh.monitoring.creation app setting from d to w #3174
    - [x] Changed default wazuh.monitoring.shards app setting from 2 to 1 #3174
    - [x] Removed Sha1 field from registry key detail #3189
    need windows agent
    - [x] Removed tooltip in last breadcrumb in header breadcrumb #3250 
    - [x] Refactored the Health check component #3197
    - [x] Added version in package downloaded name in agent deploy command #3210
    - [x] Removed restriction to allow only current active agents from vulnerability inventory #3243
    need real vulnerabilities to test
    - [x] Move API selector and Index Pattern Selector to the header bar #3175
    - [x] Health check actions notifications refactored and added debug mode #3258
    - [x] Improved visualizations object configuration readability #3355
    - [x] Changed the way kibana-vis hides the visualization while loading, this should prevent errors caused by having a 0 height visualization #3349
 
  -- Fixes
    - [x] Fixed screen flickers in Cluster visualization #3159
    - [x] Fixed the broken links when using server.basePath Kibana setting #3161
    - [x] Fixed filter in reports #3173
    - [x] Fixed typo error in Settings/Configuration #3234
    - [x] Fixed fields overlap in the agent summary screen #3217
    - [x] Fixed Ruleset Test, each request is made in a different session instead of all in the same session #3257
    - [x] Fixed the Visualize button is not displaying when expanding a field in the Events sidebar #3237
    - [x] Fix modules are missing in the agent menu #3244
    - [x] Fix improving and removing WUI error logs #3260
    - [x] Fix some errors of PDF reports #3272
    - [x] Fix TypeError when selecting macOS agent deployment in a Safari Browser #3289
    - [x] Fix error in how the SCA check's checks are displayed #
    - [x] Fixed message of error when add sample data fails #3241
    - [x] Fixed modules are missing in the agent menu #3244
    - [x] Fixed dark mode visualization background in pdf reports #3315
    - [x] Adapt Kibana integrations to Kibana 7.11 and 7.12 #3309
    - [x] Fixed error agent view does not render correctly #3306
    - [x] Fixed miscalculation in table column width in PDF reports #3326
    - [x] Normalized visData table property for 7.12 retro-compatibility #3323
    - [x] Fixed error that caused the labels in certain visualizations to overlap #3355
    - [x] Fixed export to csv button in dashboards tables #3358
    - [x] Fixed Elastic UI breaking changes in 7.12 #3345
    - [x] Fixed Wazuh main menu and breadcrumb render issues #3347
    - [x] Fixed generation of huge logs from backend errors #3397

- [x] Execution of the regression
The execution is being made as we create new test cases.

>Environments used:

**Comment by MauGaP** [comment]
we planned on creating new test cases for every scenario not contemplated in previous executions that should validate the functionality of the features included in the changelog for 4.2.1

**Comment by matiasmoreno876** [comment]
We continue to advance with the creation of test cases at the same time that we execute them, for version 4.2.1

**Comment by matiasmoreno876** [comment]
> Test cases run and developed for issues

- [Wazuh help links in the Kibana help menu #3170](https://github.com/wazuh/wazuh-kibana-app/pull/3170)
- [Improvement to hide navbar Wazuh label. #3240](https://github.com/wazuh/wazuh-kibana-app/pull/3240)
- [Add modal creating new rule/decoder #3274](https://github.com/wazuh/wazuh-kibana-app/pull/3274)
- [New functionality to change app logos #3503](https://github.com/wazuh/wazuh-kibana-app/pull/3503)
- [Removed module titles #3160](https://github.com/wazuh/wazuh-kibana-app/pull/3160)
- [Changed default wazuh.monitoring.creation app setting from d to w #3174](https://github.com/wazuh/wazuh-kibana-app/pull/3174)
- [Changed default wazuh.monitoring.shards app setting from 2 to 1 #3174](https://github.com/wazuh/wazuh-kibana-app/pull/3174)
- [Removed tooltip in last breadcrumb in header breadcrumb 3250](https://github.com/wazuh/wazuh-kibana-app/pull/3250)
- [Improved visualizations object configuration readability #3355](https://github.com/wazuh/wazuh-kibana-app/pull/3355)
- [Fixed screen flickers in Cluster visualization #3159](https://github.com/wazuh/wazuh-kibana-app/pull/3159)
- [Fixed typo error in Settings/Configuration #3234](https://github.com/wazuh/wazuh-kibana-app/pull/3234)
- [Fixed fields overlap in the agent summary screen #3217](https://github.com/wazuh/wazuh-kibana-app/pull/3217)
- [Fixed the Visualize button is not displaying when expanding a field in the Events sidebar #3237](https://github.com/wazuh/wazuh-kibana-app/pull/3237)
- [Fix modules are missing in the agent menu #3244](https://github.com/wazuh/wazuh-kibana-app/pull/3244)
- [Fix some errors of PDF reports #3272](https://github.com/wazuh/wazuh-kibana-app/pull/3272)
- [Fix TypeError when selecting macOS agent deployment in a Safari Browser #3289](https://github.com/wazuh/wazuh-kibana-app/pull/3289)
