### ISSUE TITLE
Wazuh App password is saved as plain text 

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh-kibana-app#3637]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.2.0 | Kibana server | Elasticsearch/OD|

Hello team,

I'm opening this issue because the password for the Wazuh App is still saved as plain text format in the `/usr/share/kibana/data/wazuh/config/wazuh.yml` file, in the Kibana server.

Regards.

**Comment by Desvelao** [comment]
We should offer a possibility to hide host's password, but this could be extended to more settings as:
- host's url
- host's port
- host's username
- host's password
- host's run_as

Possibilites:
- [Kibana keystore](https://www.elastic.co/guide/en/kibana/7.10/secure-settings.html)
- Encripted file

### Tasks
- [ ] Research the methods to offer this capability.
- [ ] Advantages and disadvantages of each method
- [ ] Define the method to use if possible
- [ ] Develop the selected method
- [ ] Document the capability
  - [ ] App
  - [ ] Oficial Wazuh documentation

**Comment by Desvelao** [comment]
## Researching

### Kibana keystore
The [Kibana keystore](https://www.elastic.co/guide/en/kibana/7.10/secure-settings.html) can store sensitive data.

#### How to use
1. Create the keystore
```sh
bin/kibana-keystore create
```
2. Add a setting to the store:
```sh
bin/kibana-keystore add <setting_name>
```
Fill the prompt with the value for the setting.

Example:
```sh
bin/kibana-keystore add wazuh.hosts.default.password
```

> Kibana Dev mode
> The Kibana keystore can be used in dev mode with the next command:
> ```sh
> node scripts/kibana_keystore
> ```

If some plugin defines in its configuration schema (export a `config` constant in the `server/index.[ts|js]`) the setting that was defined in the keystore, the value can be accessed from the plugin. In this way, some settings could be configurated in the keystore instead of the app configuration file `wazuh.yml`. I don't know how to access in realtime to the keystore if we want that doesn't require restart the Kibana to update the settings.

**Comment by asteriscos** [comment]
This issue will be resolved in:
- https://github.com/wazuh/wazuh-kibana-app/issues/4159
