### ISSUE TITLE
[Compatibility] OpenSearch Dashboards app

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3794]
## Description

We need to adapt the current app for Kibana to be compatible with OpenSearch Dashboards.

## Tasks
- [x] Code
  - [x] Adapt the platform dependencies to OpenSearch Dashboards.
- [x] Plugin
  - [x] Dependencies of other platform plugins
  - [x] App dependencies
- [x] Testing
  
## Deseable tasks
- Remove Kibana specific code
  - In the current app codebase, there is logic that is executed depending on the Kibana version. We could remove the logic we don't need
  - Remove logic related to X-Pack
- Create a pipeline to build app packages using Jenkins
- Create a GitHub action to build app packages

**Comment by Desvelao** [comment]
## Development
branch: `4.3-7.10-opensearch-dashboards`

**Comment by Desvelao** [comment]
## Daily status
The app is functional in development mode. 

## Tasks
- [ ] Update with the last fixes of base app of `rc3` (Kibana 7.10.2)
- [ ] Testing to check that app functionality with special attention to platform-related things
- [ ] Check the building of the app package (manual)

## Deseable tasks
- [ ] Create a pipeline to build app packages using Jenkins
- [ ] Create a GitHub action to build app packages

**Comment by gittygoo** [comment]
@Desvelao since this aparently is working on the "4.3-7.10-opensearch-dashboards" branch already any chance you can generate a .zip package to test on opensearch dashboards?

**Comment by Desvelao** [comment]
Hi @gittygoo, it is required to build a package (.zip) for the Wazuh app. In the [comment](https://github.com/wazuh/wazuh-kibana-app/issues/3794#issuecomment-1010933963), a of the tasks is trying to build this package and check that all works as expected in production. 

The process to build the package should be similar to Kibana, as explained [here](https://github.com/wazuh/wazuh-kibana-app/wiki/Build-Wazuh-app-package#building-wazuh-app-package-for-kibana-710-or-higher), but we have not tested it yet.

Keep in mind that the current development branch is missing some changes.

We will update the issue when the task is done.

**Comment by Desvelao** [comment]
## Changes
- Merged last changes integrated into the base app for `4.3.0`
- Removed logic related to `X-Pack security`
- Removed how to manage index pattern fields are refreshed depending on the plugin platform version. In OpenSearch Dashboards, there is only a way to manage the refresh of them but the app had 2 ways to manage it due to changes in the currently supported Kibana versions
- Fixes pre-build script to generate an app package

**Comment by dblock** [comment]
Thanks for all the awesome work @Desvelao! I see users asking for this in https://github.com/opensearch-project/OpenSearch/pull/847#issuecomment-1031494124, what's the current release status and is there anything anyone can do to help?

**Comment by Desvelao** [comment]
## Changes
- Fixed some unchanged references to Elasticsearch that provoked error when adding sample data or get suggestions in the `Panel` for the Office 365 and GitHub modules
- Updated the copyright year in the files
- Replaced the references to the plugin platform (name, installation path, OpenSearch guide)
- Some adjustment in the `README.md` file
  - Moved the compatibility matrix
  - Removed guide to install the plugin
  
I created a new branch `4.3-1.2-osd`

**Comment by Desvelao** [comment]
> Thanks for all the awesome work @Desvelao! I see users asking for this in [opensearch-project/OpenSearch#847 (comment)](https://github.com/opensearch-project/OpenSearch/pull/847#issuecomment-1031494124), what's the current release status and is there anything anyone can do to help?

Hi @dblock , soon there will be related news.

**Comment by astateofmind01** [comment]
Any news on this??
Is there a place to download the wazuh dashboard for opensearch?

**Comment by Desvelao** [comment]
Hi @astateofmind01, currently there is no available published package of Wazuh plugin for installing in OpenSearch Dashboards.

# Alternatives
## Use Wazuh Dashboard

Starting at Wazuh 4.3.0, there is a `Wazuh dashboard` and `Wazuh indexer` packages based on the distribution of OpenSearch Dashboards and OpenSearch respectively. `Wazuh dashboard` includes the Wazuh plugin. It is the [default method](https://documentation.wazuh.com/current/getting-started/components/index.html#components) to install the components required by Wazuh.

## Build a package compatible with OpenSearch Dashboards

If you want to use OpenSearch Dashboards and OpenSearch instead, you could build a package of Wazuh plugin compatible with OpenSearch Dashboards and install it.

### Generate a package from an available branch/tag in the `wazuh-kibana-app` repository. [Easy]
Use the next utility: https://github.com/wazuh/wazuh-packages/tree/master/wazuhapp/opensearch-dashboards. Its use is similar to the case for Kibana, explained here: https://documentation.wazuh.com/current/development/packaging/generate-wazuh-kibana-app.html#wazuh-kibana-plugin. Take into account to use the utility for OpenSearch Dashboards.

### Develop new features/fixes. [Hard]
If you want to put your hands in the source code to develop new features, apply some fix or want a more complicated way to build the package, take a look to the next guides for Kibana and adapt to the OpenSearch Dashboards case:
  - Develop new features: https://github.com/wazuh/wazuh-kibana-app/wiki/Develop-new-features
  - Build the package: https://github.com/wazuh/wazuh-kibana-app/wiki/Build-Wazuh-app-package.

> The current available branches/tags are compatible with OpenSearch Dashboards 1.2.0, so you could want to use that version for the installation of OpenSearch Dashboards in development mode, this means to use the [1.2.0 tag](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/1.2.0).
>
> If you are using another version of OpenSearch Dashboards and you want a compatible plugin, you could try the appropiate tag for the OpenSearch Dashboards in development mode but take in account we don't test its compatibility and you could need to apply some changes to the source code.
> Moreover, in the building process of the package, the version of OpenSearch Dashboards is asked. This means you could use an OpenSearch Dashboards in development mode of `1.2.0` tag to build a package for another version of OpenSearch Dashboards. This could be a problem if there is differences in the core functions used by the Wazuh plugin, so it is recommended to use the same version to building the package and installing in the production distribution.

The compatibles branches/tags for OpenSearch Dashboards contain the suffix `-wzd`. At this moment, they are:
- `4.3-1.2-wzd`: development branch for Wazuh 4.3.x and Wazuh dashboard based on OpenSearch Dashboards 1.2.0
- `v4.3.0-1.2.0-wzd`: tag for Wazuh 4.3.0 and Wazuh dashboard based on OpenSearch Dashboards 1.2.0
- `v4.3.0-1.2.0-wzd`: tag for Wazuh 4.3.1 and Wazuh dashboard based on OpenSearch Dashboards 1.2.0

**Comment by astateofmind01** [comment]
Any chance for the same for a newer version of opensearch?

**Comment by Desvelao** [comment]
Hi @astateofmind01 ,

At this moment, we don't offer compatibility with OpenSearch Dashboards exposing a public plugin, due to our focus is on the development for Wazuh dashboard so we work with the version of this, which currently is OpenSearch Dashboards 1.2.0. We didn't test if the current plugin is compatible with later OpenSearch Dashboards versions. Due to these reasons, when the OpenSearch Dashboards version that is based Wazuh dashboard changes to some later, we will work on the compatibility.

If you have interest, you could try to run or build a plugin package for another OpenSearch Dashboards version.

Eventually, Wazuh dashboards will change the OpenSearch Dashboards version.
