### ISSUE TITLE
Design a way to enable users to launch vulnerability scans and syscollector scans

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3878]
We need to enable users to launch vulnerability scans and syscollector scans from the UI. 

```mermaid
  flowchart TD;
      UI <--> API
      API <--> modulesd
      API <--> remoted
```

We will need to call methods of the API to notify the user wants to launch a task. This task will be a vulnerability scan or a syscollector scan. In the future, we might have more tasks, but for now, we will not design a complete tasks' module on the UI.

The API will also receive a filter to select the agents. This filter needs to be the same filter we already use on the agent's list.

As a first proposal, we can include buttons in the agents' table in the agents screen.

![image](https://user-images.githubusercontent.com/2181918/156599699-079abeb5-4898-488a-ad3c-ffed236942ff.png)

Where launch is a dropdown with the available tasks: vulnerability scan or syscollector scan.

**Comment by DProvinciani** [comment]
Apart from the requirements mentioned in the description, the implementation of this epic should also:

- Add buttons in the individual agent dashboards to trigger syscollector and Vulnerability Detector scans for that particular agent.
- Add a checkbox together with the button for triggering the Vulnerability Detector scans (for individual or multiples agents) to instruct the module to trigger alerts independently on whether is the first scan or not.
- Add a button in the Vulnerability Detector dashboard to trigger an update of the vulnerabilities data feeds in all the Wazuh cluster nodes in which the Vulnerability Detector module is enabled.

**Comment by AlexRuiz7** [comment]
## Tasks

- Draft UI components to run manual scans on the following views:
  - [ ] Agents general view
    <details>
      <summary>Click to expand!</summary>
      A new button can be added to the table, as follows:
      
      ![image](https://user-images.githubusercontent.com/15186973/161302289-cb0bb021-e21a-4bca-9c48-9f06f2817d05.png)
      
      The `Scan` button will be a [popover component](https://codesandbox.io/s/wazuh-manual-scans-from-the-ui-dropdown-button-component-mz4lit?file=/index.js) that includes several switches to allow the user to select the scans to perform. Once the user clicks on `Launch`, the tasks will be sent to the agents being displayed on the table on that instant.
    </details>
  - [ ] Agents specific view
  - [ ] Agents Vulnerability Detector view
  - [ ] Agents System Inventory view

**Comment by AlexRuiz7** [comment]
We must also extend this new functionality to our Splunk App.
Dafts will be provided as sson as possible.

**Comment by DProvinciani** [comment]
After reviewing this proposal with the team, we suggest the next set of changes:

- Change the text `as first scan` with `trigger alerts`.
- Disable and set to grey color the `trigger alerts` switch if the `run scan` switch is off.
- Add correct dummy data to the tasks table in the agents' view.

Also, we would like to discuss the feasibility of implementing the next changes:

- The `+` sign in the scan button maybe should be another icon.
- The `scan` button takes effect over the list of agents displayed according to the filter, but not the `deploy` button on the right side. This could be confusing for the users.
- Add checkboxes to the list of agents so that the users could apply a filter, and then select the agents of interest to perform the scans.

**Comment by AlexRuiz7** [comment]
## Modifications applied

- [x] Change the text `as first scan` with `trigger alerts`.
- [x] Disable and set to grey color the `trigger alerts` switch if the `run scan` switch is off.
- [ ] Add correct dummy data to the tasks table in the agents' view. (extend)
----

> - The + sign in the scan button maybe should be another icon.

As noted on the proposal, the current icons are placeholders, and can be changed or even removed.

> - The scan button takes effect over the list of agents displayed according to the filter, but not the deploy button on the right side. This could be confusing for the users.

The `Deploy` button simply opens the interactive helper to deploy agents, does not perform the actual deployment. You can test it out on our demo environment.

> - Add checkboxes to the list of agents so that the users could apply a filter, and then select the agents of interest to perform the scans.

Overkill imo, as it is already possible to select the agents of interest using filters.

**Comment by DProvinciani** [comment]
Leaving some comments after reviewing this design with @havidarou and @santiago-bassett 👍 

- Remove the switch `as first scan` (currently renamed to `trigger alerts`). This was considered a quite dangerous option for beginners as they could flood the environment with alerts. Because of this, we decided to expose this option only through the Wazuh API.
- Remove the `scan` button from the global agents view. In this first version, we are planning to allow triggering scans only for individual agents from the UI. The users will be able to trigger a scan for a list of agents using the Wazuh API.
- Remove the tasks table from the individual agent view. We should look for a better place and in any case, just remove it.
- The `scan` button should be called `scan on-demand`.

**Comment by AlexRuiz7** [comment]
## Resolution of the requested changes

- [ ] Remove the `Scan` button from the [1] Agents view.
- [ ] Remove the `As first scan` switch (`Trigger alerts`).
- [ ] Remove the [3] `Tasks` table from the individual agent's view.
- [ ] Rename the `Scan` button to `Scan on-demand`

**Comment by AlexRuiz7** [comment]
Waiting for validation.

**Comment by gdiazlo** [comment]
Superseded by https://github.com/wazuh/wazuh/issues/15002
