### ISSUE TITLE
[UI] The dashboard is reloaded when the `hideManagerAlerts` is enabled displaying different data

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3917]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The visualizations of dashboards are rendered with data and after the visualizations are reloading with a different subset of data.

**Tasks**
- [ ] Research the cause of the problem that renders 2 times.
- [ ] Describe the cause.
- [ ] Research about possible solutions.

**Screenshots**

https://user-images.githubusercontent.com/34042064/160104821-c1131292-3e14-431a-a298-be8dae620615.mov

**Comment by Desvelao** [comment]
I didn't review the source code or try to replicate the problem, but this could be caused due to applying in a different moment the filters.

First load/render: basic filters of module
Second load/render: the filter added by the `hideManagerAlerts` setting. (`NOT agent.id:000`).

We should investigate it properly.
