### ISSUE TITLE
Improve error management

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4145]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

### Description
On this issue, we will analyze all the error treatments.
We need to find all the cases where we catch errors and decide how to throw them to other application methods.

In this issue, we want to improve the error management in our app.
We need to normalize and improve the treatment of errors.

### Steps to find the issue scope:

- [x] Check all the current error treatment
   1. Tracking all error throw errors that don't return an error instance
   2. Searching those methods usage (previous step)
   3. Analyzing possible solutions, best error treatment
**The analysis was documented in the following issue comments:** 
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1127751874
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1129001143
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1129001589
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1129002088
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1129002538
- https://github.com/wazuh/wazuh-kibana-app/issues/4145#issuecomment-1129002659

- [x] Create a solution that solves all the current error treatment problems.
- [x] Implement a `first version of Error Handler` and document the solution. https://github.com/wazuh/wazuh-kibana-app/pull/4163
- [ ] Replace the use of error orchestrator in error management solution
- [ ] Apply the new error management solution to a known issue #5210 
- [ ] Attack the error sources and use typescript to make interfaces and create better type error management.
  1. On server-side controllers #5227
  2. On client-side services #5262

Related issue 
- #5227
- #4297

**Comment by Machi3mfl** [comment]
## wz-api-check:
- [public/react-services/wz-api-check.js](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/wz-api-check.js)

<details>
  <summary>checkStored</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-api-check.js#L50-L61
</details>

<details>
  <summary>checkApi</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-api-check.js#L89-L99
</details>

## wz-request:
- [public/react-services/wz-request.ts](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/wz-request.ts)

<details>
  <summary>genericReq</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-request.ts#L62-L99
</details>

<details>
  <summary>apiReq</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/wz-request.ts#L118-L132
</details>

<details>
  <summary>csvReq</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/wz-request.ts#L149-L153
</details>

## generic-request:


[/public/react-services/generic-request.js](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/generic-request.js)


<details>
  <summary>request</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/generic-request.js#L92-L115
</details>

To check:

- [/public/react-services/saved-objects.js](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/saved-objects.js)

<details>
  <summary>existsIndexPattern</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L137-L141
</details>

<details>
  <summary>getExistingIndexPattern</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L172-L179
</details>

<details>
  <summary>createSavedObject</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/saved-objects.js#L195-L199
</details>

<details>
  <summary>refreshFieldsOfIndexPattern</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L217-L221
</details>

<details>
  <summary>refreshIndexPattern</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L238-L243
</details>

<details>
  <summary>createWazuhIndexPattern</summary>
https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L292-L296
</details>

**Comment by Machi3mfl** [comment]
## 2. wz-request: [public/react-services/wz-request.ts](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/wz-request.ts)

<details>
  <summary>genericReq</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-request.ts#L62-L99
</details>

<details>
  <summary>apiReq</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-request.ts#L118-L132
</details>

<details>
  <summary>csvReq</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/wz-request.ts#L149-L153
</details>

**Comment by Machi3mfl** [comment]
##  3. generic-request: [/public/react-services/generic-request.js](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/generic-request.js)

<details>
  <summary>request</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/generic-request.js#L92-L115
</details>

**Comment by Machi3mfl** [comment]
## 4. saved-objects: [/public/react-services/saved-objects.js](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/react-services/saved-objects.js)

<details>
  <summary>existsIndexPattern</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L137-L141

</details>

<details>
  <summary>getExistingIndexPattern</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L172-L179

</details>

<details>
  <summary>createSavedObject</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L195-L199
</details>

<details>
  <summary>refreshFieldsOfIndexPattern</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L217-L221
</details>

<details>
  <summary>refreshIndexPattern</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L238-L243
</details>

<details>
  <summary>createWazuhIndexPattern</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/react-services/saved-objects.js#L292-L296
</details>

**Comment by Machi3mfl** [comment]
## 5. check-api.service: [/public/components/health-check/services/check-api.service.ts](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/components/health-check/services/check-api.service.ts)

<details>
  <summary>trySetDefault</summary>

https://github.com/wazuh/wazuh-kibana-app/blob/aa1a8e41a4337610889dd0332c63a1214ce91582/public/components/health-check/services/check-api.service.ts#L40-L48
</details>

**Comment by Machi3mfl** [comment]
### This PR also resolves issue #4030 by implementing the use of the new Error Factory feature on root services

- Added [SettingsController](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/settings/settings.js) tests to check the controller catches an Error instance instead of a string.

### Solution screenshot

https://user-images.githubusercontent.com/6089438/171688212-d0f9d71b-326a-4157-8c03-c2f9a870ab20.mov

**Comment by Machi3mfl** [comment]
### Next steps

- Identify error types received by the error factory
- Create Errors classes for specific errors 
- Implement error treatment by error type
