### ISSUE TITLE
Compatibility with Wazuh indexer based on OpenSearch 2.3.0

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4160]
## Description
We need to ensure the UI compatibility with the next Wazuh Indexer which might be based on OpenSearch 2.0.0. This update is still being discussed, and we need to know potential issues. 

- [x] Review OpenSearch and OpenSearch Dashboards latest stable changelog 
- [x] Identify improvements and potential impact on the UI
- [x] Report the findings to @wazuh/cicd to coordinate the upgrade effort.
- [x] Develop a testing environment to verify our components would work under this new build

**Note**: we'll move to the latest version of OpenSearch, which is 2.3.0 at this time.

## Issues
- [x] #4480
- [x] #4683
- [x] #4502
- [x] #4597
- [x] #4650
- [x] #4353
- [x] #4740

**Comment by AlexRuiz7** [comment]
## OpenSearch 2.0.0
 
### [Breaking changes](https://opensearch.org/docs/2.0/breaking-changes/)

#### Deprecate Compatibility override
> The override main response setting compatibility.override_main_response_version is deprecated from OpenSearch version 1.x and removed from OpenSearch 2.0.0. This setting is no longer supported for compatibility with legacy clients.

@wazuh/cicd This setting must be removed in the `opensearch.yml` file.

## Development environments

We need to adjust our development environments with the following changes:

- [ ] Comment or remove the previous configuration setting in the `opensearch.yml` file
- [ ] Re-tag our image on [Quay.io](https://quay.io/repository/wazuh/osd-dev?tab=tags) from 2.0 to 2.0.0.
- [ ] Fix a typo on our Docker Compose file, as the network is Docker network is created with the name `os-dev-{OS_VERSION}`. Must be changed to `os-dev-${OS_VERSION}` in order to name it dynamically.

**Comment by AlexRuiz7** [comment]
## OpenSearch 2.2.0 is live

OpenSearch 2.2.0 was released the 12th of August. We need to create images for this new version, if we decide to provide support for this new version.


### OpenSearch and Dashboards 2.2.0 Release Notes
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.2.0.md

### Tasks

- [ ] Review the Release Notes for this version.
- [ ] (Optional) Create and upload a Docker image for OSD-Dev 2.2.0 to our [Quay.io](https://quay.io/repository/wazuh/osd-dev?tab=tags) repository.

**Comment by AlexRuiz7** [comment]
## OpenSearch 2.2.1 is live

OpenSearch 2.2.1 was released the 2nd of September. We need to create images for this new version, if we decide to provide support for this new version.


### OpenSearch and Dashboards 2.2.1 Release Notes
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.2.1.md

### Tasks

- [ ] Review the Release Notes for this version.
- [ ] (Optional) Create and upload a Docker image for OSD-Dev 2.2.0 to our [Quay.io](https://quay.io/repository/wazuh/osd-dev?tab=tags) repository.

## IMPORTANT

This version solves a **CVE** in the **OpenSearch Reporting plugin**. The patched versions are 1.3.5 and 2.2.1, so any other version is vulnerable.

More information about this vulnerability can be found in this [link](https://github.com/opensearch-project/dashboards-reports/security/advisories/GHSA-pm2x-4c64-x8g7).

**Comment by yenienserrano** [comment]
In OpenSearch 2.2.1 a class is being added to the navbar that is breaking the navbar.

![Image](https://user-images.githubusercontent.com/63758389/189691870-f3acd58f-5385-4dd0-9a43-1a8245827a8e.png)

![Image](https://user-images.githubusercontent.com/63758389/189691933-42974155-7256-407e-b075-f74e10c59699.png)

**Comment by samrit-narshing** [comment]
hi  . is there a way to know  how to build or get the wazuh plugin package (zip) for opensearch 2.2.1 ..  ?

**Comment by yenienserrano** [comment]
Hi @samrit-narshing thank you for your interest in Wazuh, currently the application is not compatible with OSD 2.2.1, this issue is to see if it can be compatible with this version.

**Comment by AlexRuiz7** [comment]
Hello @wazuh-cloud-cicd team.

One of the breaking changes of OS 2.x is the deprecation of the setting ```compatibility.override_main_response_version```, however, we still use this setting in the 4.4 branch, with a comment that says that this setting is required for Filebeat 7.10.2 to work. This is worrying.

https://github.com/wazuh/wazuh-packages/blob/981377a762e2a26860e668d7709b6f150f7de17c/unattended_installer/config/indexer/indexer.yml#L35-L36

Are you aware of this conflict?

**Comment by AlexRuiz7** [comment]
## OpenSearch 2.3.0 is live

OpenSearch 2.3.0 was released the 14th of September. We need to create images for this new version, if we decide to support it.


### OpenSearch and Dashboards 2.3.0 Release Notes
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.3.0.md

### Tasks

- [x] Review the Release Notes for this version.
- [ ] Create and upload a Docker image for OSD-Dev 2.2.1 to our [Quay.io](https://quay.io/repository/wazuh/osd-dev?tab=tags) repository.
- [ ] Test our app with this new version.


### Notable changes

- Changes in some visualizations
> :mountain_railway: Refactor
> - [DeAngular][visualization][vislib] Remove angular from vislib (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2138)
> - Change timeline icon (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2162)

**Comment by yenienserrano** [comment]
From what I was testing I could not find other things to highlight in the 2.2.1 versions and, since version 2.3.0 was released, I was testing that version and so far I found no differences in performance with respect to version 2.2.1.

**Comment by yenienserrano** [comment]
A problem has been found in version 2.x with fly outs. When clicking inside the fly out, the fly out closes. This may be due to the Elastic/EUI update used.

<details>
<summary>Screenshot</summary>

https://user-images.githubusercontent.com/63758389/191055783-8a658ce0-0bc4-466f-a050-f672f7a45360.mp4

</details>

**Comment by yenienserrano** [comment]
Compared to Opensearch 1.2.0


| OpenSearch Dashboard | v2.0.0 | v2.1.0 | v2.2.1 | v2.3.0 |
|--------|--------|--------|---------|---------|
| `compatibility.override_main_response_version` | not supported | supported | supported | supported |
| Changes in breadcrumb styles | No | No | Yes | Yes |
| Elastic/EUI Version Changes | Yes, `34.6.0` | Yes, `34.6.0` | Yes, Fork `34.6.0` | Yes, Fork `34.6.0` |
| Problems with fly outs when closing | Yes | Yes | Yes | Yes |

**Comment by AlexRuiz7** [comment]
The team has decided to move to OpenSearch 2.3.0 on the new minor version of Wazuh.
