### ISSUE TITLE
App white-labeling

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4392]
# White-labeling

 Supporting our partners in their commercial offerings.

## Introduction

We want to make it easier for our partners and the general open source community to white-label our application interface to include their branding.

## Strategy

We can use multiple strategies to allow our users to dynamically change the aspect of the UI.
Most changes will need to be made to the base `wazuh-indexer` and `wazuh-dashboard` packages, while the application will need to develop an interface to manage these changes.

### Important use cases

- Use case: vendors that don’t want the users to access the customization options
  - Proposed solution: access to the customization section only for authorized roles.

- Use case: possibility to add “Powered by Wazuh” to let users know the product they are using under the hood. 
  - Proposed solution: keep the About section of the app unchanged.

- Use case: internationalization. Support for different languages (not officially supported by Wazuh). Users that do want to translate the plugin without the need to modify the source code.
  - Proposed solution: extract the hard-coded texts to resource assets, which can be switched and added without source code changes.

### CSS variables

Design our custom `opensearch-dashboard` theme to use a separate CSS that will define variables that will affect the logos, texts, colors, and fonts of the areas we want to personalize.

Their values can be overridden programmatically by `style.setProperty()` and the related styles change accordingly, in run-time.

Our application will need a configuration to save and restore these values on page load.
All evergreen browsers support CSS variables.
We might be able to style the favicon and support different themes too.

### Requirements 

1. Wazuh dashboard - login: Logo, title, and subtitle
2. Wazuh dashboard - plugin: Drop-down icon
3. Wazuh dashboard - plugin - reports: Icon
4. Wazuh dashboard - plugin - reports: Contact info
5. Wazuh dashboard - plugin - reports: Copyright
6. Wazuh dashboard - browser tab: Title

The items above translate to the following tasks:

**Prepare the app for white-labeling**
- [x] #4443 
- [x] #4446 
- [x] #4450 

**Include white-labeling support to the app**
These issues depend on the issues above.

- [x] Custom branding-- login page
  Will be done in a **next iteration**, using the platform's settings.
- [x] #3491 & #4434
- [x] #4426
- [x] #4506 
- [x] Custom branding-- page title and favicon
  Will be done in a **next iteration**, using the platform's settings.

**Bug fixes**
- [x] #4538

## Related Issues

- [x] https://github.com/wazuh/wazuh-kibana-whitelabeling-customer1/issues/1
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/3892

### Global changes

- The plugin name (`wazuh`) is shown in the platform navigation drawer.
- The plugin name is used to build the URL.
- The index patterns (`wazuh-alerts-*`, `wazuh-monitoring-*`, `wazuh-statistics-*`)
- Programmatic navigation and redirects to `/app/wazuh`.
- Hard-coded `wazuh …` in the error messages shown by the App.
- The UI colors (light and dark themes)(background, accent)
- The fonts.

## 1st iteration

We'll focus on adapting the app to support white labeling in the first iteration. This means we'll provide mechanisms to upload and change the logos and text the app use as branding.

The changes related to the platform might stay out of this iteration, as we already use the built-in OpenSearch Dashboard custom branding settings for Wazuh. We need to find a way to easily enable/disable custom branding, resulting in no conflicts with the official branding.

### Final testing

We'll test the first iteration as a unit when every piece has been put together.
This effort will be track in the following issues:

- [x] #4801
- [x] #4802

**Comment by Desvelao** [comment]
# Customize the Wazuh dashboard

## Built-in customizations

Wazuh dashboard is based on OpenSearch Dashboards. This supports customization through settings.
Reference OpenSearch Dashboards customization: https://opensearch.org/docs/1.2/dashboards/branding/
Reference OpenSearch Dashboards security plugin settings: https://github.com/opensearch-project/security-dashboards-plugin/blob/1.2.0.0/server/index.ts#L20-L191

| Section | Setting |
| --------- | --------- |
| Browser tab title | `opensearchDashboards.branding.applicationTitle` |
| Favicon | `opensearchDashboards.branding.faviconUrl` |
| Login subtitle | `opensearch_security.basicauth.login.brandimage` |
| Branding mark | `opensearchDashboards.branding.mark.defaultUrl` |
| Branding mark (dark) | `opensearchDashboards.branding.mark.darkModeUrl` |
| Branding logo | `opensearchDashboards.branding.logo.defaultUrl` |
| Branding logo (dark) | `opensearchDashboards.branding.logo.darkModeUrl` |
| Branding loading | `opensearchDashboards.branding.loadingLogo.defaultUrl` |
| Branding loading (dark) | `opensearchDashboards.branding.loadingLogo.darkModeUrl` |
| Login logo | `opensearch_security.basicauth.brandimage` |
| Login title | `opensearch_security.basicauth.login.title` |
| Login subtitle | `opensearch_security.basicauth.login.subtitle` |

> Settings are working in Wazuh dashboard based on OpenSearch Dashboards 1.2.0

Screenshots:
![image](https://user-images.githubusercontent.com/34042064/187442227-fe419b99-c29d-4035-89ef-79f50e0677ec.png)
![image](https://user-images.githubusercontent.com/34042064/187442615-94cb4bf0-652d-4d22-8e63-9823f0fe04c0.png)
![image](https://user-images.githubusercontent.com/34042064/187442669-8d74a5cc-ab27-4a5d-bce7-6114503c0406.png)

# Desirable
> Custom branding-- login page
https://github.com/orgs/wazuh/teams/cicd is currently the owner of this section (platform). We need to design a way to customize this from our UI. If we need https://github.com/orgs/wazuh/teams/cicd to make changes, we will open the correspondent issues.

OpenSearch Dashboards doesn't support this. If we want those users can customize some settings, we have to create a new section to configure them and see a way for the new value/assets to be loaded instead of the default ones. We should evaluate if this is a necessary requirement.

**Comment by Desvelao** [comment]
# Customize the Wazuh plugin

Currently, the Wazuh plugin only supports some logo customizations.

# Identify the brand references
- :heavy_check_mark: plugin menu logo
- :heavy_check_mark: plugin health check logo
- :heavy_check_mark: plugin category logo (sidebar plugin platform menu)
- :heavy_check_mark: module PDF reports logo (sidebar plugin platform menu)
- Plugin
  - name
  - id ( URL: `/app/<plugin_id>`, redirections)
- Plugin category
  - name
  - id
- Reports
  - Header. Default: Wazuh contact info
  - Footer. Default: Wazuh copyright
- References to products: API, agents, manager/server, plugin platform
- Index patterns
- Templates
- Colors: UI and reports

> Legend
> :heavy_check_mark: currently supported

## Approach

- Add new settings to define new customizations
- Remove some unnecessary brand references replacing them with generic terms.

## Enhancements

- Let the user uploads the logo assets. With this change, we should remove the possibility to define the path where the assets are exposed. This is a *breaking change*. :exclamation:

**Comment by Desvelao** [comment]
# WIP

## Refactoring the plugin settings

I am centralizing the plugin settings definitions. These definitions are used by:
- generation of the initial/default plugin configuration file
- section `Settings/Configuration`

Both are improved to use the unique settings definition. This will simplify the additions of new settings related to this issue and future ones.

### Digging the implementation

The settings are defined with a specific structure as:

```ts
type TpluginSetting = {
	name: string
	description: string
	category: SettingCategory
	type: 'text' | 'boolean' | 'number' | 'array' | 'list' | 'interval'
	default: any
	configurableUI: boolean
	defaultHidden?: any
	requireRestart?: boolean
	requireReload?: boolean
	requireHealthCheck?: boolean
	params?: {
		options: {text: string, value: any}[]
	}
}

const pluginSettings : { [pluginSettingKey: string]: TpluginSetting } = {};
```
Plugin settings properties:
| Property | Description. |
| `name` | Define the text displayed in the UI. |
| `description` | Description. |
| `category` | Category. |
| `type` | Type of setting.  |
| `configurableUI` | This can be customized from the UI. |
| `default` |  Default value. |
| `defaultHidden` | Default hidden value. |
| `requireReload` | After changing this setting from the UI, a toast is displayed to reload the browser tab. |
| `requireRestart` | After changing this setting from the UI, a toast is displayed to restart the plugin platform. |
| `requireHealthCheck` | After changing this setting from the UI, a toast is displayed to redo the plugin health check. |
| `params` | Parameters to define the possible values. Currently used for lists of fixed values. This could be expanded. |


## Adding new plugin settings
- Added:
  - Reports header
  - Reports footer
  
## Removed deprecated code
Some files were removed because the centralization of the plugin settings definitions.

## Adaptions
Adapted:
- Generation of initial plugin configuration file
- `Settings/Configuration` section
  - Setting form
  - Search bar and filter by categories
- Removed unnecessary components: `Categories`

## Others minor fixes
- Fixed typos

**Comment by Desvelao** [comment]
# WIP - Enhancement of endpoint to update the plugin configuration

## Objective
- Support multiple settings to update instead of one. This reduces the number of requests done in the frontend. Moreover
- Add a layer of protection to the expected `body` parameters of the endpoint. This will help to prevent some misconfigurations. It requires the previous work of the plugin settings definition.

## TODO
- [ ] Refactor the frontend and backend to send/manage/support multiple setting configurations in the same request.
- [ ] Add the backend body validation

**Comment by Desvelao** [comment]
# WIP

**New requirement**
Enable or disable the application of the customization to the plugin.

| setting | type | description |
| --- | --- | --- |
| `customization.status` | boolean | Enable or disable the application of the customization. |

This setting lets to configure others' customization settings and disable the customization in the plugin without removing the custom values of these settings.

**Comment by AlexRuiz7** [comment]
## Integration process for the first iteration

- https://github.com/wazuh/wazuh-kibana-app/issues/4443
- https://github.com/wazuh/wazuh-kibana-app/issues/4450
  - Resolved by #4501 
- https://github.com/wazuh/wazuh-kibana-app/issues/4446
  - Resolved by #4503

These pull requests will be reviewed separately, but tested together as a unit into an integration branch. These pull request prepare the app for the white-labeling functionalities. We have named these 2 pull requests the **core**.

- https://github.com/wazuh/wazuh-kibana-app/issues/4434
  - Resolved by https://github.com/wazuh/wazuh-kibana-app/pull/4504
- https://github.com/wazuh/wazuh-kibana-app/issues/4426
  - Resolved by https://github.com/wazuh/wazuh-kibana-app/pull/4505
- https://github.com/wazuh/wazuh-kibana-app/issues/4506
  - Resolved by https://github.com/wazuh/wazuh-kibana-app/pull/4507

After that, the white-labeling specific pull requests will be reviewed, integrated and tested one by one into the integration branch. On each iteration, only the test cases from the integrated pull request will be executed. A full regression will be executed when everything is integrated, in order to verify that there are no bugs due to the integration.

Te QA flow, the pull requests dependencies and their order, have been graphically represented in the diagram below.

![white-labeling_QA_processdrawio](https://user-images.githubusercontent.com/15186973/195149954-cbbdcee3-4bf1-4265-a88d-4f5b38e6398a.png)

**Comment by AlexRuiz7** [comment]
First iteration is **done**

**Comment by AlexRuiz7** [comment]
Hello @ilyesm 

We have a [2nd iteration](https://github.com/wazuh/wazuh-dashboard/issues/20) currently in the backlog.

**Comment by ilyesm** [comment]
> Hello @ilyesm
> 
> We have a [2nd iteration](https://github.com/wazuh/wazuh-dashboard/issues/20) currently in the backlog.

Thanks, subscribed to that issue. Looking forward.
