### ISSUE TITLE
Custom branding: PDF reports

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4426]
## Description

As described in #4392, we need to add the ability to white-label the reports generated by the App.

![Screenshot from 2022-08-31 12-08-17](https://user-images.githubusercontent.com/15186973/187662862-7e795d81-81d2-49c2-8236-40ae04ad0a4d.png)

### Pre-conditions
- [x] #4434

### Tasks
- [x] (1) Use of custom logo in reports
- [x] (2) #3892 
- [x] (3) Use of custom copyright mark in reports

### Definitions
- _wazuh_logo_: Wazuh's original logo, as seen in the image.
- _custom_logo_: user chosen logo. By default, this logo will be a copy of _wazuh_logo_.

### Strategy
These 2 logos will live in the app's space simultaneously (the paths are yet to be defined). The app will always use the _custom_logo_. The following states and mutations are allowed:

- (S) **initial**: _custom_logo_ = _wazuh_logo_
- (M) **update**: _custom_logo_ overwritten with uploaded logo
- (M) **delete**: _custom_logo_ overwritten with _wazuh_logo_

**Depends on**: #4443

**Comment by Desvelao** [comment]
# Proposition

## Objective
The user should be able to customize the data displayed in the PDF reports related to:
  - the brand web link, email
  - copyright
  
# Implementation
Add settings to define the custom values and use them if these are defined.

We want to offer that the user can set anything and no limit to web, email or copyright. With this approach, we cover any use case. To do this, it is required to add new settings to the plugin.

Settings:
- `customization.reports.header`: define the text to display in the PDF report. See *point 2* in the screenshot of https://github.com/wazuh/wazuh-kibana-app/issues/4426#issue-1357101516.
  - configurable in the file
  - text

- `customization.reports.footer`: define the text to display in the PDF report. See point 3 in the screenshot of https://github.com/wazuh/wazuh-kibana-app/issues/4426#issue-1357101516.
  - configurable in the file
  - text

## TODO
- [ ] Create the new plugin setting definitions
- [ ] Adapt the PDF generating to use the custom plugin settings

**Comment by Desvelao** [comment]
# Daily work

I added the new settings and adapted the generation of PDF reports and work.

I think it will be interesting to support multiple lines. This requires changing the input ( and the input form in `Settings/Configuration` ) and see how the data is stored in the configuration file. I found some problems when the customs value contains new lines.

### TODO
- [ ] Fix the problem when using new lines in the custom value.

**Comment by Desvelao** [comment]
Should we support the option that some of these settings are empty and anything is displayed in the related section of the PDF?

**Comment by Desvelao** [comment]
# WIP

- Fixed a problem when using multiple lines in the value of the settings `cutomization.reports.footer` and `customization.reports.header` and saving the configuration from `Settings/Configuration`.

**Comment by Desvelao** [comment]
# Suggestion of enhancement

I was investigating the possibility to resize the customized image in the PDF reports.

It is possible to use the `fit` property. More information in https://pdfmake.github.io/docs/0.1/document-definition-object/images.

We could use it to avoid the custom image overlays to the text of the report.

**Comment by Desvelao** [comment]
# Update
- Added a character count limitation
