### ISSUE TITLE
Custom branding: assets upload

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4434]
# Description

In order to ease the white-label process to the user, file upload for images and logos needs to be implemented.

## Tasks

- [ ] (1) Design and implement backend endpoints to allow read/write operations for custom branding
- [ ] (2) Adapt the UI to allow the upload of images and icons.

We won't let the user select the name or folder of the file, just upload one, or reset to the original.

The tasks above might be elevated to issues, for the time being, this is what it's required:

1. GET, PUT & DELETE operations to read, upload and reset custom imagery. No files are created or removed, only read and overwritten. See the parent issue for details.
We need to be very careful with these endpoints in terms of security. The image must be validated in the backend (format and dimensions). Their names and paths must be decided beforehand, by the backend.

2. Replace the text inputs by [file pickers](https://elastic.github.io/eui/#/forms/form-controls#file-pickers) from the EUI framework. Validate the files in the frontend (format and dimensions). Send the files to the new endpoints.
![image](https://user-images.githubusercontent.com/15186973/187892475-b510e76a-c169-46aa-a220-740a0703b96f.png)

**Depends on**: #4443

**Comment by Desvelao** [comment]
## Proposition

The previous settings to customize the subpath where the assets were exposed in the plugin platform server are no longer necessary. So, we will eliminate these settings of the plugin configuration file.

### Desingn specifications

The configuration of these settings will be done in `Settings/Configuration`.

These settings will use a file picker to drag or select the file. It should validate the supported extensions of the input file (this could change in the future of the implementation).

If the setting is configurated, the image will be displayed and a button to remove it.

It is required to create new backend endpoints to manage the upload/remove the assets.

Due to the current implementation of `Settings/Configuration` and the requirement these settings should not be included in the configuration file, it is required to add the management how these settings are saved in the plugin.

Add the 

### TODO
- [ ] Define where the assets are saved. `<PLUGIN_PATH>/assets/custom/<type>`. For the images, `<type>` is `images`
- [ ] Remove the settings related to the logo customizations from the plugin configuration file.
  - [ ] Compose plugin configuration with these values. This affects to get the plugin configuration in the frontend and backend service.
- [ ] Create the new setting configuration input component. Use a file picker.
  When it is configurated, it displays:
  - [ ] image
  - [ ] button to remove
- [ ] Backend endpoints to manage the upload/remove asset:
  - [ ] Upload
  - [ ] Remove
- [ ] Create a new logic to save these settings from the frontend.
- [ ] Add the supported format
- [ ] Add the suggested image dimensions if required

**Comment by Desvelao** [comment]
### Implementation - Composed plugin settings configuration details

Due to the settings to define the logo customization will be removed and we want to support multiple extensions. The plugin (frontend and backend) should know what asset should use, so it is required the frontend have a way to retrieve this information. An approach is that this data would be returned in the same endpoint that returns the plugin configuration `GET /utils/configuration`, but to do this, we need to merge:
- settings defined in the plugin configuration file
- custom logo assets stored in the expected path

These changes will be implemented in the `getConfiguration` backend service, used in the backend, and the mentioned route to get the plugin configuration.

**Comment by Desvelao** [comment]
## Specifications of endpoints to manage the assets

target path: `<PLUGIN_PATH>/assets/custom/images/<setting>*`

> We should research if it possible store the custom assets in a path not affected when update/changing the plugin. For example: `<PLUGIN_PLATFORM_PATH>/data/wazuh/assets`. This requires exposing this directory (research if this is possible).

### Upload

Route: ```PUT /utils/configuration/files/<setting>```
Requirements:
- authenticated user (if the plugin platform security is enabled)
- valid API token
- `administrator` API role
Body: 
- `file`: <buffer>
Action:
- Remove all the files related to the same setting in the target path
- Save the file in the target path.

### Remove

Route: ```DELETE /utils/configuration/files/<setting>```
Requirements:
- authenticated user (if the plugin platform security is enabled)
- valid API token
- `administrator` API role
Action:
- Remove the files stored in the target path. Remove all the files whose name starts with the value of `<setting>`. In this way, we are sure we remove all the related files to the same setting.

**Comment by Desvelao** [comment]
WIP

## Input form to customize the logo

Tasks done:
- Create a file picker input and adapt it to use the new plugin settings definition
- Display the custom logo if it is set
- Add a button and confirmation prompt to remove the custom image

**Screenshots**
- Setting configuration using a file picker
![image](https://user-images.githubusercontent.com/34042064/188816094-2bf8af16-ea43-4068-bb1c-3e9d97bd3f68.png)
- When there is a custom image set
![image](https://user-images.githubusercontent.com/34042064/188819407-1248f70d-56c0-4b15-b93c-ccf3933b1839.png)
- Hovering the remove icon
![image](https://user-images.githubusercontent.com/34042064/188819639-d989cb38-2aa7-4d9c-889b-ae63de6c30b3.png)
- Confirmation to remove the custom image
![image](https://user-images.githubusercontent.com/34042064/188819747-8f49daec-981b-441a-af58-93a02230d2fe.png)

**Comment by Desvelao** [comment]
## WIP

Changes:

- Removed the composition of settings. Now all the settings are retrieved from the configuration file.
- Adapted the endpoints to validate the parameters

**Comment by Desvelao** [comment]
# WIP

- Refactor the input components to be reusable.
- Uncouple custom rendering of displaying an image and button when the setting is set.

**Comment by AlexRuiz7** [comment]
> * UI preview when custom images are set
> 
> ![image](https://user-images.githubusercontent.com/34042064/188819407-1248f70d-56c0-4b15-b93c-ccf3933b1839.png)

Question: can the remove button be removed?? The file picker already has an option to remove the file, if it works, then the remove button is redundant.

**Comment by Desvelao** [comment]
> > * UI preview when custom images are set
> > 
> > ![image](https://user-images.githubusercontent.com/34042064/188819407-1248f70d-56c0-4b15-b93c-ccf3933b1839.png)
> 
> **Question**: can the remove button be removed?? The file picker already has an option to remove the file, if it works, then the remove button is redundant.

The button to `Remove` the file from the file picker only appear if there is a selected file. If the setting is set, and the user goes to `Settings/Configuration`, the file picker has no selected file, it is empty.

**Comment by Desvelao** [comment]
# Changes
- If there are selected files in the file picker inputs, and saving the configuration, the file picker inputs will be cleaned.

**Comment by Desvelao** [comment]
# Limit the size of the uploaded file

We can limit the maximum size of the uploaded file by defining the `options.body.maxBytes` route property.

```ts
router.put(
    {
      path: '/utils/configuration/files/{key}',
      validate: valdiation,
      options: {
        body: {
          maxBytes: <MAXIMUM_BYTES_PAYLOAD_UPLOAD_CUSTOM_FILE>,
        },
      }
    },
    handler
  );
```

Information about the options route: https://github.com/elastic/kibana/blob/v7.10.2/src/core/server/http/router/route.ts#L81-L86

But the user can define a global value for using `server.maxPayload` (Kibana 7.10.2). Default: `1048576`.

Do we want to set this value for the endpoint to upload the custom images? What value in bytes?

**Comment by Desvelao** [comment]
# New requirement

- [ ] Limit the maximum body size to upload files to 1MB

**Comment by AlexRuiz7** [comment]
> # Changes
> ## Frontend
> * Add size validation of the selected file of the file picker
>   ![image](https://user-images.githubusercontent.com/34042064/191942571-236591c5-455c-4af9-9b4a-e059b992bc65.png)
> 
> ## Backend
> * Add size validation of the request payload size.
>   exclamation The endpoint receives more information than the file, so its value limits the total size. This difference does that the frontend validates successfully a file whose size is the same or near to the limit, and when saving the configuration, the backend throws a validation error.

Can the unit be megabytes, or at least kilobytes?

**Comment by Desvelao** [comment]
> > ### Changes
> > #### Frontend
> > 
> > * Add size validation of the selected file of the file picker
> >   ![image](https://user-images.githubusercontent.com/34042064/191942571-236591c5-455c-4af9-9b4a-e059b992bc65.png)
> > 
> > #### Backend
> > 
> > * Add size validation of the request payload size.
> >   exclamation The endpoint receives more information than the file, so its value limits the total size. This difference does that the frontend validates successfully a file whose size is the same or near to the limit, and when saving the configuration, the backend throws a validation error.
> 
> Can the unit be megabytes, or at least kilobytes?

I added a service to format the value to a meaningful unit.

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/192202850-d38c0396-1806-457a-92a6-955c9f528b2f.png)

**Comment by Desvelao** [comment]
> 't used an SVG file to PDF logo
The `customization.logo.reports` setting can not be use a SVG image.
