### ISSUE TITLE
Custom branding: centralize the plugin's settings

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#4443]
## Description
The settings of the app are currently distributed in different files, and there are some repetitive tasks and bad practices. Adding a new setting has a high cost in development time.

## Goal

- Centralize the definition of the plugin's settings, so every side of the app reads the settings from the same source.
- Reduce the future cost, in time, to add or remove plugin settings.

## Tasks

- [x] Define a schema of properties to manage the current plugin logic
- [x] Adapt the affected sections of the plugin to use the new plugin setting definition, dynamically.
  - [x] Default configuration file
  - [x] Configuration in `Settings/Configuration`
- [x] Refactor the form
- [x] Create new hooks to manage the form state
- [x] Refactor the input components to do them uncontrolled.
- [x] Sort the plugin setting categories
- [x] Add description to category.
- [x] Tests
  - [x] Default configuration file
  - [x] `useForm` hook
  - [x] `InputForm` component

**Comment by Desvelao** [comment]
# WIP - Refactoring the plugin settings

I am centralizing the plugin settings definitions. These definitions are used by:
- generation of the initial/default plugin configuration file
- section `Settings/Configuration`

Both are improved to use the unique settings definition. This will simplify the additions of new settings related to this issue and future ones.

### Objective

- Reduce, and simplify the time to add/remove a new setting. This will reduce the cost of time when it is required to add new settings or remove some that are deprecated.
- Define properties of the plugin that reacts dynamically.
> For example, the setting can be defined in the configuration file:
> - It is included in the initial configuration file. Adapts the logic to generate it dynamically.
> - Stored in the configuration file when it is updated in `Settings/Configuration`
> See the setting properties for more information.

### Digging the implementation

The settings are defined with a specific structure as:

```ts
type TpluginSetting = {
	name: string
	description: string
	category: SettingCategory
	type: 'text' | 'boolean' | 'number' | 'array' | 'list' | 'interval'
	default: any
	configurableUI: boolean
	defaultHidden?: any
	requireRestart?: boolean
	requireReload?: boolean
	requireHealthCheck?: boolean
	params?: {
		options: {text: string, value: any}[]
	}
}

const pluginSettings : { [pluginSettingKey: string]: TpluginSetting } = {};
```
Plugin settings properties:
| Property | Definition |
| ---- | ---- |
| `name` | Define the text displayed in the UI. |
| `description` | Description. |
| `category` | Category. |
| `type` | Type of setting.  |
| `configurableUI` | This can be customized from the UI. |
| `default` |  Default value. |
| `defaultHidden` | Default hidden value. |
| `requireReload` | After changing this setting from the UI, a toast is displayed to reload the browser tab. |
| `requireRestart` | After changing this setting from the UI, a toast is displayed to restart the plugin platform. |
| `requireHealthCheck` | After changing this setting from the UI, a toast is displayed to redo the plugin health check. |
| `params` | Parameters to define the possible values. Currently used for lists of fixed values. This could be expanded. |


## Adding new plugin settings
- Added:
  - Reports header
  - Reports footer
  
## Removed deprecated code
Some files were removed because of the centralization of the plugin settings definitions.

## Adaptions
Adapted:
- Generation of initial plugin configuration file
- `Settings/Configuration` section
  - Setting form
  - Search bar and filter by categories
- Removed unnecessary components: `Categories`

## Others minor fixes
- Fixed typos

**Comment by Desvelao** [comment]
# WIP

- Refactored the `validationOptions` to `validate`
- Add new properties to manage how to store the assets:
  - Define the relative target path of the plugin where the file will be stored
  - Define the target filename
  - Define the resolved URL exposed

**Comment by Desvelao** [comment]
# WIP

- Add new `options` type related to the `editor` input form.

**Comment by Desvelao** [comment]
# WIP

- Add new setting property
| property | required | description |
| --- | --- | --- |
| `transformUIInputValue` | optional | It transforms the value of the input HTML element |

This setting helps to transform the expected value for the settings of type `switch` whose possible values are: `true` or `""` that don't match with the current requirements of `true`/`false`.

**Comment by Desvelao** [comment]
Due to a requirement for a new feature, it is required to refactor the form and input components to the state that is controlled in the form component.

Tasks:
- [ ] Refactor the form
- [ ] Create new hooks to manage the form state
- [ ] Refactor the input components to do them uncontrolled.

**Comment by Desvelao** [comment]
# Changes
- Add tests for:
  - `useForm` hook
  - `/utils/*` API endpoints
  - default configuration file
  - `InputForm` component
