### ISSUE TITLE
Automation Test Plan Design for Add Agent feature

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4485]
## Introduction

In this issue, we will track all the efforts being made to increase coverage of the "Add Agent" component on all the supported platforms. The test plan described here comprehends the automated tests which will be added to test the component. The complete tests suite will be run as part of our automated testing process.

Platforms:
- Elastic 7.16.3
- Elastic 7.17.5
- Wazuh Dashboard 1.2.0
- OpenDistro 1.13.1

## Plan

- [ ] #3997  Validate the information to add a new Agent Red Hat / CentOS SO from CentOS5 version with i386 architecture

- [ ] #3998 Validate the information to add a new Agent Red Hat / CentOS SO from CentOS6 or higher with i386 architecture

- [ ] #3999 Validate the information to add a new Agent Red Hat / CentOS SO from CentOS5 and x84_64 architecture

- [ ] #4000 Validate the information to add a new Agent Red Hat / CentOS SO from CentOS6 or higher version with x84_64 architecture

- [ ] #4001 Validate the information to add a new Agent Red Hat / CentOS SO from CentOS6 or higher version with armhf architecture

- [ ] #4002 Validate the information to add a new Agent Red Hat / CentOS SO from CentOS6 or higher version with aarch64 architecture

- [ ] #4003 Validate the information to add a new Agent Debian / Ubuntu SO version with i386 architecture

- [ ] #4004 Validate the information to add a new Agent Debian / Ubuntu SO version with x86_64 architecture

- [ ] #4005 Validate the information to add a new Agent Debian / Ubuntu SO version with armhf architecture

- [ ] #4006 Validate the information to add a new Agent Debian / Ubuntu SO version with aarch64 architecture

- [ ] #4007 Validate the information to add a new Agent Choose the version windows

- [ ] #4008 Validate the information to add a new Agent Choose the version "MacOs"

**Comment by gdiazlo** [comment]
Closing. This page is in a redesign process, and a new plan must be created after that.
