### ISSUE TITLE
Automated - Test Plan - Fixes after migrate cypress project

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4488]
In this issue, we will track all the efforts to fix the automation test cases that were broken after the cypress project migration to Wazuh-Kibana-app repository.

There are broken test cases for different platforms

<details>
<summary>
Broken test for Wazuh Dashboards
</summary>

![screencapture-file-home-mauri-repo-kibana-app-wazuh-kibana-app-test-cypress-cypress-report-output-html-2022-09-09-14_16_09 (1)](https://user-images.githubusercontent.com/104914131/189416376-7415c502-2d18-4b53-a8c7-608dcf308d8d.png)

</details>

<details>
<summary>
Broken test for Kibana (Xpack plugin) - Pending to update screenshot
</summary>

[Kibana - excecution.pdf](https://github.com/wazuh/wazuh-kibana-app/files/9538351/Kibana.-.excecution.pdf)

</details> 

This issue will be closed when all the related issues are closed and merged

## Tasks

- [x] Perform a completed test execution on Kibana 7.16.3 (Xpack Plugin) to track the failing test cases
- [x] Add the report to the track issue
- [x] [WZD - Test Fix - Validate that the added filter label is removed after click remove filter option Dashboard](https://github.com/wazuh/wazuh-kibana-app/issues/4499)
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4494
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4518 
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4513
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4489
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4527
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4530
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4545
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4555
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4559
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4518 
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4513  
- [x] https://github.com/wazuh/wazuh-kibana-app/pull/4496 
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4560
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4550
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4568

Acceptance criteria: This issue will be considered closed when all the linked tasks are closed and a complete test execution has been carried out in each environment, obtaining a percentage of passed test cases of 100%.
In the case that an error is detected, the error bug issue should be linked to the corresponding task

**Comment by mauceballos** [comment]
Delete task 
- [ ] WZD - Test Fix - add Configuration to modules
- [ ] WZD - Test Fix - Add/Delete sample data to modules

### Test

<details>
<summary>
these features are working 
</summary>

![Screenshot from 2022-09-12 12-20-47](https://user-images.githubusercontent.com/76791841/189694998-6100f8cd-a937-4b51-9689-c50b19385492.png)


</details>

**Comment by mauceballos** [comment]
<details>
<summary>
test Suite execution on wzd
</summary>

![Image](https://user-images.githubusercontent.com/76791841/190200412-644229a0-49e8-4f09-a9a0-f8ea2a47bc04.png)

</details>

<details>
<summary>
failed tests </summary>



![Image](https://user-images.githubusercontent.com/76791841/190200784-54e5bab7-edfc-44e0-be99-bb85e51ff275.png)



</details>

**Comment by Mayons95** [comment]
Kibana - Xpack - Should Displayes a message to restart the cluster after saves -Validate creation message is displayed after creating a new decoder 
Test it's not broken on Kibana
![image](https://user-images.githubusercontent.com/104914131/190250635-55ec779b-4096-4e8a-ab80-3314e6380383.png)

Neither on WZD:
![image](https://user-images.githubusercontent.com/104914131/190250896-51c80b17-f3e4-4f6e-8f8c-90a6d4d841f2.png)

Task will be deleted from the Epic: 
- [ ] Kibana - Xpack - Should Displayes a message to restart the cluster after saves -Validate creation message is displayed after creating a new decoder :clock1:

**Comment by Mayons95** [comment]
Kibana - Xpack - Should Displayes a message to restart the cluster after saves -Validate creation message is displayed after creating a new decoder 
Test it's not broken on Kibana
<details>

![image](https://user-images.githubusercontent.com/104914131/190251522-d41fdda7-ebd3-4d00-8d8e-f3829ccc0662.png)

</details>


Task will be deleted from the Epic: 

- [ ] Kibana - Xpack - Should Displayes a warning modal - Management - edit decoders

**Comment by mauceballos** [comment]
Add WZD - remove filter from mudole dashboard

**Comment by mauceballos** [comment]
Add WZD - configuration

**Comment by mauceballos** [comment]
Delete - [ ] WZD - Feature - Access to configuration

**Comment by mauceballos** [comment]
Add WZD - Feature-Sample data

**Comment by mauceballos** [comment]
Doing an execution and investigating the failure of the " Kibana - Xpack - add Configuration to modules".

**Comment by mauceballos** [comment]
Doing an execution and investigating the failure of the "Kibana - Xpack - disable modules - Disable modules, VirusTotal".

**Comment by Mayons95** [comment]
Test for create a new rule was fixed by PR https://github.com/wazuh/wazuh-kibana-app/pull/4496
![image](https://user-images.githubusercontent.com/104914131/191515753-8d74d9f0-00f7-4401-bbf8-5689e3305f81.png)

**Comment by Mayons95** [comment]
Automated test suite for WZD executed with success
<details>

![Screenshot from 2022-09-21 11-48-28](https://user-images.githubusercontent.com/104914131/191537196-cc0e9d4f-93fe-45fb-ac73-d2496fe9807d.png)

![Screenshot from 2022-09-21 11-48-15](https://user-images.githubusercontent.com/104914131/191537206-d8a6ba71-4a04-4590-a5e3-528cb96f2c49.png)

</details>

**Comment by mauceballos** [comment]
##Acceptance criteria:

- [ ] Perform a completed test execution successfully on Kibana (Xpack Plugin)
- [ ] Perform a completed test execution successfully on WZD
