### ISSUE TITLE
Kibana - Release 4.3.8 - Release Candidate 1 - Testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4535]
## Description

We need to test the app packages for the upcoming version of Wazuh 4.3.8.

## Tasks

- [x] Smoke test - Kibana 7.10.2 ODFE 
- [x] Smoke test - Kibana 7.10.2 Xpack
- [x] Smoke test - Kibana 7.16.0 Xpack
- [x] Smoke test - Kibana 7.16.1 Xpack
- [x] Smoke test - Kibana 7.16.2 Xpack
- [x] Smoke test - Kibana 7.16.3 Xpack
- [x] Smoke test - Kibana 7.17.0 Xpack
- [x] Smoke test - Kibana 7.17.1 Xpack
- [x] Smoke test - Kibana 7.17.2 Xpack
- [x] Smoke test - Kibana 7.17.3 Xpack
- [x] Smoke test - Kibana 7.17.4 Xpack
- [x] Smoke test - Kibana 7.17.5 Xpack
- [x] Smoke test - Wazuh Dashboard 4.3.8

**Comment by AlexRuiz7** [comment]
We performed with @mauceballos the manual test for the marked packages with out problems.
WZD it's pending to have a working environment to test.

_Originally posted by @Mayons95 in https://github.com/wazuh/wazuh-kibana-app/issues/4462#issuecomment-1246756206_

**Comment by AlexRuiz7** [comment]
Test OK for Wazuh Dashboard - Test with OSD Environment


![Image](https://user-images.githubusercontent.com/104914131/190196270-48aff303-95d1-4f78-aefb-3856d9bb6de5.png)

_Originally posted by @Mayons95 in https://github.com/wazuh/wazuh-kibana-app/issues/4462#issuecomment-1246932599_
