### ISSUE TITLE
Automated - Test Plan - Add increased coverage for Rules modules

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4578]
In this issue, we will track all the efforts to increase the coverage of the automation test cases for the Rules module.
Perhaps, we add other test cases to increase the coverage elsewhere in the App.
In these test cases, they are normally executed manually by those that will be added to be automated.
Also, all test cases added should be executed successfully on the Wzd and Xpack environments.

## Tasks

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4593
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4613
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4636
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4648
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4600
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4627
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4709
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4721
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4676
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4736
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4745

</details>

**Comment by Mayons95** [comment]
Automated status for Wazuh Dashboard
<details>

[Mochawesome Report.pdf](https://github.com/wazuh/wazuh-kibana-app/files/9779612/Mochawesome.Report.pdf)

</details>

**Comment by Mayons95** [comment]
Automated status for Kibana
<details>

[Kibana-report.pdf](https://github.com/wazuh/wazuh-kibana-app/files/9823097/Kibana-report.pdf)


</details>

**Comment by Mayons95** [comment]
Added a bug related to generate reports test cases

**Comment by Mayons95** [comment]
Wazuh dashboard login problem persisted after fix implementation

![image](https://user-images.githubusercontent.com/104914131/197840329-109caf08-b93d-4535-a003-4dca4c2981f6.png)

**Comment by Mayons95** [comment]
I closed this issue seeing the development task are closed and merged
