### ISSUE TITLE
Development tooling review & update

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4579]
## Description

There are several development tools included in our repository, however, due to lack of regular maintenance, they are long outdated and unused.

These tools are key to enforce the code conventions defined by the team, in the [Styleguide.md](https://github.com/wazuh/wazuh-kibana-app/blob/master/STYLEGUIDE.md), and maintain the quality of our code, which directly translates into product's quality.

We need not only to review the existing tools and their configurations, but also review our Styleguide, in order to identify and fix any contradiction. Our Styleguide must be based on the [OpenSearch Dashboards' Developer Guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md).

### Tasks

- [x] Review our Styleguide, and compare it with the [OpenSearch Dashboards' Developer Guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md).
- [x] Review our development tools, and compare their versions and configuration with OpenSearch Dashboards'.
- [x] Update our tooling and their configurations.
- [ ] Make an analysis of the files listed in the OpenSearch Dashboards repo, providing a brief summary of what it does, and which tool it's related to. Example: tsconfig.json: Configuration file for TypeScript.

--------------------

### Subtasks

- [x] Update ESLint configuration.
- [x] Update Prettier configuration.
- [x] Include ESLint plugin to check filenames and folder names.
- [x] Include default VS Code workspace settings and recommended extensions.
- [ ] #4665
- [ ] #4681

**Comment by yenienserrano** [comment]
It was decided to separate the eslint from the Kibana/Opensearch Dashboard application to have more control of the styles we want to give to our application.

On the other hand, we also want to have some Visual Studio Code configurations in the project so that just by cloning the repo and opening it in Visual Studio Code, it already has a standard configuration.

**Comment by AlexRuiz7** [comment]
A new ESLint plugin to ensure the application of filenames and folder names conventions has been added in https://github.com/wazuh/wazuh-kibana-app/pull/4640/commits/f3dbcc420303535c26b0553a268fc1ee1a670969

[ESLint plugin filenames simple](https://github.com/epaew/eslint-plugin-filenames-simple)

**Comment by AlexRuiz7** [comment]
We are also investigating how to include git hooks to our repository to perform some validations, such as:

- The commit message follows our [convention](https://docs.google.com/document/d/1is25b8r2CpBZ_1SQWCkWaXiXzdTrwd_IHd21gWJHsN0/edit#heading=h.ld5rqhrpscm4), based on [5.2 Distributed Git - Contributing to a Project](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project)
- The commit is properly [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [Optional] Run ESLint on commit --> using GitHub Actions for this requirement looks like a better approach. In fact, GitHub provides this functionality out-of-the-box now, [check this](https://github.com/stefanoeb/eslint-action).

**Comment by AlexRuiz7** [comment]
Recommended extensions for this project has been added in https://github.com/wazuh/wazuh-kibana-app/pull/4640/commits/1219141b73322977556c49e31e01b6239adf7200

![image](https://user-images.githubusercontent.com/15186973/194330253-f7a0d5e1-0e4d-485f-b4da-2b2c0c293e59.png)

**Comment by yenienserrano** [comment]
ESLint and Prettier versions were upgraded to a more current version of the OpenSearch Dashboards versions.

| ---------------------------------- | ESLint    | Prettier |
| ---------------------------------- | ----------- | ---------- |
| OpenSearch Dashboard   | "^6.8.0"  | "^2.1.1" |
| Wazuh                               | "^8.24.0"| "^2.7.1" |

**Comment by AlexRuiz7** [comment]
As we provide support for Kibana 7.10.2 (due to OpenDistro), the configurations for plugins for ESLint and Prettier were causing our workflows for unit testing to fail, as their versions required a newer version of NodeJS than 10.23, which is the one used in Kibana 7.10.2.

For this reason, we have created 3 pull requests, for Kibana 7.10.2, Kibana 7.16.x and OpenSearch Dashboards 2.3.x, with their respective configurations according to the NodeJS versions they use.
