### ISSUE TITLE
Kibana - Release 4.3.9 - Release Candidate 1 - Testing

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4645]
## Description

Issue created to track the effort to perform a smoke test on Kibana packages for Wazuh 4.3.9.
We are waiting for the packages to start the test

## Tasks

- [x] Smoke test - Wazuh Dashboard 4.3.9
- [x] Smoke test - Kibana 7.17.6 Xpack
- [x] Smoke test - Kibana 7.17.5 Xpack
- [x] Smoke test - Kibana 7.17.4 Xpack
- [x] Smoke test - Kibana 7.16.3 Xpack
- [x] Smoke test - Kibana 7.10.2 ODFE

**Comment by mauceballos** [comment]
Smoke test 
<details>
<summary>7.17.4</summary



</details>

**Comment by mauceballos** [comment]
Smoke test 
<details>
<summary>7.17.6</summary

![2022-10-06_13-26](https://user-images.githubusercontent.com/76791841/194368875-e5d960bc-3338-4389-91a7-168a6092b2ac.png)
![2022-10-06_13-27](https://user-images.githubusercontent.com/76791841/194368900-7cb40902-2df4-4bb5-a045-b5d06ddd3963.png)
![2022-10-06_13-31](https://user-images.githubusercontent.com/76791841/194368933-c086522a-1090-400b-a138-49b5c52d16ac.png)



</details>

**Comment by Machi3mfl** [comment]
## Smoke test `7.17.5`

![image](https://user-images.githubusercontent.com/6089438/194374038-544c13ba-81bd-45cd-b748-bf6fa3e7ad50.png)

![image](https://user-images.githubusercontent.com/6089438/194374119-ee3e7d49-a6aa-4ecc-8288-dfbc08e18647.png)

![image](https://user-images.githubusercontent.com/6089438/194374249-d88dfb61-c497-49c7-99cc-1410b943915d.png)

**Comment by AlexRuiz7** [comment]
Smoke test for Wazuh Dashboard 1.2.0

<details>

![image](https://user-images.githubusercontent.com/15186973/194380145-5d76628f-4680-40c3-b729-722430307f21.png)

![image](https://user-images.githubusercontent.com/15186973/194380225-bb8bf4ed-16f0-47c2-b418-baaec78b42cf.png)

![image](https://user-images.githubusercontent.com/15186973/194380268-bb07fb63-5aa2-453a-bb46-6b2b777ea1ff.png)


</details>

**Comment by Desvelao** [comment]
I fixed a problem with the `revision` in the `v4.3.9-7.10.2` tag and rebuilt the package.

<details>
![image](https://user-images.githubusercontent.com/34042064/194889531-3eebf418-aede-49bf-a4a1-c2ef33f47332.png)
![image](https://user-images.githubusercontent.com/34042064/194889305-86e40ef7-7d50-476e-acf3-59acbeb52880.png)
![image](https://user-images.githubusercontent.com/34042064/194889619-245d6516-4991-4284-b23f-4b2f88280803.png)
![image](https://user-images.githubusercontent.com/34042064/194889684-ad5be607-2759-41d7-aa95-1a9ff458cc77.png)

</details>
