### ISSUE TITLE
Kibana/WzD - Release 4.3.9 - Release Candidate 1- Testing

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4646]
## Description

We need to test the app packages for the upcoming version of Wazuh 4.3.9.

## Tasks

- [ ] Smoke test - Splunk 8.2.8 
- [ ] Smoke test - Splunk 8.2.7
- [ ] Smoke test - Splunk 8.2.6
- [ ] Smoke test - Splunk 8.1.10
- [ ] Smoke test - Splunk 8.1.7
- [ ] Smoke test - Splunk 8.1.4

**Comment by mauceballos** [comment]
Smoke test 
<details>
<summary>8.1.4</summary

![2022-10-06_10-54](https://user-images.githubusercontent.com/76791841/194332100-7342c2f3-ec68-4a78-92eb-f71cd056ea15.png)
![2022-10-06_10-53](https://user-images.githubusercontent.com/76791841/194332115-37c034ee-4762-400a-90ac-d6e8410f1799.png)

</details>

**Comment by AlexRuiz7** [comment]
Duplicated https://github.com/wazuh/wazuh-kibana-app/issues/4645
