### ISSUE TITLE
Enhance the unit test action

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#4662]
## Description

The `wazuh-unit-test` GitHub action is limited to running in a specific environment (Kibana 7.10.2) and this could give problems in plugins for other Kibana versions, moreover, the action can not run for plugin compatibles with OpenSearch Dashboards.

## Tasks
- [x] Use the images hosted on quay.com
- [x] Support run the action for plugin compatibles with OpenSearch Dashboards
- [x] Allow the action can run on:
  - [x] pull request
  - [x] dispatch

**Comment by Desvelao** [comment]
# Update

I am extending the reusable workflow to build a plugin package on demand.

Others changes:

- Add a comment with the test coverage of unit tests on pull requests.
