### ISSUE TITLE
List key files to save for Wazuh backup

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-kibana-app#4671]
According to this issue  [The upgrade guide should mention which files to back up #2979 ](https://github.com/wazuh/wazuh-documentation/issues/2979), we are adding to the Wazuh documentation a section on making a backup of the Wazuh installation. This backup may be useful for example to those users willing to move their current installation to another system.

It's necessary then, a list of key files that must be kept in a backup and which are useful to restore the installation without losing data and configurations.

The components that should be considered are:
- Wazuh indexer 
- Wazuh dashboard
- Open Distro
- Kibana and Wazuh plugin

A draft of the new documentation section can be seen here:
- [Wazuh files backup](https://documentation-dev.wazuh.com/2979-files-to-backup/user-manual/files-backup/index.html)

**Comment by Desvelao** [comment]
# Wazuh indexer

##  Data
| Entity | Description |
| --- | --- |
| Indices | The data relating to indices could be stored in the snapshot that can be restored in the target. This can help: https://opensearch.org/docs/1.2/opensearch/snapshot-restore/ , https://wazuh.com/blog/index-backup-management/ (see the section related to OpenDistro for Elasticsearch). |


## Configuration
| Entity | Folder/File  |
| --- | --- |
| Configuration folder (package) | `/etc/wazuh-indexer` |
| Configuration file (package) | `/etc/wazuh-indexer/opensearch.yml` |
| Configuration keystore (package) | `/etc/wazuh-indexer/opensearch.keystore` |
| Certificates ([Wazuh installation guides](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#deploying-certificates)) | `/etc/wazuh-indexer/certs` |
| Configuration folder (Docker) | `/usr/share/wazuh-indexer/config` |
| Configuration file (Docker) | `/usr/share/wazuh-indexer/config/opensearch.yml` |
| Configuration keystore (Docker) | `/usr/share/wazuh-indexer/config/opensearch.keystore` |
| Configuration folder (alternative installation) | The configuration directory ( `$OS_PATH_CONF`). |
| Certificates | All the certificates used in the configuration. |

# Elasticsearch

##  Data
| Entity | Description |
| --- | --- |
| Indices | The data relating to indices could be stored in the snapshot that can be restored in the target. This can help: https://wazuh.com/blog/index-backup-management/ (see the section related to Elasticsearch). |

## Configuration
Backup configuration files: https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-take-snapshot.html#back-up-config-files.

| Entity | Folder/File  |
| --- | --- |
| Configuration folder (package) | `/etc/elasticsearch` |
| Configuration file (package) | `/etc/elasticsearch/elasticsearch.yml` |
| Configuration keystore (package) | `/etc/elasticsearch/elasticsearch.keystore` |
| Certificates ([Wazuh installation guides](https://documentation.wazuh.com/current/deployment-options/elastic-stack/all-in-one-deployment/index.html#certificates-creation-and-deployment)) | `/etc/elasticsearch/certs` |
| Configuration folder (Docker) | `/usr/share/elasticsearch/config` |
| Configuration file (Docker) | `/usr/share/elasticsearch/config/elasticsearch.yml` |
| Configuration keystore (Docker) | `/usr/share/elasticsearch/config/elasticsearch.keystore` |
| Configuration folder (alternative installation) | The configuration directory ( `$ES_PATH_CONF`). |
| Certificates | All the certificates used in the configuration. |
  
# Elasticsearch with Open Distro for Elasticsearch

##  Data
| Entity | Description |
| --- | --- |
| Indices | The data relating to indices could be stored in the snapshot that can be restored in the target. This can help: https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/snapshot-restore/ https://wazuh.com/blog/index-backup-management/ (see the section related to OpenDistro for Elasticsearch). |

## Configuration
Backup configuration files: https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-take-snapshot.html#back-up-config-files.

| Entity | Folder/File  |
| --- | --- |
| Configuration folder (package) | `/etc/elasticsearch` |
| Configuration file (package) | `/etc/elasticsearch/elasticsearch.yml` |
| Configuration keystore (package) | `/etc/elasticsearch/elasticsearch.keystore` |
| Certificates ([Wazuh installation guides](https://documentation.wazuh.com/current/deployment-options/elastic-stack/all-in-one-deployment/index.html#certificates-creation-and-deployment)) | `/etc/elasticsearch/certs` |
| Configuration folder (Docker) | `/usr/share/elasticsearch/config` |
| Configuration file (Docker) | `/usr/share/elasticsearch/config/elasticsearch.yml` |
| Configuration keystore (Docker) | `/usr/share/elasticsearch/config/elasticsearch.keystore` |
| Certificates (Wazuh installation guides) | `/usr/share/elasticsearch/config/certs` |
| Configuration folder (alternative installation) | The configuration directory ( `$ES_PATH_CONF`). |
| Certificates | All the certificates used in the configuration. |
| Initial configuration (config.yml) | `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml` |
| Initial configuration (internal_users.yml) | `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml` |
| Initial configuration (roles.yml) | `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml` |
| Initial configuration (roles_mapping.yml) | `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml`  |
| Initial configuration (action_groups.yml) | `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml` |
  
# Wazuh dashboard

## Configuration
| Entity | Folder/File  |
| --- | --- |
| Configuration folder (package) | `/etc/wazuh-dashboard` | 
| Configuration file (package) | `/etc/wazuh-dashboard/opensearch_dashboards.yml` |
| Configuration keystore (package) | `/etc/wazuh-dashboard/opensearch_dashboards.keystore` |
| Configuration `node.options` (package) | `/etc/wazuh-dashboard/node.options` |
| Certificates ([Wazuh installation guide](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#deploying-certificates)) | `/etc/wazuh-dashboard/certs` |
| Configuration folder (Docker) | `/usr/share/wazuh-dashboard/config` | 
| Configuration file (Docker) | `/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml` |
| Configuration keystore (Docker) | `/usr/share/wazuh-dashboard/config/opensearch_dashboards.keystore` |
| Configuration `node.options` (Docker) | `/usr/share/wazuh-dashboard/config/node.options` |
| Certificates (Docker) | `/usr/share/wazuh-dashboard/certs ` |
| Wazuh plugin data | `/usr/share/wazuh-dashboard/data/wazuh` |
| Certificates | All the certificates used in the configuration. |

# Kibana

## Configuration
| Entity | Folder/File  |
| --- | --- |
| Configuration folder (package) | `/etc/kibana` | 
| Configuration file (package) | `/etc/kibana/opensearch_dashboards.yml` |
| Configuration keystore (package) | `/etc/kibana/opensearch_dashboards.keystore` |
| Configuration `node.options` (package) | `/etc/kibana/node.options` |
| Certificates ([package - Wazuh installation guide](https://documentation.wazuh.com/current/deployment-options/elastic-stack/all-in-one-deployment/index.html#kibana-installation-and-configuration)) | `/etc/kibana/certs` |
| Configuration folder (Docker) | `/usr/share/kibana/config` | 
| Configuration file (Docker) | `/usr/share/kibana/config/kibana.yml` |
| Configuration keystore (Docker) | `/usr/share/kibana/config/kibana.keystore` |
| Configuration `node.options` (Docker) | `/usr/share/kibana/config/node.options` |
| Certificates (Docker) | `/usr/share/kibana/config/certs` |
| Wazuh plugin data | `/usr/share/kibana/data/wazuh` |
| Certificates | All the certificates used in the configuration. |

**Comment by Desvelao** [comment]
# Tasks
- [ ] Add more details of the files instead of folders (example `/etc/wazuh-indexer/opensearch.yml` instead of `/etc/wazuh-indexer/`)
  - [ ] Review `node.options` on Wazuh dashboard/Kibana
- [ ] Ignore plugin logs
- [ ] Ignore `wazuh-registry.json`
