### ISSUE TITLE
Refactor Agent SCA Inventory 

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4719]
Refactor the SCA Inventory component `(plugins/wazuh-kibana-app/public/components/agents/sca/inventory.tsx)`

### Current solution 

The component was created to have the Policies Table and The Policy Check table in it. That adds too many states to control when some UI elements would be rendered or not.
We need to avoid this control creating new atomic components that can control their own states.

![image](https://user-images.githubusercontent.com/6089438/196771158-b52b3c57-62f8-4ea5-a446-d470981967fd.png)

![image](https://user-images.githubusercontent.com/6089438/196771299-2577cebf-b8fc-49e5-a100-12eee0e97f59.png)

### Possible solution

- [ ] Create new atomic components to reduce complexity and improve the readability
- [ ] Reduce code lines
- [ ] Check all the state properties and decide if are necessary or not.

**Comment by gdiazlo** [comment]
We will work on this issue in the future, as it is not our focus right now.
