### ISSUE TITLE
Improve deploy new agent code

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4786]
## Objectives
- Improve the code readability in the register-agent component.
- Make the register agent's main component simpler and decoupled. 

### Tasks
- [x] [Document all the "deploy new agent" page behavior](https://github.com/wazuh/wazuh-kibana-app/issues/4786#issuecomment-1301992763)
- [x] Simplify register agent main component
- [x] Centralize set states only in the main component
- [x] Create new components for every step. (For example OS Selector, OS version, OS architecture, etc)
- [x] Decouple UI in child components
- [x] Decouple all the API requests from the main component
- [x] [Change folder Architecture for more readability](https://github.com/wazuh/wazuh-kibana-app/issues/4786#issuecomment-1301946058)
- [x] Change register agent main component to typescript file
- [x] Add types to all files and resolve ESLint warnings
- [x] Document methods in the code

**Comment by Machi3mfl** [comment]
## register-agent :open_file_folder: 

* [components/](./register-agent/components)
  * [WindowsAdvice.tsx](./register-agent/components/WindowsAdvice.tsx)
  * [index.ts](./register-agent/components/index.ts)
* [config/](./register-agent/config)
  * [index.ts](./register-agent/config/index.ts)
* [services/](./register-agent/services)
  * [index.ts](./register-agent/services/index.ts)
  * [packages-service.ts](./register-agent/services/packages-service.ts)
  * [register-agent-service.ts](./register-agent/services/register-agent-service.ts)
* [steps/](./register-agent/steps)
  * [AgentGroup.tsx](./register-agent/steps/AgentGroup.tsx)
  * [InstallEnrollAgent.tsx](./register-agent/steps/InstallEnrollAgent.tsx)
  * [ServerAddress.tsx](./register-agent/steps/ServerAddress.tsx)
  * [StartAgentTabs.tsx](./register-agent/steps/StartAgentTabs.tsx)
  * [WazuhPassword.tsx](./register-agent/steps/WazuhPassword.tsx)
  * [index.ts](./register-agent/steps/index.ts)
* [index.ts](./register-agent/index.ts)
* [register-agent-main.tsx](./register-agent/register-agent-main.tsx)

**Comment by Machi3mfl** [comment]
## Deploy new agent flow
```mermaid
graph TD
        A[Deploy new Agent] --> Z{Choose operating system}
    Z --> B[Red Hat / CentOS]
    Z --> C[Debian / Ubuntu]
    Z --> D[Windows]
    Z --> M[macOS]
    B --> X{Choose Version}
    X --> E[CentOS5]
    X --> F[CentOS6 or higher]
    X --> G[Red Hat 5]
    X --> H[Red Hat 6 or higher]
    E --> W{Choose architecture}
    F --> W
    G --> W
    H --> W
    W --> N[i386]
    W --> O[x86_64]
    C --> Y{Choose architecture}
    Y --> I[i386]
    Y --> J[x86_64]
    Y --> K[armhf]
    Y --> L[aarch64]
    V{Server Address}
    I --> V
    N --> V
    O --> V
    D --> V
    M --> V
    J --> V
    I --> V
    K --> V
    L --> V
    V --> P{Assign the agent to a group}
    P --> Q{Install and enroll the agent}
    Q --> R{Start the agent}

**Comment by Machi3mfl** [comment]
### Next Step
- [ ] Rebase this develop branch with 4.4-7.10 and adjust the changes applied by PR #4647 without broking the original behaviour

**Comment by Machi3mfl** [comment]
### Current tasks

- [ ] Simplifying steps definition in register-agent.js. 

**Current behavior:** When we add a new SO in the Deploy Agent section we add a lot of code lines that grow exponentially.
Actually, the steps definition has 500 code lines, we must prevent that grow exponentially by creating a new logic that allows simplicity when we need to add a new SO.
