### ISSUE TITLE
Automated - Test Plan - Add increased coverage for Agent's filter functionallity

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4792]
In this issue, we will track all the efforts to increase the coverage of the automation test cases for the agent's filter functionallity.
Perhaps, we add other test cases to increase the coverage elsewhere in the App.
In these test cases, they are normally executed manually by those that will be added to be automated.
Also, all test cases added should be executed successfully on the Wzd and Xpack environments.

## Tasks
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4793
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4811
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4819
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4835

</details>

**Comment by Mayons95** [comment]
Kibana - Automated test execution - Report 
[Kibana-Report - 04-11.pdf](https://github.com/wazuh/wazuh-kibana-app/files/9951256/Kibana-Report.-.04-11.pdf)
