### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4810]
## UI modules

We want to decompose our application into modules following the single responsibility design principle, among others. Before starting, we want to plan, design, and clarify the following topics:

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5113

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5114

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5228

 - [x] Decide between multi-plugin modules or single-plugin modules. 
     What's more convenient for us: developing different modules as separate plugins, or building different modules within the current one. Our preference would be to build them using our current one, but we need to ensure the different modules do not interact between them in unsuspected ways.

 - [x] Designs to communicate a module with others.
    - How a module can search for others
    - How a module can export services and views
    - How a module can prevent others from using certain services and views

 - [x] Define module lifecycle
   - login and logout 
   - wazuh API auth 
   - session renewal

 - [ ]  Define how to implement and use RBAC cross-module

 - [ ] Define a way to make them portable between our platforms
 
 - [ ] https://github.com/wazuh/wazuh-kibana-app/issues/5220
 
 - [ ] Define a way to build and install multiple plugins

We might revisit this list and add or remove items as the work progress.

**Comment by Desvelao** [comment]
Multi-plugin module (one repository)
> Register multiple applications

Shared services:
- requests related to Wazuh API
- RBAC
- Wazuh API session
- Configuration
- Reporting
- Filters
- Visualizations
- agnostic UI components

Define the structure of modules:
  - views
  - user flow

**Comment by asteriscos** [comment]
The following principles will be applied to improve scalability and maintainability:

- Encapsulate each app module files in the app module folder
- Apps modules should only consume services and components from the _/common_ folder or their own folder.
- Apps modules should not depend on other modules
- Services, components, stores, etc contained in a specific app module folder should be shared with other modules. If the need arises, it should be migrated to the _/common_ folder.

Modules as registered apps

![image](https://user-images.githubusercontent.com/9343732/203764136-ffe4f06d-3e44-415f-8668-cd8f73b6af7f.png)

**Comment by gdiazlo** [comment]
I'll close this as our new roadmap has evolved. The research effort will continue on other issues when we see fit. For know, we have the knowledge we wanted.
