### ISSUE TITLE
Automation - Wazuh Security - Policies & Roles

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4840]
In this issue, we will track all the efforts to increase the coverage of the the functionality of policies and role creation.
all test cases added should be executed successfully on the Wzd and Xpack environments.

## Tasks
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4843
- [ ] Create a new role
- [ ] Create a new role based on the policy previously created

</details>

**Comment by gdiazlo** [comment]
We manage QA plans and their testing on a per-release basis.
