### ISSUE TITLE
Support for Wazuh 4.4.0

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4886]
## Description

Wazuh 4.4.0 will be released shortly. Our Wazuh Dashboard and Kibana apps need to support this new version. From our side, the list of changes included in this version can be seen in our [CHANGELOG.md](./CHANGELOG.md).

### Pre-release
- [x] #4887
- [x] Add support for Wazuh 4.x.x (bump).
- [x] Generate the required tags.
- [x] Generate the packages.
- [x] Test the packages, to verify they install, and the app works as expected.
- [x] Run Regression Testing
  - [x] #4895
  - [x] #5041 
  - [x] #5115
  - [x] #5180 
  - [x] #5208
  - [x] #5301 
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.

### Supported versions

Same as on [previous releases](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility) **plus** 7.17.9. Included in #5301
