### ISSUE TITLE
Compatibility with OpenSearch 2.4.0

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4963]
## Branch: 
- https://github.com/wazuh/wazuh-kibana-app/tree/4.3.11-2.4.0

## Description
We need to ensure UI compatibility with OpenSearch 2.4.0

For that, we need to:

- [x] Create a new branch [`4.3.11-2.4`](https://github.com/wazuh/wazuh-kibana-app/tree/4.3.11-2.4.0)
- [x] Upgrade `winston` dependency to the latest compatible version d12ca53d939ef15534bb44c78753ab1b6d651cae - Related #4956
- [x] Remove `angular-chart.js` dependency a45ad9894649d6a6ed7928199de8af705e751e68  - Related #4956
- [x] Apply OSD 2.3.0 compatibility issues detailed in #4160
- [x] Make manual tests globally
- [x] Check if is necessary SAML for the client

## Issues to be applied

- [x] #4480 19135bbfae31a16c9bb10945c1768b9bb9c1c91e
- [x] #4683  54d951c578689fc5a7f3e4ccba5d063535003be3
- [x] #4502 8dd590e1528872e3d72158c041ff0d9a059f9969
- [x] #4597 373653faae1735247b109391d49f16fc8bf0258a
- [x] #4650 2e987e4031b4b4a60e6fc5edcce305da2fd3a642
- [x] #4740

**Comment by Machi3mfl** [comment]
## Upgrade `winston` package made by @asteriscos 

- Upgrade to the latest version error

![image](https://user-images.githubusercontent.com/6089438/205927825-3bd52592-4746-455e-9d1b-63113a09e30a.png)

### Conclusion

- Updated to the compatible latest version `winston V3.5.1`

![image](https://user-images.githubusercontent.com/6089438/205928590-842fb762-beed-4bc2-8dfd-d67adbd6d6f4.png)

**Utils docs**

- [https://github.com/winstonjs/winston/blob/v3.5.1/package.json#L69](https://github.com/winstonjs/winston/blob/v3.5.1/package.json#L69)
- [https://www.npmjs.com/package/winston?activeTab=dependencies](https://www.npmjs.com/package/winston?activeTab=dependencies)

**Comment by Machi3mfl** [comment]
## Remove angular-chart.js dependency made by @yenienserrano 

- Remove import 'angular-chart.js':  `line 24 of plugins/wazuh-kibana-app/public/app.js `
- Remove  'chart.js' requirement:  `line 90 of plugins/wazuh-kibana-app/public/get_inner_angular.ts`
- Remove import discoverTemplate from plugins/wazuh-kibana-app/public/kibana-integrations/kibana-discover.js: `line 20 of ../templates/discover/discover.html`
- Remove comment //discoverTemplate: `line 45 of plugins/wazuh-kibana-app/public/kibana-integrations/kibana-discover.js`
- Finally, remove the package `angular-chart.js`

**All these changes was applied on the [4.3.11-2.4.0 branch](https://github.com/wazuh/wazuh-kibana-app/tree/4.3.11-2.4.0)**

**Comment by Machi3mfl** [comment]
## Make manual tests

- Apply sample data en check data in dashboards

https://user-images.githubusercontent.com/6089438/205959153-3e02a1a5-82bc-4e5d-88e3-3038f46f3feb.mp4

- Rules, Decoders, Groups

https://user-images.githubusercontent.com/6089438/205959669-0f01f367-1128-4692-979e-e56c5b33764d.mp4

- Agents dashboard and detail

https://user-images.githubusercontent.com/6089438/205960119-588441ef-d211-4d08-99d6-b9b060651a07.mp4

- Devtools

https://user-images.githubusercontent.com/6089438/205960291-df05383a-78c2-4b1c-80f8-654c69800ecd.mp4

- Security: Rules, Roles, Policies, Roles Mapping

https://user-images.githubusercontent.com/6089438/205960754-fbf4945a-51ff-4b88-80a8-b9e30abab865.mp4

- Settings

https://user-images.githubusercontent.com/6089438/205962733-28e5a66d-5e67-4046-ab91-7a8a8ee07514.mp4

**Comment by Desvelao** [comment]
# Changes
Fixed:
- a problem related to the generation of CSV (in Rules, Decoders) due to a typo in a variable.
- missing use of status codes instead of internal server error fallback.
Added:
- Changelog with the changes pointing to the commits

**Comment by Desvelao** [comment]
# Testing

Tested with custom Wazuh dashboard and indexer packages:
![image](https://user-images.githubusercontent.com/34042064/206243879-6938b535-e83c-4114-8e77-faffd731cbb5.png)
![image](https://user-images.githubusercontent.com/34042064/206243927-98603e45-8f6f-43bd-9414-f2214ebc5a7b.png)
![image](https://user-images.githubusercontent.com/34042064/206244017-42c25366-7c47-41e1-9bcc-516047e9f4df.png)
![image](https://user-images.githubusercontent.com/34042064/206244066-1f868c4d-e8bb-4cbe-8c90-1d10054abe95.png)
![image](https://user-images.githubusercontent.com/34042064/206244259-58f2a6c5-588e-4c15-9987-8d373fe819a2.png)
![image](https://user-images.githubusercontent.com/34042064/206244469-167d6b15-9a94-4dc8-bf9f-42b93934ef2a.png)
![image](https://user-images.githubusercontent.com/34042064/206244567-84b3b94d-5a00-483b-a53b-fbe0b0de48c9.png)
![image](https://user-images.githubusercontent.com/34042064/206244721-0225a80f-abb6-43aa-b55d-e0060fc01440.png)

**Comment by Tostti** [comment]
# Testing
Tested packages in a Virtual machine. No issues were found during these tests.

<details>
<summary>Virtual environment info</summary>

```console
root@test:/home/wazuh# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@test:/home/wazuh# free -h
               total        used        free      shared  buff/cache   available
Mem:           7.8Gi       2.1Gi       1.5Gi       1.0Mi       4.2Gi       5.4Gi
Swap:          2.0Gi          0B       2.0Gi

root@test:/home/wazuh# df --total -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              795M  1.2M  794M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   12G  7.9G  2.9G  74% /
tmpfs                              3.9G  284K  3.9G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  127M  1.7G   7% /boot
tmpfs                              795M  4.0K  795M   1% /run/user/1000
total                               19G  8.0G   10G  45% -

root@test:/home/wazuh# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    CPU family:          6
    Model:               158
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            9
    BogoMIPS:            8399.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_kno
                         wn_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 bmi2 invpcid rdseed clflushopt md_clea
                         r flush_l1d arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    32 MiB (4 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX unsupported
  L1tf:                  Mitigation; PTE Inversion
  Mds:                   Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT Host state unknown
  Retbleed:              Vulnerable
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Unknown: Dependent on hypervisor status
  Tsx async abort:       Not affected
```
  
</details>

![image](https://user-images.githubusercontent.com/42900763/206278741-04ec9da9-96e9-4426-bed1-22533bec6140.png)
![image](https://user-images.githubusercontent.com/42900763/206278758-95fbb63a-7d80-4e0c-b890-5acb91cc1985.png)
![image](https://user-images.githubusercontent.com/42900763/206278850-87f2d4ca-3f55-41a8-8b42-7d640e90ebe2.png)
![image](https://user-images.githubusercontent.com/42900763/206278965-a5e9c21b-de17-48de-acbf-84ad0862196f.png)
![image](https://user-images.githubusercontent.com/42900763/206279639-408313af-90dc-42f6-b9e8-920f94990a49.png)
![image](https://user-images.githubusercontent.com/42900763/206279740-bc2e6ab7-fea6-443d-8c1f-21a6c6b500dc.png)
