### ISSUE TITLE
Cleanup embedded components

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5040]
**Describe the solution you'd like**
We want to ensure we use mainstream components through our application. We need to evaluate which components can we use from upstream.

**Describe alternatives you've considered**

**Additional context**

- [ ] [CodeQL#9](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/9)
- [ ] [CodeQL#10](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/10)
- [ ] [CodeQL#11](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/11)
- [x] [CodeQL#14](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/14)
- [x] [CodeQL#19](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/19)
- [x] [CodeQL#20](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/20)
- [ ] [CodeQL#42](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/42)
- [x] [CodeQL#43](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/43)

Related issues:
- [ ] #5039

**Comment by Desvelao** [comment]
# Research

## codemirror

> [CodeQL#9](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/9)
> [CodeQL#10](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/10)
> [CodeQL#11](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/11)
> [CodeQL#42](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/42)

These problems are related to `codemirror`. This is used as the API Console editor. There are some issues related to using the platform editor instead.
- https://github.com/wazuh/wazuh-kibana-app/issues/5039

## jquery-ui

> [ ] [CodeQL#14](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/14)
> [ ] [CodeQL#19](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/19)
> [ ] [CodeQL#20](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/20)
> [ ] [CodeQL#43](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/43)

These problems are related to the built-in `jquery-ui` dependency.

The current built-in `jquery-ui` dependency is:

| Built-in dependency | version |
| --- | --- |
| jquery-ui | v1.12.1 - 2016-09-14 |

```
jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library. Whether you're building highly interactive web applications or you just need to add a date picker to a form control, jQuery UI is the perfect choice.
```
web: https://jqueryui.com/

For another hand, the current compatible plugin platforms with the Wazuh plugin define the `jquery` dependency.

| Platform | jquery|
| --- | --- |
| OpenSearch Dashboards 2.6.0 | `^3.5.0` https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.6.0/package.json#L401 |
| Kibana 7.10.2   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.10.2/package.json#L423   |
| Kibana 7.16.0   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.16.0/package.json#L260   |
| Kibana 7.16.1   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.16.1/package.json#L263   |
| Kibana 7.16.2   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.16.2/package.json#L263   |
| Kibana 7.16.3   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.16.3/package.json#L262   |
| Kibana 7.17.0   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.0/package.json#L263   |
| Kibana 7.17.1   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.1/package.json#L265   |
| Kibana 7.17.2   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.2/package.json#L266   |
| Kibana 7.17.3   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.3/package.json#L266   |
| Kibana 7.17.4   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.4/package.json#L266   |
| Kibana 7.17.5   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.5/package.json#L266   |
| Kibana 7.17.6   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.6/package.json#L266   |
| Kibana 7.17.7   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.7/package.json#L265   |
| Kibana 7.17.8   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.8/package.json#L265   |
| Kibana 7.17.9   | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.9/package.json#L263   |
| Kibana 7.17.10 | `^3.5.0` https://github.com/elastic/kibana/blob/v7.17.10/package.json#L259 |

`jquery-ui` dependency is not included in the plugin platform.

According to the jQuery UI documentation, the latest version is `v1.13.2`.

### Conclusions

`jquery-ui` is not included in the plugin platform. We have 2 options to try to fix the problem:
- check if the latest version `v1.13.2` fixes the problems detected by CodeQL
- review if the plugin is using some feature provided by the `jquery-ui`, if not we could remove it.

**Comment by Desvelao** [comment]
# Digging

## jquery-ui

The built-in `jquery-ui` dependency was added in this pull request: https://github.com/wazuh/wazuh-kibana-app/pull/1362.

The reason to add it, it seems that it was using the `resizable()` method provided by the `jquery-ui` instead of the colResizable jQuery plugin.

I found this change: https://github.com/wazuh/wazuh-kibana-app/pull/1362/files#diff-b4cc16e9cc9a9044b27aebd2827445b029cba50cf000ff3aac173cc91c740616R504-R512

WIP

**Comment by Desvelao** [comment]
The problems related to `jquery-ui` dependency were solved in the pull requests
> #5592
> #5673
> #5674

The problems related to the code mirror could be solved if replacing the editor in https://github.com/wazuh/wazuh-kibana-app/issues/5039.
