### ISSUE TITLE
Support for Wazuh 4.4.1

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5316]
## Description

Wazuh 4.4.1 will be released shortly after 4.4.0. Our Wazuh Dashboard and Kibana apps need to support this new version.

## Tasks

- [x] #5198
- [x] #5300
- [x] #5317
- [x] #5318
- [x] #5336

### Pre-release
- [x] Ensure #5263.
- [x] #5342
- [x] Generate the required tags.
- [x] Generate the packages.
- [x] Test the packages, to verify they install, and the app works as expected.
- [x] Run Regression Testing (#5356)
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update compatibility matrix.

### Supported versions

Same as on [previous releases](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility)
