### ISSUE TITLE
Prepare the release 4.4.1

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5342]
## Tasks

- [x] Add support for Wazuh 4.4.1 - version bump.
- [x] Add support for Wazuh Dashboard - version bump.
- [x] Review the Changelog.
