### ISSUE TITLE
Support for Wazuh 4.3.11

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#5394]
## Description

Wazuh 4.3.11 will be released shortly. Our Wazuh Dashboard and Kibana apps need to support this new version. From our side, no changes will be included, so we only need to bump the version.

### Pre-release
- [x] Add support for Wazuh 4.3.11 (bump).
- [x] Generate the required tags.
- [x] Generate the packages.
- [x] #5397
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility).

### Supported versions

Same as on [previous releases](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility)
