### ISSUE TITLE
Support for Wazuh 4.4.2

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#5404]
## Description

Example:
Wazuh 4.4.2 will be released shortly. Our Wazuh Dashboard and Kibana apps need to support this new version. From our side, no changes will be included, so we only need to bump the version.

### Pre-release
- [x] #5405
- [x] Generate the required tags.
- [x] Generate the packages.
- [x] #5414
- [x] #5440
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility).

### Supported versions

Same as on [previous releases](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility)

**Comment by Desvelao** [comment]
# Installation check

- Kibana
  - [x] 7.10.2
  <details>
 
![image](https://user-images.githubusercontent.com/34042064/235597844-43c4d383-82ca-498f-9fd5-6e518c7ee72f.png)

  </details>
  - [ ] 7.16.0
  <details>
  
  </details>
  - [ ] 7.16.1
    <details>
  
  </details>
  - [ ] 7.16.2
    <details>
  
  </details>
  - [ ] 7.16.3
    <details>
  
  </details>
  - [ ] 7.17.0
    <details>
  
  </details>
  - [ ] 7.17.1
    <details>
  
  </details>
  - [ ] 7.17.2
    <details>
  
  </details>
  - [ ] 7.17.3
    <details>
  
  </details>
  - [ ] 7.17.4
    <details>
  
  </details>
  - [ ] 7.17.5
    <details>
  
  </details>
  - [ ] 7.17.6
    <details>
  
  </details>
  - [ ] 7.17.7
    <details>
  
  </details>
  - [ ] 7.17.8
    <details>
  
  </details>
  - [ ] 7.17.9
    <details>
  
  </details>
