### ISSUE TITLE
[Redesign add agent] Create reusable card for operating systems

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5435]
## Description

This issue is part of the redesign of the deploy a new agent section. These cards will be reusable, they will show the operating system and architecture and based on that selection made by the user we will manage what data to show to the user in other steps.

<img width="1105" alt="Captura de pantalla 2023-05-11 a la(s) 15 29 28" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/4a996f60-27eb-4125-8885-2fecca0cfdb0">

**Updated design:**

<img width="1115" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/97e884b5-e92d-4c48-8d98-7cc3fe1fbfca">

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Creation of reusable card component

- [x] Display information inside the card

- [x] Create a checkbox component with its respective logic

- [x] Applying styles

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by chantal-kelm** [comment]
This is the current look of the new agent deployment page using the reusable cards built in this issue:

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/b5d39933-f019-4e36-8dd8-6330ccf3de14">

**Comment by chantal-kelm** [comment]
Update:

<img width="1215" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/69d66494-4732-4d27-8e66-f07635297329">

**Comment by chantal-kelm** [comment]
It was decided to add the intel architecture to the macOS card:

<img width="1129" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/c3d47eba-4bce-4f95-98cd-05444aad90b3">
