### ISSUE TITLE
[Redesign add agent] Add new register agent command generator

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#5455]
## Description
Create a register agent command generator that receives the data collected from the register agent form and returns the corresponding command to register a new Wazuh agent. 

## Command format

More details about commands definition in this comment: https://github.com/wazuh/wazuh-packages/issues/1625#issuecomment-1365838810

## Tasks

- [x] Create a class/classes that receive OS settings and return the register agent's commands
- [x] The class must not have UI to facilitate reusability
- [x] Add unit tests for all classes created
- [x] Create a React Hook that uses that class internally
- [x] Add documentation explaining how to use it
  -  [Command generator documentation](https://github.com/wazuh/wazuh-kibana-app/blob/8c3bcf9fcf8746255a634a9cb5ca96440fe31d8b/public/controllers/register-agent/core/register-commands/README.md)
  - [Hook documentation](https://github.com/wazuh/wazuh-kibana-app/blob/8c3bcf9fcf8746255a634a9cb5ca96440fe31d8b/public/controllers/register-agent/core/register-commands/README.md)
- [x] Check all the code to find syntaxes errors

**Comment by Machi3mfl** [comment]
Added README file in related PR with the solution documentation:
https://github.com/wazuh/wazuh-kibana-app/blob/056ccfe668291eaa7da56a1f858e7f9268be7a0b/public/controllers/register-agent/core/README.md

**Comment by Machi3mfl** [comment]
Added hook to use the new Command generator class

## Unit tests 

<img width="686" alt="Screenshot 2023-06-07 at 15 04 52" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/04ddac1a-fb91-4ff3-841e-6089529ada58">

**Comment by Machi3mfl** [comment]
# Next step

- [ ] Add documentation with examples using generics types added in the last commit https://github.com/wazuh/wazuh-kibana-app/pull/5469/commits/17bf259b0dc8879393f5f73eebfba097c2cdc4af
