### ISSUE TITLE
Support for Wazuh 4.4.3

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5475]
## Description

Wazuh 4.4.3 will be released shortly. Our Wazuh Dashboard and Kibana apps need to support this new version. From our side, the following changes will be included: 

- #5466 

### Pre-release
- [x] Add support for Wazuh 4.x.x (bump).
- [x] Generate the required tags.
- [x] Generate the packages.
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5492
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility).

### Supported versions

Same as on [previous releases](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility)

**Comment by AlexRuiz7** [comment]
Waiting for the packages

**Comment by AlexRuiz7** [comment]
All the branches but the `4.5` have been updated. There are several collisions in this branch that need to be solved. @asteriscos and @chantal-kelm will do that as they have the details of these changes in the code.

I move the issue to On Hold until then.
