### ISSUE TITLE
[Redesign add agent] Inputs logic (server address, name, password, group)

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5518]
## Description

This issue is part of the redesign of the deploy a new agent page.

These entries server address, name and group have some logic and validations, to be taken into account. The topic will be updated with the use cases. 

One of the use cases for the server address entry is when the user fills in the enrollment.dns field.

<img width="1121" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/ac7a3bf8-b4ae-49f7-8e85-d0b02a856005">

Then in the server address entry we will show the value of enrollment.dns otherwise the entry will be empty and the user will have to fill it.

<img width="1129" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/4805643b-500f-4437-ae1f-25ca7eaf2201">

## **The latest use cases for the server address input are detailed in this [issue](https://github.com/wazuh/wazuh-kibana-app/pull/5166).**

**Design:**

<img width="1106" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/2175e891-a502-49d1-8ad0-f88b3012b754">

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Identify use cases
- [x] Develop use cases
- [x] Develop validation for the server address input
- [x] Develop validation for agent name input
- [x] Adding styles

## Additional information

**In this issue this file will be refactored:** https://github.com/wazuh/wazuh-kibana-app/blob/master/public/controllers/agent/components/register-agent.js

**Comment by chantal-kelm** [comment]
In progress: 

<img width="1106" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/66ce4694-b20b-4127-ad8b-85adc2ef69ae">

**Comment by chantal-kelm** [comment]
Working on the error that occurs when in the configuration section the IP is empty.

**Comment by chantal-kelm** [comment]
:point_up_2: Bug fixed, working on testing, styles, error handling
