### ISSUE TITLE
Add process name in ports information for Linux systems and review the items order in ports inventory.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-kibana-app#5529]
## Description
As part of this implementation https://github.com/wazuh/wazuh/pull/15000 we are adding the capability to display process name and process ID in the ports inventory on Linux systems. Currently, there's no tab for process name on Linux.

Linux example

<details>
<summary>Expand image</summary>

![image](https://github.com/wazuh/wazuh-kibana-app/assets/13010397/5da91369-04f4-4623-8794-1252ae3eef3f)

</details>

Windows example

<details>
<summary>Expand image</summary>

![image](https://github.com/wazuh/wazuh-kibana-app/assets/13010397/40202023-bf51-423f-bb68-e574fc1a6db7)

</details>

Also, I would rather prefer to see the port information in the first column since this is the ports inventory. In addition, there's no information for processes related to NFS and the column would look odd with empty values. 

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Review the column order, probably `Local port` should be first. 
- [x] Add the `Process` column for Linux system. The change may be related to this code section https://github.com/wazuh/wazuh-kibana-app/blob/b11b995886bc47ffdb73849375e0225b05b6ce74/server/controllers/wazuh-reporting.ts#L970-L983
> This code is related to the PDF report

- [x] Add process name and PID to the table
  - [x] UI
  - [x] PDF report
  
 - [x] Allow searching in the new fields
