### ISSUE TITLE
Maintain production and numbered branches post release v4.4.5

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5664]
| Related issue |
| --- |
| wazuh/wazuh#17867 |

The goal is to complete the following tasks, each task must have a PR associated with this issue. 

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, merge-4.4.5-into-4.4.

Also, all PRs corresponding to the same phase (merge-X-into-Y) must be merged at the same time.

### Wazuh-kibana-app -> @wazuh/frontend
- [x] Merge tag `v4.4.5` into `4.4` (fast-forward) on wazuh-kibana-app repository --> #5665
- [x] Delete branch `4.4.5` --> #5665
- [x] Merge branch `4.4` into `4.5.0` on wazuh-kibana-app repository --> #5669 
- [x] Merge branch `4.5.0` into `4.5.1` on wazuh-kibana-app repository --> #5670
- [x] Merge branch `4.5.1` into `4.6.0` on wazuh-kibana-app repository --> #5671 
- [x] Merge branch `4.6.0` into `master` on wazuh-kibana-app repository --> #5672
- [ ] Merge branch `4.6.0` into `4.7.0` on wazuh-kibana-app repository --> #5675
