### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#5755]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh-kibana-app repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.1
- [ ] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh-kibana-app repository.
- [ ] Create a pre-release: https://github.com/wazuh//releases/tag/v4.5.1-alpha1
