### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#5756]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh-kibana-app repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Update API endpoints information https://github.com/wazuh/wazuh-kibana-app/pull/5758
- [x] Create tag v4.5.1-2.6.0-alpha1 from branch 4.5.1 on wazuh-kibana-app repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.5.1-alpha1
