### ISSUE TITLE
Support new stage RC 1 for 4.5.1 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#5782]
## Description

This issue attempts to support a new stage RC 1 for 4.5.1 in the wazuh-kibana-app repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-rc1 from branch 4.5.1 on wazuh-kibana-app repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.5.1-2.6.0-rc1
