### ISSUE TITLE
Adapt the breadcrumb to the new menu and remove old menu

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5814]
## Description

The section of the applications will be moved to the side menu of the platform. We need to adapt the breadcrumb to the new applications.

The root item of the breadcrumb should be the name of the application.

## Screenshots
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/71ab8921-b06f-4214-b14a-8f43783edd4c)

## Tasks
- [x] Adapt the breadcrumb
- [x] Change the redirections
- [x] Remove legacy menu

**Comment by yenienserrano** [comment]
Two types of breadcrumb renderings were found, one that has an icon with a tooltip with a description and the other has no such icon. We would have to decide to leave one for all modules, if all modules have the icon or not.

**Comment by yenienserrano** [comment]
We have decided to remove the breadcrumbs icon since other applications do not have it, if we want to add it in the future we would have to add it in all the views.

**Comment by Desvelao** [comment]
I reopened the issue due to changes in the app names, so we will change the application ID too.
