### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#5822]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh-kibana-app repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Create tag v4.6.0-2.8.0-alpha1 from branch 4.6.0 on wazuh-kibana-app repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.6.0-2.8.0-alpha1.
