### ISSUE TITLE
Support new Wazuh version 4.5.3 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#5823]
## Description

This issue attempts to support a new version 4.5.3 in the wazuh-kibana-app repository.

## Tasks

- [x] Create numbered branch for version (4.5.3) using branch 4.5.2 on wazuh-kibana-app repository.
- [x] Bump 4.5.3 branch to 4.5.3 version, including revision and changelog.

PRs
- [x] https://github.com/wazuh/wazuh-kibana-app/pull/5824
- [x] https://github.com/wazuh/wazuh-kibana-app/pull/5825
- [x] https://github.com/wazuh/wazuh-kibana-app/pull/5828
