### ISSUE TITLE
Modify Overview application to display the Wazuh applications

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5835]
**Description**
The Overview application should display all the Wazuh applications instead of the current "modules".

The main panels should have the name of the application categories.

- Endpoints security
- Thread intelligence
- Security operations
- Cloud security
- Server management
- Management

Each application should be displayed in the related category.

**Screenshots**
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/3b67943a-8dfa-4851-869b-feedb855fd95)

# Tasks
- [x] Define the Overview application
- [x] Group the applications by categories and display them as panels with cards instead of the old modules
- [x] Define the icon and description for the applications that are not set
