### ISSUE TITLE
[Vulnerabilities dashboard] Add POC to create a dashboard using osd artifacts

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#5839]
## Description

Add POC to create a dashboard using OSD artifacts. Use all the native OSD components to create a dashboard using a defined index pattern.

## Tasks

- [x] Create a component to render a dashboard in wazuh-kibana-app
- [x] Create abstractions (wrapper component, interfaces) to make easier the development and parallel work
- [x] Create a solution that receives an index pattern and some configuration and renders a dashboard with visualizations

**Comment by jbiset** [comment]
## Research
By analyzing the OpenSearch Dashboard documentation complemented with the documentation present in the code, it has been possible to render within the vulnerability detector module a dashboard that renders embedded visualizations by value. This modality allows you to create the dashboard by passing the data necessary for rendering, the result of the JSON that is obtained through the visualization creation tool.
However, the mode of rendering by reference through the savedObjectId is being analyzed, which is not yet fully implemented in the examples presented by the OpenSearch Dashboard plugin.
Below is a class diagram to understand how the embeddable plugin is designed and render an embedded display via its savedObjectId.

```mermaid

classDiagram
  class EmbeddableInput {
    <<type>>
    viewMode?: ViewMode;
    title?: string;
    id: string;
    lastReloadRequestTime?: number;
    hidePanelTitles?: boolean;
    enhancements?: SerializableState;
    disabledActions?: string[];
    disableTriggers?: boolean;
    timeRange?: TimeRange;
    query?: Query;
    filters?: Filter[];
  }
  class EmbeddableOutput {
    <<interface>>
    loading?: boolean;
    error?: EmbeddableError;
    editUrl?: string;
    editApp?: string;
    editPath?: string;
    defaultTitle?: string;
    title?: string;
    editable?: boolean;
    savedObjectId?: string;
  }
class IEmbeddable~EmbeddableInput, EmbeddableOutput~{
    <<interface>>
    +getInput(): EmbeddableInput
    +getOutput(): EmbeddableOutput
  }
  class SavedObjectAttributes {
    <<interface>>
    [key: string]: SavedObjectAttribute;
  }
  class SavedObjectAttribute {
    <<type>>
    %% SavedObjectAttribute = SavedObjectAttributeSingle | SavedObjectAttributeSingle[];
  }
    %% SavedObjectAttributeSingle = string | number | boolean | null | undefined | SavedObjectAttributes;
  class PersistableState~EmbeddableInput~ {
    <<interface>>
    +getPersistableState(): EmbeddableInput
  }
  class SavedObjectMetaData~T~ {
    <<interface>>
    type: string;
    name: string;
    getIconForSavedObject(savedObject: SimpleSavedObject<T>): IconType;
    getTooltipForSavedObject?(savedObject: SimpleSavedObject<T>): string;
    showSavedObject?(savedObject: SimpleSavedObject<T>): boolean;
    includeFields?: string[];
  }
  class IContainer {
    <<interface>>
    untilEmbeddableLoaded<TEmbeddable>(id: string): Promise<TEmbeddable | ErrorEmbeddable>
    getInputForChild<EEI extends EmbeddableInput>(id: string): EEI
    updateInputForChild<EEI extends EmbeddableInput>(id: string, changes: Partial<EEI>): void;
    getChild<E extends Embeddable<EmbeddableInput> = Embeddable<EmbeddableInput>>(id: string): E;
    removeEmbeddable(embeddableId: string): void;
    addNewEmbeddable<EEI, EEO, E>(type: string, explicitInput: Partial<EEI>): Promise<E | ErrorEmbeddable>
  }
class EmbeddableError {
    <<interface>>
    name: string;
    message: string;
  }
  class ErrorEmbeddable {
    - type = ERROR_EMBEDDABLE_TYPE
    - dom?: HTMLElement
    + error: Error | string;
    + constructor(error: Error | string, input: EmbeddableInput, parent?: IContainer)
    + reload(): void;
    + render(dom: HTMLElement): void;
    + destroy(): void;
  }

  class Embeddable~EmbeddableInput, EmbeddableOutput~ {
    <<abstract>>
    + runtimeId: number;
    + runtimeId = Embeddable.runtimeId++;
    + parent?: IContainer;
    + isContainer: boolean = false;
    + type: string;
    + id: string;
    + fatalError?: Error;
    # output: TEmbeddableOutput;
    # input: TEmbeddableInput;
    - input$: Rx.BehaviorSubject<TEmbeddableInput>;
    - output$: Rx.BehaviorSubject<TEmbeddableOutput>;
    - parentSubscription?: Rx.Subscription;
    - destroyed: boolean = false;
    # renderComplete = new RenderCompleteDispatcher();
    + constructor(input: TEmbeddableInput, output: TEmbeddableOutput, parent?: IContainer);
    + getIsContainer(): this is IContainer;
    * reload(): void;
    + getInput$(): Readonly<Rx.Observable<TEmbeddableInput>>;
    + getOutput$(): Readonly<Rx.Observable<TEmbeddableOutput>>;
    + getOutput(): Readonly<TEmbeddableOutput>;
    + getInput(): Readonly<TEmbeddableInput>;
    + getTitle(): string;
    + getRoot(): IEmbeddable | IContainer;
    + updateInput(changes: Partial<TEmbeddableInput>): void;
    + render(el: HTMLElement): void;
    + getInspectorAdapters(): Adapters | undefined;
    + destroy(): void;
    # updateOutput(outputChanges: Partial<TEmbeddableOutput>): void;
    # onFatalError(e: Error);
    - onResetInput(newInput: TEmbeddableInput);
    - onInputChanged(changes: Partial<TEmbeddableInput>);
    + supportedTriggers(): Array<keyof TriggerContextMapping>;
  }
class EmbeddableFactory~EmbeddableInput, EmbeddableOutput, IEmbeddable, SavedObjectAttributes~ {
    <<interface>>
    type: string
    isEditable(): Promise<boolean>
    savedObjectMetaData?: SavedObjectMetaData
    isContainerType: boolean
    getDisplayName(): string
    canCreateNew(): boolean
    getDefaultInput(partial: Partial<EmbeddableInput>): Partial<EmbeddableInput>
    getExplicitInput(): Promise<Partial<EmbeddableInput>>
    createFromSavedObject(savedObjectId: string, input: Partial<EmbeddableInput>, parent?: IContainer): Promise<IEmbeddable | ErrorEmbeddable>
    create(initialInput: EmbeddableInput, parent?: IContainer): Promise<IEmbeddable | ErrorEmbeddable | undefined>
  }
class ContainerInput~PanelExplicitInput~ {
    hidePanelTitles?: boolean;
    panels: Array<PanelState>;
  }
class ContainerOutput {
    embeddableLoaded: Array<boolean>;
  }
class ObjectIdType {
    <<type>>
    id: string;
  }
  class PanelState {
    <<interface>>
    type: string;
    explicitInput: Partial<E> & ObjectIdType;
  }
  class EmbeddableRenderer ~EmbeddableInput~ {

  }
class EmbeddableRoot {
    - root?: React.RefObject<HTMLDivElement>;
    - alreadyMounted: boolean = false;
  }

  PersistableState <|-- EmbeddableFactory
  Embeddable <|-- ErrorEmbeddable
  IEmbeddable <|-- Embeddable
  IEmbeddable <|-- IContainer
  EmbeddableInput <|-- ContainerInput
  EmbeddableOutput <|-- ContainerOutput
  EmbeddableInput <|-- PanelState
```
