### ISSUE TITLE
Maintain production and numbered branches post release 4.5.2 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#5855]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.2-into-4.5.3`.

## Tasks

- [x] Merge branch `4.5.2` into branch `4.5.3`. https://github.com/wazuh/wazuh-kibana-app/pull/5856
- [x] Merge branch `4.5.3` into branch `4.6.0`. https://github.com/wazuh/wazuh-kibana-app/pull/5859
- [x] Merge branch `4.6.0` into branch `4.7.0`. https://github.com/wazuh/wazuh-kibana-app/pull/5860
- [ ] Merge branch `4.7.0` into branch `master`. https://github.com/wazuh/wazuh-kibana-app/pull/5861
- [x] Delete all stage pre-releases for 4.5.2 (https://github.com/wazuh/wazuh-kibana-app/releases).
- [x] Delete all stage tags for v4.5.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.2-rc1, 4.5.2-alpha1, etc.
- [x] Delete branch `4.5.2`.
- [x] Merge branch `4.5.2-7.10` into branch `4.5.3-7.10`. https://github.com/wazuh/wazuh-kibana-app/pull/5857
- [x] Delete all stage tags for v4.5.2-7.10. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.2-rc1, 4.5.2-alpha1, etc.
- [x] Delete branch `4.5.2-7.10`.
- [x] Merge branch `4.5.2-7.16` into branch `4.5.3-7.16`. https://github.com/wazuh/wazuh-kibana-app/pull/5858
- [x] Delete all stage tags for v4.5.2-7.16. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.2-rc1, 4.5.2-alpha1, etc.
- [x] Delete branch `4.5.2-7.16`.
