### ISSUE TITLE
[Update dashboards] Create `malware detection` dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5898]
## Description

Create the malware detection dashboard 

### Dashboard mock

![image](https://documentation.wazuh.com/4.3/_images/screenshot-02-Wazuh-Intrusion-Detection1.png)

**The dashboard mock serves as a design prototype (the information shown is only an example)**

## Tasks

- [x] Create visualizations definitions 
- [ ] ~~Update colors to create a consistent color palette~~ -> [After some research, the following conclusion was reached](https://github.com/wazuh/wazuh-kibana-app/issues/5838#issuecomment-1707163985)
- [ ] ~~Document the differences between `wazuh-kibana-app` and `integrations` dashboard (information shown)~~ -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5898#issuecomment-1724589591)

**Comment by chantal-kelm** [comment]
This dashboard does not exist in the current plugin so no comparison can be made.

**Comment by chantal-kelm** [comment]
<img width="1792" alt="Captura de pantalla 2023-09-20 a la(s) 09 20 43" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/e74d9970-f427-4a85-be06-0e513f11ee26">
