### ISSUE TITLE
[Update dashboards] Create `Log data analysis` dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5909]
## Description

Create the Log data analysis dashboard 

### Dashboard mock

![image](https://documentation.wazuh.com/4.3/_images/screenshot-03-Wazuh-Log-Data-Analysis1.png)

**The dashboard mock serves as a design prototype (the information shown is only an example)**

## Tasks

- [x] Create the visualisations definitions that are possible with the chart types offered by Opensearch. -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5909#issuecomment-1730048056)
- [ ] After implementing this dashboard in our plugin, we will have to develop a flyout when clicking on the data in the table. 
- [ ] ~~Update colors to create a consistent color palette~~ -> [After some research, the following conclusion was reached](https://github.com/wazuh/wazuh-kibana-app/issues/5838#issuecomment-1707163985)
- [ ] ~~Document the differences between `wazuh-kibana-app` and `integrations` dashboard (information shown)~~ -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5909#issuecomment-1730021154)

**Comment by chantal-kelm** [comment]
This dashboard does not exist in the current plugin so no comparison can be made.

**Comment by chantal-kelm** [comment]
Since we make the visualisations with the graph types provided by Opensearch, only the Attack Tactics by Agent graph and the Recent Events graph can be made in this issue, as the rest are designed visualisations and are not possible with the Opensearch graph types.

**Comment by chantal-kelm** [comment]
<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/c62e1850-72af-43ec-8793-bf0c7f0a2c8a">
