### ISSUE TITLE
[Update dashboards] Update `integrity monitoring` dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5911]
## Description

Update the integrity monitoring dashboard.

## Dashboard Mock

![image](https://documentation.wazuh.com/4.3/_images/screenshot-04-Wazuh-File-Integrity-Monitoring1.png)

**The dashboard mock serves as a design prototype (the information shown is only an example)**

## Tasks

- [x] Create visualizations definitions 
- [ ] ~~Update colors to create a consistent color palette~~ -> [After some research, the following conclusion was reached](https://github.com/wazuh/wazuh-kibana-app/issues/5838#issuecomment-1707163985)
- [ ] ~~Document the differences between `wazuh-kibana-app` and `integrations` dashboard (information shown)~~ -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5898#issuecomment-1724589591)

**Comment by chantal-kelm** [comment]
Update dashboard

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/4f8ef322-60d1-4470-bc23-d8e192727304">
