### ISSUE TITLE
Support new stage Beta 1 for 4.6.0 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#5920]
## Description

This issue attempts to support a new stage Beta 1 for 4.6.0 in the wazuh-kibana-app repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Bump revision for branch 4.6.0 on wazuh-kibana-app repository. #5921
- [x] Create tag v4.6.0-beta1 from branch 4.6.0 on wazuh-kibana-app repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.6.0-2.8.0-beta1

**Comment by Tostti** [comment]
LGTM
