### ISSUE TITLE
[Update dashboards] Update `regulatory compliance` dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5938]
## Description

Update the regulatory compliance dashboard.

## Dashboard Mock

![image](https://documentation.wazuh.com/4.3/_images/screenshot-08-Wazuh-Regulatory-Compliance1.png)

**The dashboard mock serves as a design prototype (the information shown is only an example)**

## Tasks

- [x] Create visualizations definitions 
- [ ] ~~Update colors to create a consistent color palette~~ -> [After some research, the following conclusion was reached](https://github.com/wazuh/wazuh-kibana-app/issues/5838#issuecomment-1707163985)
- [ ] ~~Document the differences between `wazuh-kibana-app` and `integrations` dashboard (information shown)~~ -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5898#issuecomment-1724589591)

**Comment by chantal-kelm** [comment]
Update dashboard

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/cc78f6ad-268e-4b06-8d69-cf09bc41ddde">
