### ISSUE TITLE
[Vulnerabilities dashboards] Add search bar services/hooks

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#5945]
## Description

All services to avoid the use of the SearchBar component from OSD data plugin.
These services will be used like a search bar in the new vulnerabilities dashboards.

## Tasks

- [x] Create services/hooks
- [x] Unit test for every services/hooks

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

**Comment by Machi3mfl** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/5960
