### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#619]
Hi team!

In this issue we'll describe the process of adaptation to the RBAC system using the new API 4.0 features.

We'll describe where we want to go with the adaptation to the RBAC and the changes we need to make in our system.

To organize the workflow, we have created a development branch, [new-rbac](https://github.com/wazuh/wazuh-kibana-app/tree/new-rbac), thanks to the Git-Flow tool, which will be our main development branch. This branch will be continuously updated from branch [new-api](https://github.com/wazuh/wazuh-kibana-app/tree/new-api).
From this branch, we'll create each feature that comes up, using the NewRbac/ prefix.

Once we have described all of the above, the following issues must be completed to finish with the adaptation to the RBAC

- [x] [RBAC: System Overview](https://github.com/wazuh/wazuh-kibana-app/issues/2108)
- [x] [RBAC: New Api authentication](https://github.com/wazuh/wazuh-kibana-app/issues/2103)
- [x] [RBAC: Adapt/Manage Roles in Wazuh UI](https://github.com/wazuh/wazuh-kibana-app/issues/2107)
- [x] [RBAC: Adapt to X-pack](https://github.com/wazuh/wazuh-kibana-app/issues/2104)
- [ ] ~[RBAC: Adapt to SearchGuard](https://github.com/wazuh/wazuh-kibana-app/issues/2105)~
- [x] [RBAC: Adapt to OpenDistro](https://github.com/wazuh/wazuh-kibana-app/issues/2106)
